// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agente.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const apriAnalisi = `-- name: ApriAnalisi :one

INSERT INTO analisi_messaggio (messaggio_id, input_hash, versione, prompt, modello, stato)
VALUES ($1, $2, $3, $4, $5, 'in_corso')
ON CONFLICT (messaggio_id, input_hash, prompt, modello) DO NOTHING
RETURNING analisi_id, messaggio_id, input_hash, versione, prompt, modello, stato, risultato, grezzo, scartato, errore, token_in, token_out, durata_ms, creato_il
`

type ApriAnalisiParams struct {
	MessaggioID uuid.UUID `json:"messaggio_id"`
	InputHash   string    `json:"input_hash"`
	Versione    string    `json:"versione"`
	Prompt      string    `json:"prompt"`
	Modello     string    `json:"modello"`
}

// Analisi semantica (checkpoint 3R §9). L'agente propone: nessuna di queste query tocca thread_id,
// documento, componente o il NAS.
func (q *Queries) ApriAnalisi(ctx context.Context, arg ApriAnalisiParams) (AnalisiMessaggio, error) {
	row := q.db.QueryRow(ctx, apriAnalisi,
		arg.MessaggioID,
		arg.InputHash,
		arg.Versione,
		arg.Prompt,
		arg.Modello,
	)
	var i AnalisiMessaggio
	err := row.Scan(
		&i.AnalisiID,
		&i.MessaggioID,
		&i.InputHash,
		&i.Versione,
		&i.Prompt,
		&i.Modello,
		&i.Stato,
		&i.Risultato,
		&i.Grezzo,
		&i.Scartato,
		&i.Errore,
		&i.TokenIn,
		&i.TokenOut,
		&i.DurataMs,
		&i.CreatoIl,
	)
	return i, err
}

const chiudiAnalisi = `-- name: ChiudiAnalisi :one
UPDATE analisi_messaggio
SET stato = $2, risultato = $3, grezzo = $4, scartato = $5, errore = $6,
    token_in = $7, token_out = $8, durata_ms = $9
WHERE analisi_id = $1
RETURNING analisi_id, messaggio_id, input_hash, versione, prompt, modello, stato, risultato, grezzo, scartato, errore, token_in, token_out, durata_ms, creato_il
`

type ChiudiAnalisiParams struct {
	AnalisiID uuid.UUID        `json:"analisi_id"`
	Stato     StatoAnalisi     `json:"stato"`
	Risultato json.RawMessage  `json:"risultato"`
	Grezzo    *json.RawMessage `json:"grezzo"`
	Scartato  json.RawMessage  `json:"scartato"`
	Errore    pgtype.Text      `json:"errore"`
	TokenIn   pgtype.Int4      `json:"token_in"`
	TokenOut  pgtype.Int4      `json:"token_out"`
	DurataMs  pgtype.Int4      `json:"durata_ms"`
}

func (q *Queries) ChiudiAnalisi(ctx context.Context, arg ChiudiAnalisiParams) (AnalisiMessaggio, error) {
	row := q.db.QueryRow(ctx, chiudiAnalisi,
		arg.AnalisiID,
		arg.Stato,
		arg.Risultato,
		arg.Grezzo,
		arg.Scartato,
		arg.Errore,
		arg.TokenIn,
		arg.TokenOut,
		arg.DurataMs,
	)
	var i AnalisiMessaggio
	err := row.Scan(
		&i.AnalisiID,
		&i.MessaggioID,
		&i.InputHash,
		&i.Versione,
		&i.Prompt,
		&i.Modello,
		&i.Stato,
		&i.Risultato,
		&i.Grezzo,
		&i.Scartato,
		&i.Errore,
		&i.TokenIn,
		&i.TokenOut,
		&i.DurataMs,
		&i.CreatoIl,
	)
	return i, err
}

const contaAnalisiPerStato = `-- name: ContaAnalisiPerStato :many
SELECT stato, count(*) AS n FROM analisi_messaggio GROUP BY stato ORDER BY stato
`

type ContaAnalisiPerStatoRow struct {
	Stato StatoAnalisi `json:"stato"`
	N     int64        `json:"n"`
}

// ContaAnalisiPerStato: la metrica del replay L6 e del banco. «Quante proposte dell'agente sono state
// accettate senza modifica» si legge dal log degli agganci, non da qui.
func (q *Queries) ContaAnalisiPerStato(ctx context.Context) ([]ContaAnalisiPerStatoRow, error) {
	rows, err := q.db.Query(ctx, contaAnalisiPerStato)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContaAnalisiPerStatoRow{}
	for rows.Next() {
		var i ContaAnalisiPerStatoRow
		if err := rows.Scan(&i.Stato, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalisiPerInput = `-- name: GetAnalisiPerInput :one
SELECT analisi_id, messaggio_id, input_hash, versione, prompt, modello, stato, risultato, grezzo, scartato, errore, token_in, token_out, durata_ms, creato_il FROM analisi_messaggio
WHERE messaggio_id = $1 AND input_hash = $2 AND prompt = $3 AND modello = $4
`

type GetAnalisiPerInputParams struct {
	MessaggioID uuid.UUID `json:"messaggio_id"`
	InputHash   string    `json:"input_hash"`
	Prompt      string    `json:"prompt"`
	Modello     string    `json:"modello"`
}

// GetAnalisiPerInput: lo stesso input, con lo stesso prompt e lo stesso modello, e' gia' stato chiesto?
// Serve a non ripagare due volte la stessa domanda e a rendere la rianalisi una scelta, non un effetto.
func (q *Queries) GetAnalisiPerInput(ctx context.Context, arg GetAnalisiPerInputParams) (AnalisiMessaggio, error) {
	row := q.db.QueryRow(ctx, getAnalisiPerInput,
		arg.MessaggioID,
		arg.InputHash,
		arg.Prompt,
		arg.Modello,
	)
	var i AnalisiMessaggio
	err := row.Scan(
		&i.AnalisiID,
		&i.MessaggioID,
		&i.InputHash,
		&i.Versione,
		&i.Prompt,
		&i.Modello,
		&i.Stato,
		&i.Risultato,
		&i.Grezzo,
		&i.Scartato,
		&i.Errore,
		&i.TokenIn,
		&i.TokenOut,
		&i.DurataMs,
		&i.CreatoIl,
	)
	return i, err
}

const listAnalisiMessaggio = `-- name: ListAnalisiMessaggio :many
SELECT analisi_id, messaggio_id, input_hash, versione, prompt, modello, stato, risultato, grezzo, scartato, errore, token_in, token_out, durata_ms, creato_il FROM analisi_messaggio WHERE messaggio_id = $1 ORDER BY creato_il DESC LIMIT 10
`

func (q *Queries) ListAnalisiMessaggio(ctx context.Context, messaggioID uuid.UUID) ([]AnalisiMessaggio, error) {
	rows, err := q.db.Query(ctx, listAnalisiMessaggio, messaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalisiMessaggio{}
	for rows.Next() {
		var i AnalisiMessaggio
		if err := rows.Scan(
			&i.AnalisiID,
			&i.MessaggioID,
			&i.InputHash,
			&i.Versione,
			&i.Prompt,
			&i.Modello,
			&i.Stato,
			&i.Risultato,
			&i.Grezzo,
			&i.Scartato,
			&i.Errore,
			&i.TokenIn,
			&i.TokenOut,
			&i.DurataMs,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ultimaAnalisiCompletata = `-- name: UltimaAnalisiCompletata :one
SELECT analisi_id, messaggio_id, input_hash, versione, prompt, modello, stato, risultato, grezzo, scartato, errore, token_in, token_out, durata_ms, creato_il FROM analisi_messaggio
WHERE messaggio_id = $1 AND stato = 'completata'
ORDER BY creato_il DESC LIMIT 1
`

func (q *Queries) UltimaAnalisiCompletata(ctx context.Context, messaggioID uuid.UUID) (AnalisiMessaggio, error) {
	row := q.db.QueryRow(ctx, ultimaAnalisiCompletata, messaggioID)
	var i AnalisiMessaggio
	err := row.Scan(
		&i.AnalisiID,
		&i.MessaggioID,
		&i.InputHash,
		&i.Versione,
		&i.Prompt,
		&i.Modello,
		&i.Stato,
		&i.Risultato,
		&i.Grezzo,
		&i.Scartato,
		&i.Errore,
		&i.TokenIn,
		&i.TokenOut,
		&i.DurataMs,
		&i.CreatoIl,
	)
	return i, err
}
