// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anagrafica.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBuyer = `-- name: GetBuyer :one
SELECT buyer_id, cliente_id, cognome, nome, email, telefono, ruolo, tipo, manda_file, lingua, confermato, origine, note, creato_il FROM buyer WHERE buyer_id = $1
`

func (q *Queries) GetBuyer(ctx context.Context, buyerID uuid.UUID) (Buyer, error) {
	row := q.db.QueryRow(ctx, getBuyer, buyerID)
	var i Buyer
	err := row.Scan(
		&i.BuyerID,
		&i.ClienteID,
		&i.Cognome,
		&i.Nome,
		&i.Email,
		&i.Telefono,
		&i.Ruolo,
		&i.Tipo,
		&i.MandaFile,
		&i.Lingua,
		&i.Confermato,
		&i.Origine,
		&i.Note,
		&i.CreatoIl,
	)
	return i, err
}

const getBuyerPerEmail = `-- name: GetBuyerPerEmail :one
SELECT buyer_id, cliente_id, cognome, nome, email, telefono, ruolo, tipo, manda_file, lingua, confermato, origine, note, creato_il FROM buyer WHERE email = lower($1)
`

func (q *Queries) GetBuyerPerEmail(ctx context.Context, lower string) (Buyer, error) {
	row := q.db.QueryRow(ctx, getBuyerPerEmail, lower)
	var i Buyer
	err := row.Scan(
		&i.BuyerID,
		&i.ClienteID,
		&i.Cognome,
		&i.Nome,
		&i.Email,
		&i.Telefono,
		&i.Ruolo,
		&i.Tipo,
		&i.MandaFile,
		&i.Lingua,
		&i.Confermato,
		&i.Origine,
		&i.Note,
		&i.CreatoIl,
	)
	return i, err
}

const getCliente = `-- name: GetCliente :one
SELECT cliente_id, cartella_nas, ragione_sociale, profilo, lingua, portale_url, portale_note, regole, attivo, note, creato_il FROM cliente WHERE cliente_id = $1
`

func (q *Queries) GetCliente(ctx context.Context, clienteID uuid.UUID) (Cliente, error) {
	row := q.db.QueryRow(ctx, getCliente, clienteID)
	var i Cliente
	err := row.Scan(
		&i.ClienteID,
		&i.CartellaNas,
		&i.RagioneSociale,
		&i.Profilo,
		&i.Lingua,
		&i.PortaleUrl,
		&i.PortaleNote,
		&i.Regole,
		&i.Attivo,
		&i.Note,
		&i.CreatoIl,
	)
	return i, err
}

const getClientePerDominio = `-- name: GetClientePerDominio :one
SELECT c.cliente_id, c.cartella_nas, c.ragione_sociale, c.profilo, c.lingua, c.portale_url, c.portale_note, c.regole, c.attivo, c.note, c.creato_il FROM dominio_cliente d JOIN cliente c ON c.cliente_id = d.cliente_id WHERE d.dominio = lower($1)
`

func (q *Queries) GetClientePerDominio(ctx context.Context, lower string) (Cliente, error) {
	row := q.db.QueryRow(ctx, getClientePerDominio, lower)
	var i Cliente
	err := row.Scan(
		&i.ClienteID,
		&i.CartellaNas,
		&i.RagioneSociale,
		&i.Profilo,
		&i.Lingua,
		&i.PortaleUrl,
		&i.PortaleNote,
		&i.Regole,
		&i.Attivo,
		&i.Note,
		&i.CreatoIl,
	)
	return i, err
}

const incrementaRegola = `-- name: IncrementaRegola :exec
UPDATE regola SET applicazioni = applicazioni + 1, correzioni_umane = correzioni_umane + $1::int
WHERE regola_id = $2
`

type IncrementaRegolaParams struct {
	Correzione int32  `json:"correzione"`
	RegolaID   string `json:"regola_id"`
}

func (q *Queries) IncrementaRegola(ctx context.Context, arg IncrementaRegolaParams) error {
	_, err := q.db.Exec(ctx, incrementaRegola, arg.Correzione, arg.RegolaID)
	return err
}

const insertBuyer = `-- name: InsertBuyer :one
INSERT INTO buyer (cliente_id, cognome, nome, email, telefono, ruolo, tipo, lingua, origine, note)
VALUES ($1, $2, $3, lower($10), $4, $5, $6, $7, $8, $9)
ON CONFLICT (cliente_id, cognome, nome) DO UPDATE SET email = COALESCE(EXCLUDED.email, buyer.email),
    telefono = COALESCE(EXCLUDED.telefono, buyer.telefono)
RETURNING buyer_id, cliente_id, cognome, nome, email, telefono, ruolo, tipo, manda_file, lingua, confermato, origine, note, creato_il
`

type InsertBuyerParams struct {
	ClienteID uuid.UUID         `json:"cliente_id"`
	Cognome   string            `json:"cognome"`
	Nome      pgtype.Text       `json:"nome"`
	Telefono  pgtype.Text       `json:"telefono"`
	Ruolo     pgtype.Text       `json:"ruolo"`
	Tipo      TipoBuyer         `json:"tipo"`
	Lingua    pgtype.Text       `json:"lingua"`
	Origine   OrigineAnagrafica `json:"origine"`
	Note      pgtype.Text       `json:"note"`
	Email     pgtype.Text       `json:"email"`
}

func (q *Queries) InsertBuyer(ctx context.Context, arg InsertBuyerParams) (Buyer, error) {
	row := q.db.QueryRow(ctx, insertBuyer,
		arg.ClienteID,
		arg.Cognome,
		arg.Nome,
		arg.Telefono,
		arg.Ruolo,
		arg.Tipo,
		arg.Lingua,
		arg.Origine,
		arg.Note,
		arg.Email,
	)
	var i Buyer
	err := row.Scan(
		&i.BuyerID,
		&i.ClienteID,
		&i.Cognome,
		&i.Nome,
		&i.Email,
		&i.Telefono,
		&i.Ruolo,
		&i.Tipo,
		&i.MandaFile,
		&i.Lingua,
		&i.Confermato,
		&i.Origine,
		&i.Note,
		&i.CreatoIl,
	)
	return i, err
}

const listBuyerCliente = `-- name: ListBuyerCliente :many
SELECT buyer_id, cliente_id, cognome, nome, email, telefono, ruolo, tipo, manda_file, lingua, confermato, origine, note, creato_il FROM buyer WHERE cliente_id = $1 ORDER BY cognome, nome
`

func (q *Queries) ListBuyerCliente(ctx context.Context, clienteID uuid.UUID) ([]Buyer, error) {
	rows, err := q.db.Query(ctx, listBuyerCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Buyer{}
	for rows.Next() {
		var i Buyer
		if err := rows.Scan(
			&i.BuyerID,
			&i.ClienteID,
			&i.Cognome,
			&i.Nome,
			&i.Email,
			&i.Telefono,
			&i.Ruolo,
			&i.Tipo,
			&i.MandaFile,
			&i.Lingua,
			&i.Confermato,
			&i.Origine,
			&i.Note,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClienti = `-- name: ListClienti :many
SELECT cliente_id, cartella_nas, ragione_sociale, profilo, lingua, portale_url, portale_note, regole, attivo, note, creato_il FROM cliente WHERE attivo ORDER BY cartella_nas
`

func (q *Queries) ListClienti(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.Query(ctx, listClienti)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cliente{}
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.ClienteID,
			&i.CartellaNas,
			&i.RagioneSociale,
			&i.Profilo,
			&i.Lingua,
			&i.PortaleUrl,
			&i.PortaleNote,
			&i.Regole,
			&i.Attivo,
			&i.Note,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDominiCliente = `-- name: ListDominiCliente :many
SELECT dominio, cliente_id FROM dominio_cliente WHERE cliente_id = $1 ORDER BY dominio
`

func (q *Queries) ListDominiCliente(ctx context.Context, clienteID uuid.UUID) ([]DominioCliente, error) {
	rows, err := q.db.Query(ctx, listDominiCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DominioCliente{}
	for rows.Next() {
		var i DominioCliente
		if err := rows.Scan(&i.Dominio, &i.ClienteID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFaseCatalogo = `-- name: ListFaseCatalogo :many
SELECT nome_fase, ordine, descrizione, ufficio, sla_gg, terminale FROM fase_catalogo ORDER BY ordine
`

func (q *Queries) ListFaseCatalogo(ctx context.Context) ([]FaseCatalogo, error) {
	rows, err := q.db.Query(ctx, listFaseCatalogo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FaseCatalogo{}
	for rows.Next() {
		var i FaseCatalogo
		if err := rows.Scan(
			&i.NomeFase,
			&i.Ordine,
			&i.Descrizione,
			&i.Ufficio,
			&i.SlaGg,
			&i.Terminale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegole = `-- name: ListRegole :many
SELECT regola_id, descrizione, modo, soglia_correzioni, applicazioni, correzioni_umane, attiva_dal FROM regola ORDER BY regola_id
`

func (q *Queries) ListRegole(ctx context.Context) ([]Regola, error) {
	rows, err := q.db.Query(ctx, listRegole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Regola{}
	for rows.Next() {
		var i Regola
		if err := rows.Scan(
			&i.RegolaID,
			&i.Descrizione,
			&i.Modo,
			&i.SogliaCorrezioni,
			&i.Applicazioni,
			&i.CorrezioniUmane,
			&i.AttivaDal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransizioniDa = `-- name: ListTransizioniDa :many
SELECT da, a, automatica, fatto_richiesto FROM transizione WHERE da = $1
`

func (q *Queries) ListTransizioniDa(ctx context.Context, da Fase) ([]Transizione, error) {
	rows, err := q.db.Query(ctx, listTransizioniDa, da)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transizione{}
	for rows.Next() {
		var i Transizione
		if err := rows.Scan(
			&i.Da,
			&i.A,
			&i.Automatica,
			&i.FattoRichiesto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCliente = `-- name: UpsertCliente :one
INSERT INTO cliente (cartella_nas, ragione_sociale, profilo, lingua, portale_url, portale_note, regole)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (cartella_nas) DO UPDATE SET ragione_sociale = EXCLUDED.ragione_sociale, profilo = EXCLUDED.profilo,
    lingua = EXCLUDED.lingua, portale_url = EXCLUDED.portale_url, portale_note = EXCLUDED.portale_note, regole = EXCLUDED.regole
RETURNING cliente_id, cartella_nas, ragione_sociale, profilo, lingua, portale_url, portale_note, regole, attivo, note, creato_il
`

type UpsertClienteParams struct {
	CartellaNas    string          `json:"cartella_nas"`
	RagioneSociale string          `json:"ragione_sociale"`
	Profilo        pgtype.Text     `json:"profilo"`
	Lingua         pgtype.Text     `json:"lingua"`
	PortaleUrl     pgtype.Text     `json:"portale_url"`
	PortaleNote    pgtype.Text     `json:"portale_note"`
	Regole         json.RawMessage `json:"regole"`
}

func (q *Queries) UpsertCliente(ctx context.Context, arg UpsertClienteParams) (Cliente, error) {
	row := q.db.QueryRow(ctx, upsertCliente,
		arg.CartellaNas,
		arg.RagioneSociale,
		arg.Profilo,
		arg.Lingua,
		arg.PortaleUrl,
		arg.PortaleNote,
		arg.Regole,
	)
	var i Cliente
	err := row.Scan(
		&i.ClienteID,
		&i.CartellaNas,
		&i.RagioneSociale,
		&i.Profilo,
		&i.Lingua,
		&i.PortaleUrl,
		&i.PortaleNote,
		&i.Regole,
		&i.Attivo,
		&i.Note,
		&i.CreatoIl,
	)
	return i, err
}

const upsertDominioCliente = `-- name: UpsertDominioCliente :exec
INSERT INTO dominio_cliente (dominio, cliente_id) VALUES (lower($1), $2)
ON CONFLICT (dominio) DO UPDATE SET cliente_id = EXCLUDED.cliente_id
`

type UpsertDominioClienteParams struct {
	Lower     string    `json:"lower"`
	ClienteID uuid.UUID `json:"cliente_id"`
}

func (q *Queries) UpsertDominioCliente(ctx context.Context, arg UpsertDominioClienteParams) error {
	_, err := q.db.Exec(ctx, upsertDominioCliente, arg.Lower, arg.ClienteID)
	return err
}
