// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fascicolo.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assegnaThreadProposte = `-- name: AssegnaThreadProposte :execrows
UPDATE documento_proposta p SET thread_id = $2
FROM allegato a WHERE a.allegato_id = p.allegato_id AND a.messaggio_id = $1 AND p.thread_id IS NULL
`

type AssegnaThreadProposteParams struct {
	MessaggioID uuid.UUID     `json:"messaggio_id"`
	ThreadID    uuid.NullUUID `json:"thread_id"`
}

func (q *Queries) AssegnaThreadProposte(ctx context.Context, arg AssegnaThreadProposteParams) (int64, error) {
	result, err := q.db.Exec(ctx, assegnaThreadProposte, arg.MessaggioID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decidiProposta = `-- name: DecidiProposta :execrows
UPDATE documento_proposta SET stato = $2, deciso_da = $3, deciso_il = now() WHERE proposta_id = $1 AND stato = 'aperta'
`

type DecidiPropostaParams struct {
	PropostaID uuid.UUID     `json:"proposta_id"`
	Stato      StatoProposta `json:"stato"`
	DecisoDa   uuid.NullUUID `json:"deciso_da"`
}

func (q *Queries) DecidiProposta(ctx context.Context, arg DecidiPropostaParams) (int64, error) {
	result, err := q.db.Exec(ctx, decidiProposta, arg.PropostaID, arg.Stato, arg.DecisoDa)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBloccantiThread = `-- name: GetBloccantiThread :one
SELECT thread_id, n_bloccanti, n_da_confermare, n_sul_portale, n_mancanti FROM v_thread_bloccanti WHERE thread_id = $1
`

func (q *Queries) GetBloccantiThread(ctx context.Context, threadID uuid.UUID) (VThreadBloccanti, error) {
	row := q.db.QueryRow(ctx, getBloccantiThread, threadID)
	var i VThreadBloccanti
	err := row.Scan(
		&i.ThreadID,
		&i.NBloccanti,
		&i.NDaConfermare,
		&i.NSulPortale,
		&i.NMancanti,
	)
	return i, err
}

const getCartellaDocumento = `-- name: GetCartellaDocumento :one
SELECT tipo, sottocartella, per_codice FROM cartella_documento WHERE tipo = $1
`

func (q *Queries) GetCartellaDocumento(ctx context.Context, tipo TipoDocumento) (CartellaDocumento, error) {
	row := q.db.QueryRow(ctx, getCartellaDocumento, tipo)
	var i CartellaDocumento
	err := row.Scan(&i.Tipo, &i.Sottocartella, &i.PerCodice)
	return i, err
}

const getDocumento = `-- name: GetDocumento :one
SELECT documento_id, thread_id, componente_id, tipo, codice, rev, nome_file, estensione, sha256, bytes, path_relativo, stato_nas, errore_nas, scritto_il, confermato_da, confermato_il, sostituito_da, nota FROM documento WHERE documento_id = $1
`

func (q *Queries) GetDocumento(ctx context.Context, documentoID uuid.UUID) (Documento, error) {
	row := q.db.QueryRow(ctx, getDocumento, documentoID)
	var i Documento
	err := row.Scan(
		&i.DocumentoID,
		&i.ThreadID,
		&i.ComponenteID,
		&i.Tipo,
		&i.Codice,
		&i.Rev,
		&i.NomeFile,
		&i.Estensione,
		&i.Sha256,
		&i.Bytes,
		&i.PathRelativo,
		&i.StatoNas,
		&i.ErroreNas,
		&i.ScrittoIl,
		&i.ConfermatoDa,
		&i.ConfermatoIl,
		&i.SostituitoDa,
		&i.Nota,
	)
	return i, err
}

const getDocumentoPerHash = `-- name: GetDocumentoPerHash :one
SELECT documento_id, thread_id, componente_id, tipo, codice, rev, nome_file, estensione, sha256, bytes, path_relativo, stato_nas, errore_nas, scritto_il, confermato_da, confermato_il, sostituito_da, nota FROM documento WHERE thread_id = $1 AND sha256 = $2
`

type GetDocumentoPerHashParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Sha256   string    `json:"sha256"`
}

func (q *Queries) GetDocumentoPerHash(ctx context.Context, arg GetDocumentoPerHashParams) (Documento, error) {
	row := q.db.QueryRow(ctx, getDocumentoPerHash, arg.ThreadID, arg.Sha256)
	var i Documento
	err := row.Scan(
		&i.DocumentoID,
		&i.ThreadID,
		&i.ComponenteID,
		&i.Tipo,
		&i.Codice,
		&i.Rev,
		&i.NomeFile,
		&i.Estensione,
		&i.Sha256,
		&i.Bytes,
		&i.PathRelativo,
		&i.StatoNas,
		&i.ErroreNas,
		&i.ScrittoIl,
		&i.ConfermatoDa,
		&i.ConfermatoIl,
		&i.SostituitoDa,
		&i.Nota,
	)
	return i, err
}

const getProposta = `-- name: GetProposta :one
SELECT proposta_id, allegato_id, thread_id, tipo_proposto, codice, rev, componente_id, confidenza, fonte, regola_id, dettagli, stato, deciso_da, deciso_il, creato_il FROM documento_proposta WHERE proposta_id = $1
`

func (q *Queries) GetProposta(ctx context.Context, propostaID uuid.UUID) (DocumentoProposta, error) {
	row := q.db.QueryRow(ctx, getProposta, propostaID)
	var i DocumentoProposta
	err := row.Scan(
		&i.PropostaID,
		&i.AllegatoID,
		&i.ThreadID,
		&i.TipoProposto,
		&i.Codice,
		&i.Rev,
		&i.ComponenteID,
		&i.Confidenza,
		&i.Fonte,
		&i.RegolaID,
		&i.Dettagli,
		&i.Stato,
		&i.DecisoDa,
		&i.DecisoIl,
		&i.CreatoIl,
	)
	return i, err
}

const insertDocumento = `-- name: InsertDocumento :one
INSERT INTO documento (thread_id, componente_id, tipo, codice, rev, nome_file, estensione, sha256, bytes, path_relativo, confermato_da, nota)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING documento_id, thread_id, componente_id, tipo, codice, rev, nome_file, estensione, sha256, bytes, path_relativo, stato_nas, errore_nas, scritto_il, confermato_da, confermato_il, sostituito_da, nota
`

type InsertDocumentoParams struct {
	ThreadID     uuid.UUID     `json:"thread_id"`
	ComponenteID uuid.NullUUID `json:"componente_id"`
	Tipo         TipoDocumento `json:"tipo"`
	Codice       pgtype.Text   `json:"codice"`
	Rev          pgtype.Text   `json:"rev"`
	NomeFile     string        `json:"nome_file"`
	Estensione   string        `json:"estensione"`
	Sha256       string        `json:"sha256"`
	Bytes        pgtype.Int8   `json:"bytes"`
	PathRelativo string        `json:"path_relativo"`
	ConfermatoDa uuid.UUID     `json:"confermato_da"`
	Nota         pgtype.Text   `json:"nota"`
}

func (q *Queries) InsertDocumento(ctx context.Context, arg InsertDocumentoParams) (Documento, error) {
	row := q.db.QueryRow(ctx, insertDocumento,
		arg.ThreadID,
		arg.ComponenteID,
		arg.Tipo,
		arg.Codice,
		arg.Rev,
		arg.NomeFile,
		arg.Estensione,
		arg.Sha256,
		arg.Bytes,
		arg.PathRelativo,
		arg.ConfermatoDa,
		arg.Nota,
	)
	var i Documento
	err := row.Scan(
		&i.DocumentoID,
		&i.ThreadID,
		&i.ComponenteID,
		&i.Tipo,
		&i.Codice,
		&i.Rev,
		&i.NomeFile,
		&i.Estensione,
		&i.Sha256,
		&i.Bytes,
		&i.PathRelativo,
		&i.StatoNas,
		&i.ErroreNas,
		&i.ScrittoIl,
		&i.ConfermatoDa,
		&i.ConfermatoIl,
		&i.SostituitoDa,
		&i.Nota,
	)
	return i, err
}

const insertProvenienza = `-- name: InsertProvenienza :exec
INSERT INTO documento_provenienza (documento_id, allegato_id, rif_id, messaggio_id, ricevuto_il, caricato_da)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (documento_id, ricevuto_il) DO NOTHING
`

type InsertProvenienzaParams struct {
	DocumentoID uuid.UUID     `json:"documento_id"`
	AllegatoID  uuid.NullUUID `json:"allegato_id"`
	RifID       uuid.NullUUID `json:"rif_id"`
	MessaggioID uuid.NullUUID `json:"messaggio_id"`
	RicevutoIl  time.Time     `json:"ricevuto_il"`
	CaricatoDa  uuid.NullUUID `json:"caricato_da"`
}

func (q *Queries) InsertProvenienza(ctx context.Context, arg InsertProvenienzaParams) error {
	_, err := q.db.Exec(ctx, insertProvenienza,
		arg.DocumentoID,
		arg.AllegatoID,
		arg.RifID,
		arg.MessaggioID,
		arg.RicevutoIl,
		arg.CaricatoDa,
	)
	return err
}

const listCartellaDocumento = `-- name: ListCartellaDocumento :many
SELECT tipo, sottocartella, per_codice FROM cartella_documento ORDER BY tipo
`

func (q *Queries) ListCartellaDocumento(ctx context.Context) ([]CartellaDocumento, error) {
	rows, err := q.db.Query(ctx, listCartellaDocumento)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartellaDocumento{}
	for rows.Next() {
		var i CartellaDocumento
		if err := rows.Scan(&i.Tipo, &i.Sottocartella, &i.PerCodice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentiThread = `-- name: ListDocumentiThread :many
SELECT documento_id, thread_id, componente_id, tipo, codice, rev, nome_file, estensione, sha256, bytes, path_relativo, stato_nas, errore_nas, scritto_il, confermato_da, confermato_il, sostituito_da, nota FROM documento WHERE thread_id = $1 ORDER BY componente_id NULLS LAST, tipo, nome_file
`

func (q *Queries) ListDocumentiThread(ctx context.Context, threadID uuid.UUID) ([]Documento, error) {
	rows, err := q.db.Query(ctx, listDocumentiThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Documento{}
	for rows.Next() {
		var i Documento
		if err := rows.Scan(
			&i.DocumentoID,
			&i.ThreadID,
			&i.ComponenteID,
			&i.Tipo,
			&i.Codice,
			&i.Rev,
			&i.NomeFile,
			&i.Estensione,
			&i.Sha256,
			&i.Bytes,
			&i.PathRelativo,
			&i.StatoNas,
			&i.ErroreNas,
			&i.ScrittoIl,
			&i.ConfermatoDa,
			&i.ConfermatoIl,
			&i.SostituitoDa,
			&i.Nota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFascicolo = `-- name: ListFascicolo :many
SELECT thread_id, componente_id, codice, rev, tipo_componente, padre_id, tipo_documento, bloccante, documento_id, stato_nas, path_relativo, proposta_aperta, atteso_da_portale, deroga_id, esito FROM v_fascicolo WHERE thread_id = $1 ORDER BY padre_id NULLS FIRST, codice, tipo_documento
`

func (q *Queries) ListFascicolo(ctx context.Context, threadID uuid.UUID) ([]VFascicolo, error) {
	rows, err := q.db.Query(ctx, listFascicolo, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VFascicolo{}
	for rows.Next() {
		var i VFascicolo
		if err := rows.Scan(
			&i.ThreadID,
			&i.ComponenteID,
			&i.Codice,
			&i.Rev,
			&i.TipoComponente,
			&i.PadreID,
			&i.TipoDocumento,
			&i.Bloccante,
			&i.DocumentoID,
			&i.StatoNas,
			&i.PathRelativo,
			&i.PropostaAperta,
			&i.AttesoDaPortale,
			&i.DerogaID,
			&i.Esito,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposteAperteThread = `-- name: ListProposteAperteThread :many
SELECT p.proposta_id, p.allegato_id, p.thread_id, p.tipo_proposto, p.codice, p.rev, p.componente_id, p.confidenza, p.fonte, p.regola_id, p.dettagli, p.stato, p.deciso_da, p.deciso_il, p.creato_il, a.nome_file, a.estensione, a.bytes, a.sha256, a.path_staging, a.messaggio_id, a.contenitore_id
FROM documento_proposta p JOIN allegato a ON a.allegato_id = p.allegato_id
WHERE p.thread_id = $1 AND p.stato = 'aperta'
ORDER BY a.ricevuto_il, a.messaggio_id, a.contenitore_id NULLS FIRST, a.indice
`

type ListProposteAperteThreadRow struct {
	PropostaID    uuid.UUID       `json:"proposta_id"`
	AllegatoID    uuid.UUID       `json:"allegato_id"`
	ThreadID      uuid.NullUUID   `json:"thread_id"`
	TipoProposto  TipoDocumento   `json:"tipo_proposto"`
	Codice        pgtype.Text     `json:"codice"`
	Rev           pgtype.Text     `json:"rev"`
	ComponenteID  uuid.NullUUID   `json:"componente_id"`
	Confidenza    int16           `json:"confidenza"`
	Fonte         FonteProposta   `json:"fonte"`
	RegolaID      pgtype.Text     `json:"regola_id"`
	Dettagli      json.RawMessage `json:"dettagli"`
	Stato         StatoProposta   `json:"stato"`
	DecisoDa      uuid.NullUUID   `json:"deciso_da"`
	DecisoIl      *time.Time      `json:"deciso_il"`
	CreatoIl      time.Time       `json:"creato_il"`
	NomeFile      string          `json:"nome_file"`
	Estensione    pgtype.Text     `json:"estensione"`
	Bytes         pgtype.Int8     `json:"bytes"`
	Sha256        pgtype.Text     `json:"sha256"`
	PathStaging   pgtype.Text     `json:"path_staging"`
	MessaggioID   uuid.UUID       `json:"messaggio_id"`
	ContenitoreID uuid.NullUUID   `json:"contenitore_id"`
}

func (q *Queries) ListProposteAperteThread(ctx context.Context, threadID uuid.NullUUID) ([]ListProposteAperteThreadRow, error) {
	rows, err := q.db.Query(ctx, listProposteAperteThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProposteAperteThreadRow{}
	for rows.Next() {
		var i ListProposteAperteThreadRow
		if err := rows.Scan(
			&i.PropostaID,
			&i.AllegatoID,
			&i.ThreadID,
			&i.TipoProposto,
			&i.Codice,
			&i.Rev,
			&i.ComponenteID,
			&i.Confidenza,
			&i.Fonte,
			&i.RegolaID,
			&i.Dettagli,
			&i.Stato,
			&i.DecisoDa,
			&i.DecisoIl,
			&i.CreatoIl,
			&i.NomeFile,
			&i.Estensione,
			&i.Bytes,
			&i.Sha256,
			&i.PathStaging,
			&i.MessaggioID,
			&i.ContenitoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposteBulk = `-- name: ListProposteBulk :many
SELECT p.proposta_id, p.allegato_id, p.thread_id, p.tipo_proposto, p.codice, p.rev, p.componente_id, p.confidenza, p.fonte, p.regola_id, p.dettagli, p.stato, p.deciso_da, p.deciso_il, p.creato_il FROM documento_proposta p
WHERE p.thread_id = $1 AND p.stato = 'aperta' AND p.confidenza >= $2 AND p.tipo_proposto <> 'rumore'
`

type ListProposteBulkParams struct {
	ThreadID   uuid.NullUUID `json:"thread_id"`
	Confidenza int16         `json:"confidenza"`
}

func (q *Queries) ListProposteBulk(ctx context.Context, arg ListProposteBulkParams) ([]DocumentoProposta, error) {
	rows, err := q.db.Query(ctx, listProposteBulk, arg.ThreadID, arg.Confidenza)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentoProposta{}
	for rows.Next() {
		var i DocumentoProposta
		if err := rows.Scan(
			&i.PropostaID,
			&i.AllegatoID,
			&i.ThreadID,
			&i.TipoProposto,
			&i.Codice,
			&i.Rev,
			&i.ComponenteID,
			&i.Confidenza,
			&i.Fonte,
			&i.RegolaID,
			&i.Dettagli,
			&i.Stato,
			&i.DecisoDa,
			&i.DecisoIl,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentoErrore = `-- name: SetDocumentoErrore :exec
UPDATE documento SET stato_nas = 'errore', errore_nas = $2 WHERE documento_id = $1
`

type SetDocumentoErroreParams struct {
	DocumentoID uuid.UUID   `json:"documento_id"`
	ErroreNas   pgtype.Text `json:"errore_nas"`
}

func (q *Queries) SetDocumentoErrore(ctx context.Context, arg SetDocumentoErroreParams) error {
	_, err := q.db.Exec(ctx, setDocumentoErrore, arg.DocumentoID, arg.ErroreNas)
	return err
}

const setDocumentoScritto = `-- name: SetDocumentoScritto :exec
UPDATE documento SET stato_nas = 'scritto', scritto_il = now(), errore_nas = NULL WHERE documento_id = $1
`

func (q *Queries) SetDocumentoScritto(ctx context.Context, documentoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDocumentoScritto, documentoID)
	return err
}

const upsertProposta = `-- name: UpsertProposta :one
INSERT INTO documento_proposta (allegato_id, thread_id, tipo_proposto, codice, rev, componente_id, confidenza, fonte, regola_id, dettagli)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (allegato_id) DO UPDATE SET
    thread_id = COALESCE(EXCLUDED.thread_id, documento_proposta.thread_id),
    tipo_proposto = CASE WHEN documento_proposta.stato = 'aperta' THEN EXCLUDED.tipo_proposto ELSE documento_proposta.tipo_proposto END,
    codice = CASE WHEN documento_proposta.stato = 'aperta' THEN EXCLUDED.codice ELSE documento_proposta.codice END,
    rev = CASE WHEN documento_proposta.stato = 'aperta' THEN EXCLUDED.rev ELSE documento_proposta.rev END,
    confidenza = CASE WHEN documento_proposta.stato = 'aperta' THEN EXCLUDED.confidenza ELSE documento_proposta.confidenza END,
    fonte = CASE WHEN documento_proposta.stato = 'aperta' THEN EXCLUDED.fonte ELSE documento_proposta.fonte END,
    dettagli = CASE WHEN documento_proposta.stato = 'aperta' THEN EXCLUDED.dettagli ELSE documento_proposta.dettagli END
RETURNING proposta_id, allegato_id, thread_id, tipo_proposto, codice, rev, componente_id, confidenza, fonte, regola_id, dettagli, stato, deciso_da, deciso_il, creato_il
`

type UpsertPropostaParams struct {
	AllegatoID   uuid.UUID       `json:"allegato_id"`
	ThreadID     uuid.NullUUID   `json:"thread_id"`
	TipoProposto TipoDocumento   `json:"tipo_proposto"`
	Codice       pgtype.Text     `json:"codice"`
	Rev          pgtype.Text     `json:"rev"`
	ComponenteID uuid.NullUUID   `json:"componente_id"`
	Confidenza   int16           `json:"confidenza"`
	Fonte        FonteProposta   `json:"fonte"`
	RegolaID     pgtype.Text     `json:"regola_id"`
	Dettagli     json.RawMessage `json:"dettagli"`
}

func (q *Queries) UpsertProposta(ctx context.Context, arg UpsertPropostaParams) (DocumentoProposta, error) {
	row := q.db.QueryRow(ctx, upsertProposta,
		arg.AllegatoID,
		arg.ThreadID,
		arg.TipoProposto,
		arg.Codice,
		arg.Rev,
		arg.ComponenteID,
		arg.Confidenza,
		arg.Fonte,
		arg.RegolaID,
		arg.Dettagli,
	)
	var i DocumentoProposta
	err := row.Scan(
		&i.PropostaID,
		&i.AllegatoID,
		&i.ThreadID,
		&i.TipoProposto,
		&i.Codice,
		&i.Rev,
		&i.ComponenteID,
		&i.Confidenza,
		&i.Fonte,
		&i.RegolaID,
		&i.Dettagli,
		&i.Stato,
		&i.DecisoDa,
		&i.DecisoIl,
		&i.CreatoIl,
	)
	return i, err
}
