// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fornitori.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const contaAnagrafiche = `-- name: ContaAnagrafiche :one
SELECT (SELECT count(*) FROM cliente)::int               AS clienti,
       (SELECT count(*) FROM dominio_cliente)::int       AS domini_cliente,
       (SELECT count(*) FROM buyer)::int                 AS buyer,
       (SELECT count(*) FROM fornitore)::int             AS fornitori,
       (SELECT count(*) FROM dominio_fornitore)::int     AS domini_fornitore,
       (SELECT count(*) FROM contatto_fornitore)::int    AS contatti_fornitore,
       (SELECT count(*) FROM fornitore_lavorazione)::int AS lavorazioni_fornitore,
       (SELECT count(*) FROM cliente_fornitore_lavorazione)::int AS qualifiche
`

type ContaAnagraficheRow struct {
	Clienti              int32 `json:"clienti"`
	DominiCliente        int32 `json:"domini_cliente"`
	Buyer                int32 `json:"buyer"`
	Fornitori            int32 `json:"fornitori"`
	DominiFornitore      int32 `json:"domini_fornitore"`
	ContattiFornitore    int32 `json:"contatti_fornitore"`
	LavorazioniFornitore int32 `json:"lavorazioni_fornitore"`
	Qualifiche           int32 `json:"qualifiche"`
}

// ContaAnagrafiche: la fotografia dopo un seed (7B.5). Serve allo script di bootstrap per dire i
// numeri finali senza che PowerShell debba conoscere lo schema: Go legge, PowerShell mostra.
func (q *Queries) ContaAnagrafiche(ctx context.Context) (ContaAnagraficheRow, error) {
	row := q.db.QueryRow(ctx, contaAnagrafiche)
	var i ContaAnagraficheRow
	err := row.Scan(
		&i.Clienti,
		&i.DominiCliente,
		&i.Buyer,
		&i.Fornitori,
		&i.DominiFornitore,
		&i.ContattiFornitore,
		&i.LavorazioniFornitore,
		&i.Qualifiche,
	)
	return i, err
}

const contaControparti = `-- name: ContaControparti :many
SELECT controparte_tipo::text AS tipo, count(*)::int AS n FROM messaggio GROUP BY controparte_tipo ORDER BY 1
`

type ContaContropartiRow struct {
	Tipo string `json:"tipo"`
	N    int32  `json:"n"`
}

func (q *Queries) ContaControparti(ctx context.Context) ([]ContaContropartiRow, error) {
	rows, err := q.db.Query(ctx, contaControparti)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContaContropartiRow{}
	for rows.Next() {
		var i ContaContropartiRow
		if err := rows.Scan(&i.Tipo, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eliminaContattoFornitore = `-- name: EliminaContattoFornitore :execrows
DELETE FROM contatto_fornitore WHERE contatto_id = $1 AND fornitore_id = $2
`

type EliminaContattoFornitoreParams struct {
	ContattoID  uuid.UUID `json:"contatto_id"`
	FornitoreID uuid.UUID `json:"fornitore_id"`
}

func (q *Queries) EliminaContattoFornitore(ctx context.Context, arg EliminaContattoFornitoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaContattoFornitore, arg.ContattoID, arg.FornitoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eliminaConvenzione = `-- name: EliminaConvenzione :execrows
DELETE FROM convenzione_codice WHERE convenzione_id = $1 AND cliente_id = $2
`

type EliminaConvenzioneParams struct {
	ConvenzioneID uuid.UUID `json:"convenzione_id"`
	ClienteID     uuid.UUID `json:"cliente_id"`
}

func (q *Queries) EliminaConvenzione(ctx context.Context, arg EliminaConvenzioneParams) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaConvenzione, arg.ConvenzioneID, arg.ClienteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eliminaDominioFornitore = `-- name: EliminaDominioFornitore :execrows
DELETE FROM dominio_fornitore WHERE dominio = lower($1) AND fornitore_id = $2
`

type EliminaDominioFornitoreParams struct {
	Lower       string    `json:"lower"`
	FornitoreID uuid.UUID `json:"fornitore_id"`
}

func (q *Queries) EliminaDominioFornitore(ctx context.Context, arg EliminaDominioFornitoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaDominioFornitore, arg.Lower, arg.FornitoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eliminaLavorazioneFornitore = `-- name: EliminaLavorazioneFornitore :execrows
DELETE FROM fornitore_lavorazione WHERE fornitore_id = $1 AND lavorazione = $2
`

type EliminaLavorazioneFornitoreParams struct {
	FornitoreID uuid.UUID `json:"fornitore_id"`
	Lavorazione string    `json:"lavorazione"`
}

// Fallisce con la chiave esterna se una qualifica dipende da questa capacita': e' voluto. Prima si
// toglie la qualifica, poi la capacita'.
func (q *Queries) EliminaLavorazioneFornitore(ctx context.Context, arg EliminaLavorazioneFornitoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaLavorazioneFornitore, arg.FornitoreID, arg.Lavorazione)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eliminaQualifica = `-- name: EliminaQualifica :execrows
DELETE FROM cliente_fornitore_lavorazione WHERE cliente_id = $1 AND fornitore_id = $2 AND lavorazione = $3
`

type EliminaQualificaParams struct {
	ClienteID   uuid.UUID `json:"cliente_id"`
	FornitoreID uuid.UUID `json:"fornitore_id"`
	Lavorazione string    `json:"lavorazione"`
}

func (q *Queries) EliminaQualifica(ctx context.Context, arg EliminaQualificaParams) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaQualifica, arg.ClienteID, arg.FornitoreID, arg.Lavorazione)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConvenzione = `-- name: GetConvenzione :one
SELECT convenzione_id, cliente_id, modo, espressione, esempio, controesempio, descrizione, attiva, creato_il FROM convenzione_codice WHERE convenzione_id = $1
`

func (q *Queries) GetConvenzione(ctx context.Context, convenzioneID uuid.UUID) (ConvenzioneCodice, error) {
	row := q.db.QueryRow(ctx, getConvenzione, convenzioneID)
	var i ConvenzioneCodice
	err := row.Scan(
		&i.ConvenzioneID,
		&i.ClienteID,
		&i.Modo,
		&i.Espressione,
		&i.Esempio,
		&i.Controesempio,
		&i.Descrizione,
		&i.Attiva,
		&i.CreatoIl,
	)
	return i, err
}

const getFornitore = `-- name: GetFornitore :one
SELECT fornitore_id, ragione_sociale, tipo, lingua, note, attivo, creato_il FROM fornitore WHERE fornitore_id = $1
`

func (q *Queries) GetFornitore(ctx context.Context, fornitoreID uuid.UUID) (Fornitore, error) {
	row := q.db.QueryRow(ctx, getFornitore, fornitoreID)
	var i Fornitore
	err := row.Scan(
		&i.FornitoreID,
		&i.RagioneSociale,
		&i.Tipo,
		&i.Lingua,
		&i.Note,
		&i.Attivo,
		&i.CreatoIl,
	)
	return i, err
}

const getFornitorePerDominio = `-- name: GetFornitorePerDominio :one
SELECT f.fornitore_id, f.ragione_sociale, f.tipo, f.lingua, f.note, f.attivo, f.creato_il FROM dominio_fornitore d JOIN fornitore f ON f.fornitore_id = d.fornitore_id WHERE d.dominio = lower($1)
`

func (q *Queries) GetFornitorePerDominio(ctx context.Context, lower string) (Fornitore, error) {
	row := q.db.QueryRow(ctx, getFornitorePerDominio, lower)
	var i Fornitore
	err := row.Scan(
		&i.FornitoreID,
		&i.RagioneSociale,
		&i.Tipo,
		&i.Lingua,
		&i.Note,
		&i.Attivo,
		&i.CreatoIl,
	)
	return i, err
}

const getFornitorePerRagioneSociale = `-- name: GetFornitorePerRagioneSociale :one
SELECT fornitore_id, ragione_sociale, tipo, lingua, note, attivo, creato_il FROM fornitore WHERE lower(ragione_sociale) = lower($1)
`

func (q *Queries) GetFornitorePerRagioneSociale(ctx context.Context, lower string) (Fornitore, error) {
	row := q.db.QueryRow(ctx, getFornitorePerRagioneSociale, lower)
	var i Fornitore
	err := row.Scan(
		&i.FornitoreID,
		&i.RagioneSociale,
		&i.Tipo,
		&i.Lingua,
		&i.Note,
		&i.Attivo,
		&i.CreatoIl,
	)
	return i, err
}

const insertContattoFornitore = `-- name: InsertContattoFornitore :one
INSERT INTO contatto_fornitore (fornitore_id, nome, email, ruolo, lingua, note)
VALUES ($1, $2, lower($3), $4, $5, $6) RETURNING contatto_id, fornitore_id, nome, email, ruolo, lingua, note
`

type InsertContattoFornitoreParams struct {
	FornitoreID uuid.UUID   `json:"fornitore_id"`
	Nome        pgtype.Text `json:"nome"`
	Lower       string      `json:"lower"`
	Ruolo       pgtype.Text `json:"ruolo"`
	Lingua      pgtype.Text `json:"lingua"`
	Note        pgtype.Text `json:"note"`
}

func (q *Queries) InsertContattoFornitore(ctx context.Context, arg InsertContattoFornitoreParams) (ContattoFornitore, error) {
	row := q.db.QueryRow(ctx, insertContattoFornitore,
		arg.FornitoreID,
		arg.Nome,
		arg.Lower,
		arg.Ruolo,
		arg.Lingua,
		arg.Note,
	)
	var i ContattoFornitore
	err := row.Scan(
		&i.ContattoID,
		&i.FornitoreID,
		&i.Nome,
		&i.Email,
		&i.Ruolo,
		&i.Lingua,
		&i.Note,
	)
	return i, err
}

const insertConvenzione = `-- name: InsertConvenzione :one
INSERT INTO convenzione_codice (cliente_id, modo, espressione, esempio, controesempio, descrizione)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING convenzione_id, cliente_id, modo, espressione, esempio, controesempio, descrizione, attiva, creato_il
`

type InsertConvenzioneParams struct {
	ClienteID     uuid.UUID       `json:"cliente_id"`
	Modo          ModoConvenzione `json:"modo"`
	Espressione   string          `json:"espressione"`
	Esempio       string          `json:"esempio"`
	Controesempio pgtype.Text     `json:"controesempio"`
	Descrizione   string          `json:"descrizione"`
}

func (q *Queries) InsertConvenzione(ctx context.Context, arg InsertConvenzioneParams) (ConvenzioneCodice, error) {
	row := q.db.QueryRow(ctx, insertConvenzione,
		arg.ClienteID,
		arg.Modo,
		arg.Espressione,
		arg.Esempio,
		arg.Controesempio,
		arg.Descrizione,
	)
	var i ConvenzioneCodice
	err := row.Scan(
		&i.ConvenzioneID,
		&i.ClienteID,
		&i.Modo,
		&i.Espressione,
		&i.Esempio,
		&i.Controesempio,
		&i.Descrizione,
		&i.Attiva,
		&i.CreatoIl,
	)
	return i, err
}

const insertConvenzioneLavorazione = `-- name: InsertConvenzioneLavorazione :exec
INSERT INTO convenzione_codice_lavorazione (convenzione_id, lavorazione) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertConvenzioneLavorazioneParams struct {
	ConvenzioneID uuid.UUID `json:"convenzione_id"`
	Lavorazione   string    `json:"lavorazione"`
}

func (q *Queries) InsertConvenzioneLavorazione(ctx context.Context, arg InsertConvenzioneLavorazioneParams) error {
	_, err := q.db.Exec(ctx, insertConvenzioneLavorazione, arg.ConvenzioneID, arg.Lavorazione)
	return err
}

const insertDominioFornitore = `-- name: InsertDominioFornitore :exec
INSERT INTO dominio_fornitore (dominio, fornitore_id) VALUES (lower($1), $2)
`

type InsertDominioFornitoreParams struct {
	Lower       string    `json:"lower"`
	FornitoreID uuid.UUID `json:"fornitore_id"`
}

func (q *Queries) InsertDominioFornitore(ctx context.Context, arg InsertDominioFornitoreParams) error {
	_, err := q.db.Exec(ctx, insertDominioFornitore, arg.Lower, arg.FornitoreID)
	return err
}

const insertFornitore = `-- name: InsertFornitore :one
INSERT INTO fornitore (ragione_sociale, tipo, lingua, note)
VALUES ($1, $2, $3, $4) RETURNING fornitore_id, ragione_sociale, tipo, lingua, note, attivo, creato_il
`

type InsertFornitoreParams struct {
	RagioneSociale string        `json:"ragione_sociale"`
	Tipo           TipoFornitore `json:"tipo"`
	Lingua         pgtype.Text   `json:"lingua"`
	Note           pgtype.Text   `json:"note"`
}

func (q *Queries) InsertFornitore(ctx context.Context, arg InsertFornitoreParams) (Fornitore, error) {
	row := q.db.QueryRow(ctx, insertFornitore,
		arg.RagioneSociale,
		arg.Tipo,
		arg.Lingua,
		arg.Note,
	)
	var i Fornitore
	err := row.Scan(
		&i.FornitoreID,
		&i.RagioneSociale,
		&i.Tipo,
		&i.Lingua,
		&i.Note,
		&i.Attivo,
		&i.CreatoIl,
	)
	return i, err
}

const insertLavorazioneFornitore = `-- name: InsertLavorazioneFornitore :execrows
INSERT INTO fornitore_lavorazione (fornitore_id, lavorazione) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertLavorazioneFornitoreParams struct {
	FornitoreID uuid.UUID `json:"fornitore_id"`
	Lavorazione string    `json:"lavorazione"`
}

func (q *Queries) InsertLavorazioneFornitore(ctx context.Context, arg InsertLavorazioneFornitoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLavorazioneFornitore, arg.FornitoreID, arg.Lavorazione)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertQualifica = `-- name: InsertQualifica :execrows
INSERT INTO cliente_fornitore_lavorazione (cliente_id, fornitore_id, lavorazione)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertQualificaParams struct {
	ClienteID   uuid.UUID `json:"cliente_id"`
	FornitoreID uuid.UUID `json:"fornitore_id"`
	Lavorazione string    `json:"lavorazione"`
}

func (q *Queries) InsertQualifica(ctx context.Context, arg InsertQualificaParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertQualifica, arg.ClienteID, arg.FornitoreID, arg.Lavorazione)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listContattiFornitore = `-- name: ListContattiFornitore :many
SELECT contatto_id, fornitore_id, nome, email, ruolo, lingua, note FROM contatto_fornitore WHERE fornitore_id = $1 ORDER BY email
`

func (q *Queries) ListContattiFornitore(ctx context.Context, fornitoreID uuid.UUID) ([]ContattoFornitore, error) {
	rows, err := q.db.Query(ctx, listContattiFornitore, fornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContattoFornitore{}
	for rows.Next() {
		var i ContattoFornitore
		if err := rows.Scan(
			&i.ContattoID,
			&i.FornitoreID,
			&i.Nome,
			&i.Email,
			&i.Ruolo,
			&i.Lingua,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConvenzioniCliente = `-- name: ListConvenzioniCliente :many

SELECT c.convenzione_id, c.cliente_id, c.modo, c.espressione, c.esempio, c.controesempio, c.descrizione, c.attiva, c.creato_il,
       COALESCE((SELECT array_agg(l.lavorazione ORDER BY l.lavorazione)
                   FROM convenzione_codice_lavorazione l WHERE l.convenzione_id = c.convenzione_id), '{}')::text[] AS lavorazioni
FROM convenzione_codice c WHERE c.cliente_id = $1 ORDER BY c.creato_il, c.espressione
`

type ListConvenzioniClienteRow struct {
	ConvenzioneID uuid.UUID       `json:"convenzione_id"`
	ClienteID     uuid.UUID       `json:"cliente_id"`
	Modo          ModoConvenzione `json:"modo"`
	Espressione   string          `json:"espressione"`
	Esempio       string          `json:"esempio"`
	Controesempio pgtype.Text     `json:"controesempio"`
	Descrizione   string          `json:"descrizione"`
	Attiva        bool            `json:"attiva"`
	CreatoIl      time.Time       `json:"creato_il"`
	Lavorazioni   []string        `json:"lavorazioni"`
}

// ---------------------------------------------------------------- convenzioni di codice (D39)
func (q *Queries) ListConvenzioniCliente(ctx context.Context, clienteID uuid.UUID) ([]ListConvenzioniClienteRow, error) {
	rows, err := q.db.Query(ctx, listConvenzioniCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConvenzioniClienteRow{}
	for rows.Next() {
		var i ListConvenzioniClienteRow
		if err := rows.Scan(
			&i.ConvenzioneID,
			&i.ClienteID,
			&i.Modo,
			&i.Espressione,
			&i.Esempio,
			&i.Controesempio,
			&i.Descrizione,
			&i.Attiva,
			&i.CreatoIl,
			&i.Lavorazioni,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDominiFornitore = `-- name: ListDominiFornitore :many

SELECT dominio, fornitore_id FROM dominio_fornitore WHERE fornitore_id = $1 ORDER BY dominio
`

// ---------------------------------------------------------------- domini e contatti
func (q *Queries) ListDominiFornitore(ctx context.Context, fornitoreID uuid.UUID) ([]DominioFornitore, error) {
	rows, err := q.db.Query(ctx, listDominiFornitore, fornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DominioFornitore{}
	for rows.Next() {
		var i DominioFornitore
		if err := rows.Scan(&i.Dominio, &i.FornitoreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFornitori = `-- name: ListFornitori :many


SELECT f.fornitore_id, f.ragione_sociale, f.tipo, f.lingua, f.note, f.attivo, f.creato_il,
       (SELECT count(*) FROM dominio_fornitore d WHERE d.fornitore_id = f.fornitore_id)  AS n_domini,
       (SELECT count(*) FROM contatto_fornitore c WHERE c.fornitore_id = f.fornitore_id) AS n_contatti,
       (SELECT count(*) FROM fornitore_lavorazione l WHERE l.fornitore_id = f.fornitore_id) AS n_lavorazioni,
       (SELECT count(*) FROM messaggio m WHERE m.controparte_fornitore_id = f.fornitore_id) AS n_messaggi
FROM fornitore f ORDER BY f.attivo DESC, f.ragione_sociale
`

type ListFornitoriRow struct {
	FornitoreID    uuid.UUID     `json:"fornitore_id"`
	RagioneSociale string        `json:"ragione_sociale"`
	Tipo           TipoFornitore `json:"tipo"`
	Lingua         pgtype.Text   `json:"lingua"`
	Note           pgtype.Text   `json:"note"`
	Attivo         bool          `json:"attivo"`
	CreatoIl       time.Time     `json:"creato_il"`
	NDomini        int64         `json:"n_domini"`
	NContatti      int64         `json:"n_contatti"`
	NLavorazioni   int64         `json:"n_lavorazioni"`
	NMessaggi      int64         `json:"n_messaggi"`
}

// Blocco 7A: fornitori, contatti, lavorazioni, qualifiche, convenzioni di codice e la controparte
// del messaggio (0014). Nessuna di queste query scrive `messaggio.thread_id` ne' una proposta:
// la controparte e' un FATTO sul messaggio, il triage resta un suggerimento.
// ---------------------------------------------------------------- fornitore
func (q *Queries) ListFornitori(ctx context.Context) ([]ListFornitoriRow, error) {
	rows, err := q.db.Query(ctx, listFornitori)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFornitoriRow{}
	for rows.Next() {
		var i ListFornitoriRow
		if err := rows.Scan(
			&i.FornitoreID,
			&i.RagioneSociale,
			&i.Tipo,
			&i.Lingua,
			&i.Note,
			&i.Attivo,
			&i.CreatoIl,
			&i.NDomini,
			&i.NContatti,
			&i.NLavorazioni,
			&i.NMessaggi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFornitoriAttivi = `-- name: ListFornitoriAttivi :many
SELECT fornitore_id, ragione_sociale, tipo, lingua, note, attivo, creato_il FROM fornitore WHERE attivo ORDER BY ragione_sociale
`

func (q *Queries) ListFornitoriAttivi(ctx context.Context) ([]Fornitore, error) {
	rows, err := q.db.Query(ctx, listFornitoriAttivi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fornitore{}
	for rows.Next() {
		var i Fornitore
		if err := rows.Scan(
			&i.FornitoreID,
			&i.RagioneSociale,
			&i.Tipo,
			&i.Lingua,
			&i.Note,
			&i.Attivo,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFornitoriPerContatto = `-- name: ListFornitoriPerContatto :many
SELECT f.fornitore_id, f.ragione_sociale, f.tipo, f.lingua, f.note, f.attivo, f.creato_il FROM contatto_fornitore c JOIN fornitore f ON f.fornitore_id = c.fornitore_id
WHERE c.email = lower($1) ORDER BY f.ragione_sociale
`

// ListFornitoriPerContatto: TUTTI i fornitori che hanno questa email fra i contatti. La chiave
// unica e' (fornitore_id, email), quindi possono essere due: il resolver risponde `ambiguo`.
func (q *Queries) ListFornitoriPerContatto(ctx context.Context, lower string) ([]Fornitore, error) {
	rows, err := q.db.Query(ctx, listFornitoriPerContatto, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fornitore{}
	for rows.Next() {
		var i Fornitore
		if err := rows.Scan(
			&i.FornitoreID,
			&i.RagioneSociale,
			&i.Tipo,
			&i.Lingua,
			&i.Note,
			&i.Attivo,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFornitoriQualificati = `-- name: ListFornitoriQualificati :many
SELECT f.fornitore_id, f.ragione_sociale, f.tipo, f.lingua, f.note, f.attivo, f.creato_il FROM cliente_fornitore_lavorazione q JOIN fornitore f ON f.fornitore_id = q.fornitore_id
WHERE q.cliente_id = $1 AND q.lavorazione = $2 AND f.attivo ORDER BY f.ragione_sociale
`

type ListFornitoriQualificatiParams struct {
	ClienteID   uuid.UUID `json:"cliente_id"`
	Lavorazione string    `json:"lavorazione"`
}

// ListFornitoriQualificati: chi e' qualificato per QUESTO cliente su QUESTA lavorazione. Chi fa la
// lavorazione ma non e' qualificato per il cliente non compare: e' la differenza fra
// fornitore_lavorazione (capacita') e cliente_fornitore_lavorazione (qualifica).
func (q *Queries) ListFornitoriQualificati(ctx context.Context, arg ListFornitoriQualificatiParams) ([]Fornitore, error) {
	rows, err := q.db.Query(ctx, listFornitoriQualificati, arg.ClienteID, arg.Lavorazione)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fornitore{}
	for rows.Next() {
		var i Fornitore
		if err := rows.Scan(
			&i.FornitoreID,
			&i.RagioneSociale,
			&i.Tipo,
			&i.Lingua,
			&i.Note,
			&i.Attivo,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLavorazioni = `-- name: ListLavorazioni :many

SELECT codice, descrizione FROM lavorazione ORDER BY descrizione
`

// ---------------------------------------------------------------- lavorazioni
func (q *Queries) ListLavorazioni(ctx context.Context) ([]Lavorazione, error) {
	rows, err := q.db.Query(ctx, listLavorazioni)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lavorazione{}
	for rows.Next() {
		var i Lavorazione
		if err := rows.Scan(&i.Codice, &i.Descrizione); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLavorazioniFornitore = `-- name: ListLavorazioniFornitore :many
SELECT l.codice, l.descrizione FROM fornitore_lavorazione fl JOIN lavorazione l ON l.codice = fl.lavorazione
WHERE fl.fornitore_id = $1 ORDER BY l.descrizione
`

func (q *Queries) ListLavorazioniFornitore(ctx context.Context, fornitoreID uuid.UUID) ([]Lavorazione, error) {
	rows, err := q.db.Query(ctx, listLavorazioniFornitore, fornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lavorazione{}
	for rows.Next() {
		var i Lavorazione
		if err := rows.Scan(&i.Codice, &i.Descrizione); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessaggiDaRitriage = `-- name: ListMessaggiDaRitriage :many
SELECT m.messaggio_id, m.canale, m.chiave_esterna, m.conversazione_id, m.parent_messaggio_id, m.thread_id, m.aggancio, m.agganciato_da, m.agganciato_il, m.direzione, m.data_evento, m.mittente_nome, m.mittente_indirizzo, m.buyer_id, m.destinatari, m.oggetto, m.corpo_testo, m.corpo_html, m.lingua, m.importanza, m.nota_operatore, m.n_allegati, m.registrato_il, m.registrato_da, m.interno, m.controparte_tipo, m.controparte_cliente_id, m.controparte_fornitore_id, m.controparte_via, m.controparte_il, m.richiesta_fornitore_id, m.controparte_altro_id FROM messaggio m
WHERE m.thread_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM proposta_triage p WHERE p.messaggio_id = m.messaggio_id AND p.stato <> 'proposta')
  AND (   lower(m.mittente_indirizzo) = lower($1::text)
       OR ($2::text <> '' AND lower(split_part(m.mittente_indirizzo, '@', 2)) = lower($2::text))
       OR EXISTS (SELECT 1 FROM jsonb_array_elements(m.destinatari) d
                   WHERE lower(d->>'indirizzo') = lower($1::text)
                      OR ($2::text <> '' AND lower(split_part(d->>'indirizzo', '@', 2)) = lower($2::text))))
ORDER BY m.data_evento
`

type ListMessaggiDaRitriageParams struct {
	Indirizzo string `json:"indirizzo"`
	Dominio   string `json:"dominio"`
}

// ListMessaggiDaRitriage: i messaggi NON DECISI che parlano con questo indirizzo o questo dominio,
// in entrata (mittente) o in uscita (uno dei destinatari). Non decisi = nessuna RFQ e nessuna
// proposta accettata o rifiutata: le decisioni prese non si toccano (7A.3).
func (q *Queries) ListMessaggiDaRitriage(ctx context.Context, arg ListMessaggiDaRitriageParams) ([]Messaggio, error) {
	rows, err := q.db.Query(ctx, listMessaggiDaRitriage, arg.Indirizzo, arg.Dominio)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messaggio{}
	for rows.Next() {
		var i Messaggio
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.ChiaveEsterna,
			&i.ConversazioneID,
			&i.ParentMessaggioID,
			&i.ThreadID,
			&i.Aggancio,
			&i.AgganciatoDa,
			&i.AgganciatoIl,
			&i.Direzione,
			&i.DataEvento,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.BuyerID,
			&i.Destinatari,
			&i.Oggetto,
			&i.CorpoTesto,
			&i.CorpoHtml,
			&i.Lingua,
			&i.Importanza,
			&i.NotaOperatore,
			&i.NAllegati,
			&i.RegistratoIl,
			&i.RegistratoDa,
			&i.Interno,
			&i.ControparteTipo,
			&i.ControparteClienteID,
			&i.ControparteFornitoreID,
			&i.ControparteVia,
			&i.ControparteIl,
			&i.RichiestaFornitoreID,
			&i.ControparteAltroID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessaggiPerControparteFornitore = `-- name: ListMessaggiPerControparteFornitore :many
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il, richiesta_fornitore_id, controparte_altro_id FROM messaggio WHERE controparte_fornitore_id = $1 ORDER BY data_evento DESC LIMIT 50
`

func (q *Queries) ListMessaggiPerControparteFornitore(ctx context.Context, controparteFornitoreID uuid.NullUUID) ([]Messaggio, error) {
	rows, err := q.db.Query(ctx, listMessaggiPerControparteFornitore, controparteFornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messaggio{}
	for rows.Next() {
		var i Messaggio
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.ChiaveEsterna,
			&i.ConversazioneID,
			&i.ParentMessaggioID,
			&i.ThreadID,
			&i.Aggancio,
			&i.AgganciatoDa,
			&i.AgganciatoIl,
			&i.Direzione,
			&i.DataEvento,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.BuyerID,
			&i.Destinatari,
			&i.Oggetto,
			&i.CorpoTesto,
			&i.CorpoHtml,
			&i.Lingua,
			&i.Importanza,
			&i.NotaOperatore,
			&i.NAllegati,
			&i.RegistratoIl,
			&i.RegistratoDa,
			&i.Interno,
			&i.ControparteTipo,
			&i.ControparteClienteID,
			&i.ControparteFornitoreID,
			&i.ControparteVia,
			&i.ControparteIl,
			&i.RichiestaFornitoreID,
			&i.ControparteAltroID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessaggiSenzaControparte = `-- name: ListMessaggiSenzaControparte :many
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il, richiesta_fornitore_id, controparte_altro_id FROM messaggio WHERE controparte_il IS NULL ORDER BY registrato_il LIMIT $1
`

// I messaggi entrati prima della 0014: la migrazione li lascia `sconosciuto` senza data, e il
// ricalcolo al primo avvio li risolve a lotti (CP8).
func (q *Queries) ListMessaggiSenzaControparte(ctx context.Context, limit int32) ([]Messaggio, error) {
	rows, err := q.db.Query(ctx, listMessaggiSenzaControparte, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messaggio{}
	for rows.Next() {
		var i Messaggio
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.ChiaveEsterna,
			&i.ConversazioneID,
			&i.ParentMessaggioID,
			&i.ThreadID,
			&i.Aggancio,
			&i.AgganciatoDa,
			&i.AgganciatoIl,
			&i.Direzione,
			&i.DataEvento,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.BuyerID,
			&i.Destinatari,
			&i.Oggetto,
			&i.CorpoTesto,
			&i.CorpoHtml,
			&i.Lingua,
			&i.Importanza,
			&i.NotaOperatore,
			&i.NAllegati,
			&i.RegistratoIl,
			&i.RegistratoDa,
			&i.Interno,
			&i.ControparteTipo,
			&i.ControparteClienteID,
			&i.ControparteFornitoreID,
			&i.ControparteVia,
			&i.ControparteIl,
			&i.RichiestaFornitoreID,
			&i.ControparteAltroID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualificheCliente = `-- name: ListQualificheCliente :many
SELECT q.cliente_id, q.fornitore_id, q.lavorazione, f.ragione_sociale AS fornitore, f.tipo, l.descrizione AS lavorazione_descrizione
FROM cliente_fornitore_lavorazione q
JOIN fornitore f ON f.fornitore_id = q.fornitore_id
JOIN lavorazione l ON l.codice = q.lavorazione
WHERE q.cliente_id = $1 ORDER BY l.descrizione, f.ragione_sociale
`

type ListQualificheClienteRow struct {
	ClienteID              uuid.UUID     `json:"cliente_id"`
	FornitoreID            uuid.UUID     `json:"fornitore_id"`
	Lavorazione            string        `json:"lavorazione"`
	Fornitore              string        `json:"fornitore"`
	Tipo                   TipoFornitore `json:"tipo"`
	LavorazioneDescrizione string        `json:"lavorazione_descrizione"`
}

func (q *Queries) ListQualificheCliente(ctx context.Context, clienteID uuid.UUID) ([]ListQualificheClienteRow, error) {
	rows, err := q.db.Query(ctx, listQualificheCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualificheClienteRow{}
	for rows.Next() {
		var i ListQualificheClienteRow
		if err := rows.Scan(
			&i.ClienteID,
			&i.FornitoreID,
			&i.Lavorazione,
			&i.Fornitore,
			&i.Tipo,
			&i.LavorazioneDescrizione,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualificheFornitore = `-- name: ListQualificheFornitore :many

SELECT q.cliente_id, q.fornitore_id, q.lavorazione, c.cartella_nas, c.ragione_sociale AS cliente, l.descrizione AS lavorazione_descrizione
FROM cliente_fornitore_lavorazione q
JOIN cliente c ON c.cliente_id = q.cliente_id
JOIN lavorazione l ON l.codice = q.lavorazione
WHERE q.fornitore_id = $1 ORDER BY c.cartella_nas, l.descrizione
`

type ListQualificheFornitoreRow struct {
	ClienteID              uuid.UUID `json:"cliente_id"`
	FornitoreID            uuid.UUID `json:"fornitore_id"`
	Lavorazione            string    `json:"lavorazione"`
	CartellaNas            string    `json:"cartella_nas"`
	Cliente                string    `json:"cliente"`
	LavorazioneDescrizione string    `json:"lavorazione_descrizione"`
}

// ---------------------------------------------------------------- qualifiche: cliente x fornitore x lavorazione
func (q *Queries) ListQualificheFornitore(ctx context.Context, fornitoreID uuid.UUID) ([]ListQualificheFornitoreRow, error) {
	rows, err := q.db.Query(ctx, listQualificheFornitore, fornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualificheFornitoreRow{}
	for rows.Next() {
		var i ListQualificheFornitoreRow
		if err := rows.Scan(
			&i.ClienteID,
			&i.FornitoreID,
			&i.Lavorazione,
			&i.CartellaNas,
			&i.Cliente,
			&i.LavorazioneDescrizione,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setControparteMessaggio = `-- name: SetControparteMessaggio :execrows

UPDATE messaggio
   SET controparte_tipo = $2, controparte_cliente_id = $3, controparte_fornitore_id = $4,
       controparte_altro_id = $5,
       controparte_via = $6::via_controparte, controparte_il = now()
 WHERE messaggio_id = $1
   AND (controparte_via IS DISTINCT FROM 'manuale' OR $6::via_controparte = 'manuale')
`

type SetControparteMessaggioParams struct {
	MessaggioID            uuid.UUID          `json:"messaggio_id"`
	ControparteTipo        TipoControparte    `json:"controparte_tipo"`
	ControparteClienteID   uuid.NullUUID      `json:"controparte_cliente_id"`
	ControparteFornitoreID uuid.NullUUID      `json:"controparte_fornitore_id"`
	ControparteAltroID     uuid.NullUUID      `json:"controparte_altro_id"`
	Via                    NullViaControparte `json:"via"`
}

// ---------------------------------------------------------------- la controparte sul messaggio (D33)
// Una controparte decisa da una persona (`manuale`) non si sovrascrive con una risoluzione
// automatica: il ricalcolo passa oltre.
func (q *Queries) SetControparteMessaggio(ctx context.Context, arg SetControparteMessaggioParams) (int64, error) {
	result, err := q.db.Exec(ctx, setControparteMessaggio,
		arg.MessaggioID,
		arg.ControparteTipo,
		arg.ControparteClienteID,
		arg.ControparteFornitoreID,
		arg.ControparteAltroID,
		arg.Via,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setConvenzioneAttiva = `-- name: SetConvenzioneAttiva :execrows
UPDATE convenzione_codice SET attiva = $3 WHERE convenzione_id = $1 AND cliente_id = $2
`

type SetConvenzioneAttivaParams struct {
	ConvenzioneID uuid.UUID `json:"convenzione_id"`
	ClienteID     uuid.UUID `json:"cliente_id"`
	Attiva        bool      `json:"attiva"`
}

func (q *Queries) SetConvenzioneAttiva(ctx context.Context, arg SetConvenzioneAttivaParams) (int64, error) {
	result, err := q.db.Exec(ctx, setConvenzioneAttiva, arg.ConvenzioneID, arg.ClienteID, arg.Attiva)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFornitore = `-- name: UpdateFornitore :one
UPDATE fornitore SET ragione_sociale = $2, tipo = $3, lingua = $4, note = $5, attivo = $6
WHERE fornitore_id = $1 RETURNING fornitore_id, ragione_sociale, tipo, lingua, note, attivo, creato_il
`

type UpdateFornitoreParams struct {
	FornitoreID    uuid.UUID     `json:"fornitore_id"`
	RagioneSociale string        `json:"ragione_sociale"`
	Tipo           TipoFornitore `json:"tipo"`
	Lingua         pgtype.Text   `json:"lingua"`
	Note           pgtype.Text   `json:"note"`
	Attivo         bool          `json:"attivo"`
}

func (q *Queries) UpdateFornitore(ctx context.Context, arg UpdateFornitoreParams) (Fornitore, error) {
	row := q.db.QueryRow(ctx, updateFornitore,
		arg.FornitoreID,
		arg.RagioneSociale,
		arg.Tipo,
		arg.Lingua,
		arg.Note,
		arg.Attivo,
	)
	var i Fornitore
	err := row.Scan(
		&i.FornitoreID,
		&i.RagioneSociale,
		&i.Tipo,
		&i.Lingua,
		&i.Note,
		&i.Attivo,
		&i.CreatoIl,
	)
	return i, err
}
