// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const annullaJobScaduti = `-- name: AnnullaJobScaduti :execrows
UPDATE job SET stato = 'annullato'::stato_job, lease_fino_a = NULL, lease_token = NULL, worker_id = NULL,
    chiuso_il = now(), errore = concat_ws(' ', errore, '[scaduto prima di essere eseguito]')
WHERE scade_il IS NOT NULL AND scade_il <= now() AND stato IN ('pronto','in_corso')
`

// Job interattivi che non servono più: nessuno li eseguirà, e restare 'pronto' li farebbe apparire
// come lavoro arretrato.
func (q *Queries) AnnullaJobScaduti(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, annullaJobScaduti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bloccaTentativo = `-- name: BloccaTentativo :one
SELECT job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il FROM job
WHERE job_id = $1
  AND stato = 'in_corso' AND lease_token = $2 AND worker_id = $3
  AND lease_fino_a > now() AND now() <= avviato_il + make_interval(secs => durata_max_s)
FOR UPDATE
`

type BloccaTentativoParams struct {
	JobID      int64         `json:"job_id"`
	LeaseToken uuid.NullUUID `json:"lease_token"`
	WorkerID   pgtype.Text   `json:"worker_id"`
}

// Usata dall'ingest: blocca la riga del job per tutta la transazione del lotto, così un tentativo
// concorrente non può diventare valido a metà scrittura.
func (q *Queries) BloccaTentativo(ctx context.Context, arg BloccaTentativoParams) (Job, error) {
	row := q.db.QueryRow(ctx, bloccaTentativo, arg.JobID, arg.LeaseToken, arg.WorkerID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const claimJob = `-- name: ClaimJob :one
UPDATE job SET stato = 'in_corso',
    lease_token  = gen_random_uuid(),
    avviato_il   = now(),
    lease_fino_a = now() + make_interval(secs => lease_s),
    worker_id    = $1,
    tentativi    = tentativi + 1
WHERE job_id = (
    SELECT j.job_id FROM job j
    WHERE j.stato = 'pronto' AND j.worker_tipo = $2 AND j.non_prima_di <= now()
      AND (j.scade_il IS NULL OR j.scade_il > now())
    ORDER BY j.priorita, j.job_id
    FOR UPDATE SKIP LOCKED LIMIT 1)
RETURNING job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il
`

type ClaimJobParams struct {
	WorkerID   pgtype.Text `json:"worker_id"`
	WorkerTipo WorkerTipo  `json:"worker_tipo"`
}

// Un solo UPDATE: il tentativo nasce qui con un token nuovo e con avviato_il, che fissa l'inizio da
// cui si misura durata_max_s. Un job interattivo già scaduto non viene assegnato a nessuno.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.WorkerID, arg.WorkerTipo)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const completaJob = `-- name: CompletaJob :one
UPDATE job SET stato = 'fatto', risultato = $1, errore = NULL,
    lease_fino_a = NULL, lease_token = NULL, chiuso_il = now()
WHERE job_id = $2
  AND stato = 'in_corso' AND lease_token = $3 AND worker_id = $4
  AND lease_fino_a > now() AND now() <= avviato_il + make_interval(secs => durata_max_s)
RETURNING job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il
`

type CompletaJobParams struct {
	Risultato  *json.RawMessage `json:"risultato"`
	JobID      int64            `json:"job_id"`
	LeaseToken uuid.NullUUID    `json:"lease_token"`
	WorkerID   pgtype.Text      `json:"worker_id"`
}

func (q *Queries) CompletaJob(ctx context.Context, arg CompletaJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, completaJob,
		arg.Risultato,
		arg.JobID,
		arg.LeaseToken,
		arg.WorkerID,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const contaJobPerStato = `-- name: ContaJobPerStato :many
SELECT worker_tipo, stato, count(*) AS n FROM job GROUP BY worker_tipo, stato ORDER BY worker_tipo, stato
`

type ContaJobPerStatoRow struct {
	WorkerTipo WorkerTipo `json:"worker_tipo"`
	Stato      StatoJob   `json:"stato"`
	N          int64      `json:"n"`
}

func (q *Queries) ContaJobPerStato(ctx context.Context) ([]ContaJobPerStatoRow, error) {
	rows, err := q.db.Query(ctx, contaJobPerStato)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContaJobPerStatoRow{}
	for rows.Next() {
		var i ContaJobPerStatoRow
		if err := rows.Scan(&i.WorkerTipo, &i.Stato, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eliminaJobVecchi = `-- name: EliminaJobVecchi :execrows
DELETE FROM job
WHERE stato IN ('fatto','fallito','annullato') AND chiuso_il IS NOT NULL
  AND chiuso_il < now() - make_interval(days => $1::int)
`

func (q *Queries) EliminaJobVecchi(ctx context.Context, giorni int32) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaJobVecchi, giorni)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const esisteJobPronto = `-- name: EsisteJobPronto :one
SELECT EXISTS (SELECT 1 FROM job WHERE tipo = $1 AND stato IN ('pronto','in_corso'))
`

func (q *Queries) EsisteJobPronto(ctx context.Context, tipo TipoJob) (bool, error) {
	row := q.db.QueryRow(ctx, esisteJobPronto, tipo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const fallisciJob = `-- name: FallisciJob :one
UPDATE job SET
    stato        = CASE WHEN tentativi >= max_tentativi OR $1::boolean THEN 'fallito'::stato_job ELSE 'pronto'::stato_job END,
    non_prima_di = now() + make_interval(secs => LEAST(600, 15 * power(2, tentativi))::int),
    lease_fino_a = NULL, lease_token = NULL, worker_id = NULL, errore = $2,
    chiuso_il    = CASE WHEN tentativi >= max_tentativi OR $1::boolean THEN now() END
WHERE job_id = $3
  AND stato = 'in_corso' AND lease_token = $4 AND worker_id = $5
  AND lease_fino_a > now() AND now() <= avviato_il + make_interval(secs => durata_max_s)
RETURNING job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il
`

type FallisciJobParams struct {
	Definitivo bool          `json:"definitivo"`
	Errore     pgtype.Text   `json:"errore"`
	JobID      int64         `json:"job_id"`
	LeaseToken uuid.NullUUID `json:"lease_token"`
	WorkerID   pgtype.Text   `json:"worker_id"`
}

func (q *Queries) FallisciJob(ctx context.Context, arg FallisciJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, fallisciJob,
		arg.Definitivo,
		arg.Errore,
		arg.JobID,
		arg.LeaseToken,
		arg.WorkerID,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il FROM job WHERE job_id = $1
`

func (q *Queries) GetJob(ctx context.Context, jobID int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const heartbeatJob = `-- name: HeartbeatJob :execrows
UPDATE job SET lease_fino_a = now() + make_interval(secs => lease_s)
WHERE job_id = $1
  AND stato = 'in_corso' AND lease_token = $2 AND worker_id = $3
  AND lease_fino_a > now() AND now() <= avviato_il + make_interval(secs => durata_max_s)
`

type HeartbeatJobParams struct {
	JobID      int64         `json:"job_id"`
	LeaseToken uuid.NullUUID `json:"lease_token"`
	WorkerID   pgtype.Text   `json:"worker_id"`
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatJob, arg.JobID, arg.LeaseToken, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertJob = `-- name: InsertJob :one

INSERT INTO job (tipo, worker_tipo, payload, chiave_idempotenza, priorita, non_prima_di,
                 lease_s, durata_max_s, max_tentativi, casella_id, postazione_id, richiesto_da, scade_il)
VALUES ($1, $2, $3, $4, $5, COALESCE($6::timestamptz, now()),
        $7, $8, COALESCE($9::int, 5),
        $10, $11, $12, $13)
ON CONFLICT (chiave_idempotenza) WHERE stato IN ('pronto','in_corso') DO NOTHING
RETURNING job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il
`

type InsertJobParams struct {
	Tipo              TipoJob         `json:"tipo"`
	WorkerTipo        WorkerTipo      `json:"worker_tipo"`
	Payload           json.RawMessage `json:"payload"`
	ChiaveIdempotenza pgtype.Text     `json:"chiave_idempotenza"`
	Priorita          int16           `json:"priorita"`
	NonPrimaDi        *time.Time      `json:"non_prima_di"`
	LeaseS            int32           `json:"lease_s"`
	DurataMaxS        int32           `json:"durata_max_s"`
	MaxTentativi      pgtype.Int4     `json:"max_tentativi"`
	CasellaID         uuid.NullUUID   `json:"casella_id"`
	PostazioneID      uuid.NullUUID   `json:"postazione_id"`
	RichiestoDa       uuid.NullUUID   `json:"richiesto_da"`
	ScadeIl           *time.Time      `json:"scade_il"`
}

// Coda dei job.
//
// Il PREDICATO DI VALIDITÀ DEL TENTATIVO (piano §2.3) compare identico in HeartbeatJob, CompletaJob,
// FallisciJob e BloccaTentativo:
//
//	stato = 'in_corso' AND lease_token = $token AND worker_id = $worker
//	AND lease_fino_a > now() AND now() <= avviato_il + durata_max_s
//
// Zero righe significa «questo tentativo non vale più» e il chiamante risponde 409 senza applicare
// nulla. Non va rilassato in nessuno dei quattro punti: basta un punto scoperto perché il risultato
// di un tentativo scaduto si applichi al lavoro di quello nuovo.
// max_tentativi è narg con COALESCE e non un parametro obbligatorio: uno zero Go passato per
// distrazione varrebbe «nessun tentativo» e il job non partirebbe mai. Omesso = il default dello
// schema (5); jobs.MaxTentativiPer lo alza per le scritture sul NAS (voce 1.7).
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.Tipo,
		arg.WorkerTipo,
		arg.Payload,
		arg.ChiaveIdempotenza,
		arg.Priorita,
		arg.NonPrimaDi,
		arg.LeaseS,
		arg.DurataMaxS,
		arg.MaxTentativi,
		arg.CasellaID,
		arg.PostazioneID,
		arg.RichiestoDa,
		arg.ScadeIl,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const jobPendenteConPrefisso = `-- name: JobPendenteConPrefisso :one
SELECT job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il FROM job WHERE chiave_idempotenza LIKE $1::text || '%'
  AND stato IN ('pronto','in_corso') ORDER BY job_id DESC LIMIT 1
`

// Il sync storico è per casella dalla 0004 (chiave `sync_storico:<casella_id>`): il badge della
// schermata deve poter chiedere «ce n'è uno in corso, di chiunque» senza conoscerne la casella.
func (q *Queries) JobPendenteConPrefisso(ctx context.Context, prefisso string) (Job, error) {
	row := q.db.QueryRow(ctx, jobPendenteConPrefisso, prefisso)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const jobPendentePerChiave = `-- name: JobPendentePerChiave :one
SELECT job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il FROM job WHERE chiave_idempotenza = $1 AND stato IN ('pronto','in_corso') LIMIT 1
`

func (q *Queries) JobPendentePerChiave(ctx context.Context, chiaveIdempotenza pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, jobPendentePerChiave, chiaveIdempotenza)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const listJob = `-- name: ListJob :many
SELECT job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il FROM job
WHERE ($2::stato_job IS NULL OR stato = $2::stato_job)
ORDER BY job_id DESC LIMIT $1
`

type ListJobParams struct {
	Limit int32        `json:"limit"`
	Stato NullStatoJob `json:"stato"`
}

func (q *Queries) ListJob(ctx context.Context, arg ListJobParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJob, arg.Limit, arg.Stato)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.Tipo,
			&i.WorkerTipo,
			&i.Payload,
			&i.ChiaveIdempotenza,
			&i.Stato,
			&i.Priorita,
			&i.Tentativi,
			&i.MaxTentativi,
			&i.NonPrimaDi,
			&i.LeaseFinoA,
			&i.WorkerID,
			&i.Risultato,
			&i.Errore,
			&i.CreatoIl,
			&i.AggiornatoIl,
			&i.ChiusoIl,
			&i.CasellaID,
			&i.PostazioneID,
			&i.RichiestoDa,
			&i.LeaseS,
			&i.DurataMaxS,
			&i.LeaseToken,
			&i.AvviatoIl,
			&i.ScadeIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaseTokenInCorso = `-- name: ListLeaseTokenInCorso :many
SELECT lease_token FROM job WHERE stato = 'in_corso' AND lease_token IS NOT NULL
`

// I token dei tentativi vivi: un file .parte.<token> il cui token non è qui appartiene a un tentativo
// che non esiste più e va rimosso dallo scheduler (voce 2.3, N8).
func (q *Queries) ListLeaseTokenInCorso(ctx context.Context) ([]uuid.NullUUID, error) {
	rows, err := q.db.Query(ctx, listLeaseTokenInCorso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.NullUUID{}
	for rows.Next() {
		var lease_token uuid.NullUUID
		if err := rows.Scan(&lease_token); err != nil {
			return nil, err
		}
		items = append(items, lease_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerPresenza = `-- name: ListWorkerPresenza :many
SELECT worker_tipo, worker_id, ultimo_claim, ultimo_job_il FROM worker_presenza ORDER BY worker_tipo
`

func (q *Queries) ListWorkerPresenza(ctx context.Context) ([]WorkerPresenza, error) {
	rows, err := q.db.Query(ctx, listWorkerPresenza)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkerPresenza{}
	for rows.Next() {
		var i WorkerPresenza
		if err := rows.Scan(
			&i.WorkerTipo,
			&i.WorkerID,
			&i.UltimoClaim,
			&i.UltimoJobIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riaccodaJob = `-- name: RiaccodaJob :one
UPDATE job SET stato = 'pronto', tentativi = 0, errore = NULL, non_prima_di = now(), chiuso_il = NULL,
    lease_fino_a = NULL, lease_token = NULL, worker_id = NULL
WHERE job.job_id = $1 AND job.stato IN ('fallito','annullato')
  AND NOT EXISTS (
      SELECT 1 FROM job p
      WHERE p.chiave_idempotenza IS NOT NULL AND p.chiave_idempotenza = job.chiave_idempotenza
        AND p.stato IN ('pronto','in_corso'))
RETURNING job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il
`

// Zero righe = non riaccodabile: o non è chiuso, o esiste già un job pendente con la stessa chiave di
// idempotenza. Il secondo caso violerebbe l'indice unico parziale: qui diventa un avviso, non un 500.
func (q *Queries) RiaccodaJob(ctx context.Context, jobID int64) (Job, error) {
	row := q.db.QueryRow(ctx, riaccodaJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const riaccodaScrittureNasEsaurite = `-- name: RiaccodaScrittureNasEsaurite :many
UPDATE job SET stato = 'pronto', tentativi = 0, non_prima_di = now(), chiuso_il = NULL,
    lease_fino_a = NULL, lease_token = NULL, worker_id = NULL,
    errore = concat_ws(' ', errore, '[riaccodato al ritorno del NAS]')
WHERE job.stato = 'fallito' AND job.tipo IN ('copia_nas','crea_cartella_thread')
  AND job.tentativi >= job.max_tentativi
  AND NOT EXISTS (
      SELECT 1 FROM job p
      WHERE p.chiave_idempotenza IS NOT NULL AND p.chiave_idempotenza = job.chiave_idempotenza
        AND p.stato IN ('pronto','in_corso'))
RETURNING job_id
`

// Al ritorno del NAS le copie che avevano finito i tentativi tornano in coda da sole (N3): senza,
// l'unico modo di recuperarle sarebbe che qualcuno se ne accorgesse e premesse «riprova», e una copia
// persa non si vede da nessuna parte finché non serve il file.
//
// Solo quelle ESAURITE: un fallimento dichiarato definitivo - il conflitto di hash sulla destinazione,
// cioè un file già lì con un contenuto diverso - chiude il job con tentativi < max_tentativi e non
// va rimesso in coda, perché il NAS che torna non lo risolve. La condizione NOT EXISTS è la stessa
// di RiaccodaJob: due job pendenti con la stessa chiave violerebbero l'indice unico parziale.
func (q *Queries) RiaccodaScrittureNasEsaurite(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, riaccodaScrittureNasEsaurite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var job_id int64
		if err := rows.Scan(&job_id); err != nil {
			return nil, err
		}
		items = append(items, job_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rilasciaLeaseScaduti = `-- name: RilasciaLeaseScaduti :execrows
UPDATE job SET
    stato = CASE WHEN tentativi >= max_tentativi THEN 'fallito'::stato_job ELSE 'pronto'::stato_job END,
    lease_fino_a = NULL, lease_token = NULL, worker_id = NULL,
    errore = concat_ws(' ', errore, CASE WHEN avviato_il IS NOT NULL AND now() > avviato_il + make_interval(secs => durata_max_s)
                                         THEN '[durata massima superata]' ELSE '[lease scaduto]' END),
    chiuso_il = CASE WHEN tentativi >= max_tentativi THEN now() END
WHERE stato = 'in_corso'
  AND (lease_fino_a < now() OR (avviato_il IS NOT NULL AND now() > avviato_il + make_interval(secs => durata_max_s)))
`

func (q *Queries) RilasciaLeaseScaduti(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, rilasciaLeaseScaduti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rinviaJob = `-- name: RinviaJob :one
UPDATE job SET stato = 'pronto', tentativi = GREATEST(0, tentativi - 1),
    lease_fino_a = NULL, lease_token = NULL, worker_id = NULL, avviato_il = NULL,
    non_prima_di = now() + make_interval(secs => $1::int), errore = $2
WHERE job_id = $3
  AND stato = 'in_corso' AND lease_token = $4 AND worker_id = $5
  AND lease_fino_a > now() AND now() <= avviato_il + make_interval(secs => durata_max_s)
RETURNING job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il
`

type RinviaJobParams struct {
	FraS       int32         `json:"fra_s"`
	Motivo     pgtype.Text   `json:"motivo"`
	JobID      int64         `json:"job_id"`
	LeaseToken uuid.NullUUID `json:"lease_token"`
	WorkerID   pgtype.Text   `json:"worker_id"`
}

// Rimette in coda un tentativo che non è nemmeno cominciato e RESTITUISCE il tentativo consumato dal
// claim. Serve quando il NAS non è raggiungibile: contare come fallimento un tentativo che non
// abbiamo nemmeno provato brucerebbe il budget dei 50 in poche ore di rete assente, cioè proprio nel
// caso per cui il budget esiste (voce 1.7). Vale il predicato di validità del tentativo: un tentativo
// scaduto non può rinviare il job che nel frattempo è passato a un altro.
func (q *Queries) RinviaJob(ctx context.Context, arg RinviaJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, rinviaJob,
		arg.FraS,
		arg.Motivo,
		arg.JobID,
		arg.LeaseToken,
		arg.WorkerID,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const scadutoPerDurataMassima = `-- name: ScadutoPerDurataMassima :execrows
UPDATE job SET stato = 'pronto', lease_fino_a = NULL, lease_token = NULL, worker_id = NULL,
    non_prima_di = now(), errore = 'durata massima superata'
WHERE job_id = $1 AND stato = 'in_corso' AND avviato_il IS NOT NULL
  AND now() > avviato_il + make_interval(secs => durata_max_s)
`

// Chiamata quando il predicato fallisce: se il motivo è la durata massima il job torna disponibile
// con il motivo scritto, invece di restare appeso fino alla scadenza del lease.
func (q *Queries) ScadutoPerDurataMassima(ctx context.Context, jobID int64) (int64, error) {
	result, err := q.db.Exec(ctx, scadutoPerDurataMassima, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ultimoJobPerChiavePrefisso = `-- name: UltimoJobPerChiavePrefisso :one
SELECT job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il FROM job WHERE chiave_idempotenza LIKE $1::text || '%' ORDER BY job_id DESC LIMIT 1
`

func (q *Queries) UltimoJobPerChiavePrefisso(ctx context.Context, prefisso string) (Job, error) {
	row := q.db.QueryRow(ctx, ultimoJobPerChiavePrefisso, prefisso)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}

const upsertWorkerPresenza = `-- name: UpsertWorkerPresenza :exec
INSERT INTO worker_presenza (worker_tipo, worker_id, ultimo_claim, ultimo_job_il)
VALUES ($1, $2, now(), CASE WHEN $3::boolean THEN now() END)
ON CONFLICT (worker_tipo) DO UPDATE SET worker_id = EXCLUDED.worker_id, ultimo_claim = now(),
    ultimo_job_il = COALESCE(EXCLUDED.ultimo_job_il, worker_presenza.ultimo_job_il)
`

type UpsertWorkerPresenzaParams struct {
	WorkerTipo WorkerTipo `json:"worker_tipo"`
	WorkerID   string     `json:"worker_id"`
	ConJob     bool       `json:"con_job"`
}

func (q *Queries) UpsertWorkerPresenza(ctx context.Context, arg UpsertWorkerPresenzaParams) error {
	_, err := q.db.Exec(ctx, upsertWorkerPresenza, arg.WorkerTipo, arg.WorkerID, arg.ConJob)
	return err
}

const verificaTentativo = `-- name: VerificaTentativo :one
SELECT job_id, tipo, worker_tipo, payload, chiave_idempotenza, stato, priorita, tentativi, max_tentativi, non_prima_di, lease_fino_a, worker_id, risultato, errore, creato_il, aggiornato_il, chiuso_il, casella_id, postazione_id, richiesto_da, lease_s, durata_max_s, lease_token, avviato_il, scade_il FROM job
WHERE job_id = $1
  AND stato = 'in_corso' AND lease_token = $2 AND worker_id = $3
  AND lease_fino_a > now() AND now() <= avviato_il + make_interval(secs => durata_max_s)
`

type VerificaTentativoParams struct {
	JobID      int64         `json:"job_id"`
	LeaseToken uuid.NullUUID `json:"lease_token"`
	WorkerID   pgtype.Text   `json:"worker_id"`
}

// Il predicato di validità SENZA blocco della riga: serve all'upload di un file (voce 2.3), che dura
// quanto un trasferimento e non può tenere una transazione aperta. Si verifica prima di cominciare a
// scrivere e di nuovo alla fine: un tentativo scaduto a metà trasferimento riceve 409 e il suo
// .parte.<token> viene rimosso. Non promuove nulla: la promozione a definitivo la fa solo il result,
// dentro la transazione, con BloccaTentativo.
func (q *Queries) VerificaTentativo(ctx context.Context, arg VerificaTentativoParams) (Job, error) {
	row := q.db.QueryRow(ctx, verificaTentativo, arg.JobID, arg.LeaseToken, arg.WorkerID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.Tipo,
		&i.WorkerTipo,
		&i.Payload,
		&i.ChiaveIdempotenza,
		&i.Stato,
		&i.Priorita,
		&i.Tentativi,
		&i.MaxTentativi,
		&i.NonPrimaDi,
		&i.LeaseFinoA,
		&i.WorkerID,
		&i.Risultato,
		&i.Errore,
		&i.CreatoIl,
		&i.AggiornatoIl,
		&i.ChiusoIl,
		&i.CasellaID,
		&i.PostazioneID,
		&i.RichiestoDa,
		&i.LeaseS,
		&i.DurataMaxS,
		&i.LeaseToken,
		&i.AvviatoIl,
		&i.ScadeIl,
	)
	return i, err
}
