// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaggi.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const agganciaMessaggio = `-- name: AgganciaMessaggio :exec
UPDATE messaggio SET thread_id = $2, aggancio = $3, agganciato_da = $4, agganciato_il = now()
WHERE messaggio_id = $1
`

type AgganciaMessaggioParams struct {
	MessaggioID  uuid.UUID     `json:"messaggio_id"`
	ThreadID     uuid.NullUUID `json:"thread_id"`
	Aggancio     Aggancio      `json:"aggancio"`
	AgganciatoDa uuid.NullUUID `json:"agganciato_da"`
}

func (q *Queries) AgganciaMessaggio(ctx context.Context, arg AgganciaMessaggioParams) error {
	_, err := q.db.Exec(ctx, agganciaMessaggio,
		arg.MessaggioID,
		arg.ThreadID,
		arg.Aggancio,
		arg.AgganciatoDa,
	)
	return err
}

const agganciaOrfaniConversazione = `-- name: AgganciaOrfaniConversazione :many
UPDATE messaggio SET thread_id = $2, aggancio = 'auto_conversazione', agganciato_il = now()
WHERE conversazione_id = $1 AND thread_id IS NULL AND messaggio_id <> $3
RETURNING messaggio_id
`

type AgganciaOrfaniConversazioneParams struct {
	ConversazioneID uuid.UUID     `json:"conversazione_id"`
	ThreadID        uuid.NullUUID `json:"thread_id"`
	MessaggioID     uuid.UUID     `json:"messaggio_id"`
}

// quando l'operatore crea/aggancia una RFQ, gli altri messaggi orfani della stessa conversazione la seguono
func (q *Queries) AgganciaOrfaniConversazione(ctx context.Context, arg AgganciaOrfaniConversazioneParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, agganciaOrfaniConversazione, arg.ConversazioneID, arg.ThreadID, arg.MessaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var messaggio_id uuid.UUID
		if err := rows.Scan(&messaggio_id); err != nil {
			return nil, err
		}
		items = append(items, messaggio_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bloccaMessaggio = `-- name: BloccaMessaggio :one
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da FROM messaggio WHERE messaggio_id = $1 FOR UPDATE
`

// Come GetMessaggio, ma la riga resta bloccata fino alla fine della transazione (voce 1.9, T13).
// Serve a ogni percorso che DECIDE qualcosa sul messaggio: nuova RFQ, aggancio, sgancio, ignora.
// Senza, due operatori che premono "Nuova RFQ" sullo stesso messaggio nello stesso momento leggono
// entrambi thread_id NULL, creano due RFQ e solo una resta agganciata: l'altra rimane in giro vuota,
// con la sua cartella sul NAS, e nessuno dei due operatori vede un errore. Con il blocco il secondo
// aspetta, rilegge il messaggio già agganciato e riceve un esito esplicito.
func (q *Queries) BloccaMessaggio(ctx context.Context, messaggioID uuid.UUID) (Messaggio, error) {
	row := q.db.QueryRow(ctx, bloccaMessaggio, messaggioID)
	var i Messaggio
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
	)
	return i, err
}

const collegaConversazione = `-- name: CollegaConversazione :exec
UPDATE conversazione SET thread_id = $2, collegata_da = $3 WHERE conversazione_id = $1
`

type CollegaConversazioneParams struct {
	ConversazioneID uuid.UUID     `json:"conversazione_id"`
	ThreadID        uuid.NullUUID `json:"thread_id"`
	CollegataDa     Aggancio      `json:"collegata_da"`
}

func (q *Queries) CollegaConversazione(ctx context.Context, arg CollegaConversazioneParams) error {
	_, err := q.db.Exec(ctx, collegaConversazione, arg.ConversazioneID, arg.ThreadID, arg.CollegataDa)
	return err
}

const contaInbox = `-- name: ContaInbox :one
SELECT count(*) FILTER (WHERE thread_id IS NULL AND NOT ignorato) AS orfani,
       count(*) FILTER (WHERE thread_id IS NOT NULL)             AS agganciati,
       count(*) FILTER (WHERE thread_id IS NULL AND ignorato)     AS ignorati,
       count(*)                                                  AS tutti
FROM v_inbox
`

type ContaInboxRow struct {
	Orfani     int64 `json:"orfani"`
	Agganciati int64 `json:"agganciati"`
	Ignorati   int64 `json:"ignorati"`
	Tutti      int64 `json:"tutti"`
}

func (q *Queries) ContaInbox(ctx context.Context) (ContaInboxRow, error) {
	row := q.db.QueryRow(ctx, contaInbox)
	var i ContaInboxRow
	err := row.Scan(
		&i.Orfani,
		&i.Agganciati,
		&i.Ignorati,
		&i.Tutti,
	)
	return i, err
}

const getConversazione = `-- name: GetConversazione :one
SELECT conversazione_id, canale, chiave_esterna, thread_id, collegata_da, primo_messaggio_il FROM conversazione WHERE conversazione_id = $1
`

func (q *Queries) GetConversazione(ctx context.Context, conversazioneID uuid.UUID) (Conversazione, error) {
	row := q.db.QueryRow(ctx, getConversazione, conversazioneID)
	var i Conversazione
	err := row.Scan(
		&i.ConversazioneID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ThreadID,
		&i.CollegataDa,
		&i.PrimoMessaggioIl,
	)
	return i, err
}

const getInboxRiga = `-- name: GetInboxRiga :one
SELECT messaggio_id, canale, direzione, data_evento, thread_id, aggancio, conversazione_id, mittente_nome, mittente_indirizzo, oggetto, n_allegati, buyer_id, dominio, cliente_id, cliente, buyer_cognome, n_rif_portale, n_cad, triage_esito, triage_confidenza, triage_motivi, thread_proposto, ignorato, non_letto, cartella_outlook, entry_id FROM v_inbox WHERE messaggio_id = $1
`

func (q *Queries) GetInboxRiga(ctx context.Context, messaggioID uuid.UUID) (VInbox, error) {
	row := q.db.QueryRow(ctx, getInboxRiga, messaggioID)
	var i VInbox
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.Direzione,
		&i.DataEvento,
		&i.ThreadID,
		&i.Aggancio,
		&i.ConversazioneID,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.Oggetto,
		&i.NAllegati,
		&i.BuyerID,
		&i.Dominio,
		&i.ClienteID,
		&i.Cliente,
		&i.BuyerCognome,
		&i.NRifPortale,
		&i.NCad,
		&i.TriageEsito,
		&i.TriageConfidenza,
		&i.TriageMotivi,
		&i.ThreadProposto,
		&i.Ignorato,
		&i.NonLetto,
		&i.CartellaOutlook,
		&i.EntryID,
	)
	return i, err
}

const getMessaggio = `-- name: GetMessaggio :one
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da FROM messaggio WHERE messaggio_id = $1
`

func (q *Queries) GetMessaggio(ctx context.Context, messaggioID uuid.UUID) (Messaggio, error) {
	row := q.db.QueryRow(ctx, getMessaggio, messaggioID)
	var i Messaggio
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
	)
	return i, err
}

const getMessaggioOutlook = `-- name: GetMessaggioOutlook :one
SELECT messaggio_id, entry_id, store_id, conversation_id, conversation_index, in_reply_to, riferimenti, cartella, categorie, non_letto, flag_stato, aggiornato_il FROM messaggio_outlook WHERE messaggio_id = $1
`

func (q *Queries) GetMessaggioOutlook(ctx context.Context, messaggioID uuid.UUID) (MessaggioOutlook, error) {
	row := q.db.QueryRow(ctx, getMessaggioOutlook, messaggioID)
	var i MessaggioOutlook
	err := row.Scan(
		&i.MessaggioID,
		&i.EntryID,
		&i.StoreID,
		&i.ConversationID,
		&i.ConversationIndex,
		&i.InReplyTo,
		&i.Riferimenti,
		&i.Cartella,
		&i.Categorie,
		&i.NonLetto,
		&i.FlagStato,
		&i.AggiornatoIl,
	)
	return i, err
}

const getMessaggioPerChiave = `-- name: GetMessaggioPerChiave :one
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da FROM messaggio WHERE canale = $1 AND chiave_esterna = $2
`

type GetMessaggioPerChiaveParams struct {
	Canale        Canale `json:"canale"`
	ChiaveEsterna string `json:"chiave_esterna"`
}

func (q *Queries) GetMessaggioPerChiave(ctx context.Context, arg GetMessaggioPerChiaveParams) (Messaggio, error) {
	row := q.db.QueryRow(ctx, getMessaggioPerChiave, arg.Canale, arg.ChiaveEsterna)
	var i Messaggio
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
	)
	return i, err
}

const getSyncCursore = `-- name: GetSyncCursore :one
SELECT cartella, ultimo_received, storico_fino_a, ultimo_sync, n_messaggi, errore FROM sync_cursore WHERE cartella = $1
`

func (q *Queries) GetSyncCursore(ctx context.Context, cartella string) (SyncCursore, error) {
	row := q.db.QueryRow(ctx, getSyncCursore, cartella)
	var i SyncCursore
	err := row.Scan(
		&i.Cartella,
		&i.UltimoReceived,
		&i.StoricoFinoA,
		&i.UltimoSync,
		&i.NMessaggi,
		&i.Errore,
	)
	return i, err
}

const listInbox = `-- name: ListInbox :many
SELECT messaggio_id, canale, direzione, data_evento, thread_id, aggancio, conversazione_id, mittente_nome, mittente_indirizzo, oggetto, n_allegati, buyer_id, dominio, cliente_id, cliente, buyer_cognome, n_rif_portale, n_cad, triage_esito, triage_confidenza, triage_motivi, thread_proposto, ignorato, non_letto, cartella_outlook, entry_id FROM v_inbox
WHERE ($1::text = 'tutti'
    OR ($1::text = 'orfani'     AND thread_id IS NULL AND NOT ignorato)
    OR ($1::text = 'agganciati' AND thread_id IS NOT NULL)
    OR ($1::text = 'ignorati'   AND thread_id IS NULL AND ignorato))
ORDER BY data_evento DESC
LIMIT $3 OFFSET $2
`

type ListInboxParams struct {
	Filtro string `json:"filtro"`
	Salta  int32  `json:"salta"`
	Limite int32  `json:"limite"`
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]VInbox, error) {
	rows, err := q.db.Query(ctx, listInbox, arg.Filtro, arg.Salta, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VInbox{}
	for rows.Next() {
		var i VInbox
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.Direzione,
			&i.DataEvento,
			&i.ThreadID,
			&i.Aggancio,
			&i.ConversazioneID,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.Oggetto,
			&i.NAllegati,
			&i.BuyerID,
			&i.Dominio,
			&i.ClienteID,
			&i.Cliente,
			&i.BuyerCognome,
			&i.NRifPortale,
			&i.NCad,
			&i.TriageEsito,
			&i.TriageConfidenza,
			&i.TriageMotivi,
			&i.ThreadProposto,
			&i.Ignorato,
			&i.NonLetto,
			&i.CartellaOutlook,
			&i.EntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessaggiConversazione = `-- name: ListMessaggiConversazione :many
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da FROM messaggio WHERE conversazione_id = $1 ORDER BY data_evento
`

func (q *Queries) ListMessaggiConversazione(ctx context.Context, conversazioneID uuid.UUID) ([]Messaggio, error) {
	rows, err := q.db.Query(ctx, listMessaggiConversazione, conversazioneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messaggio{}
	for rows.Next() {
		var i Messaggio
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.ChiaveEsterna,
			&i.ConversazioneID,
			&i.ParentMessaggioID,
			&i.ThreadID,
			&i.Aggancio,
			&i.AgganciatoDa,
			&i.AgganciatoIl,
			&i.Direzione,
			&i.DataEvento,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.BuyerID,
			&i.Destinatari,
			&i.Oggetto,
			&i.CorpoTesto,
			&i.CorpoHtml,
			&i.Lingua,
			&i.Importanza,
			&i.NotaOperatore,
			&i.NAllegati,
			&i.RegistratoIl,
			&i.RegistratoDa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessaggiThread = `-- name: ListMessaggiThread :many
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da FROM messaggio WHERE thread_id = $1 ORDER BY data_evento
`

func (q *Queries) ListMessaggiThread(ctx context.Context, threadID uuid.NullUUID) ([]Messaggio, error) {
	rows, err := q.db.Query(ctx, listMessaggiThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messaggio{}
	for rows.Next() {
		var i Messaggio
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.ChiaveEsterna,
			&i.ConversazioneID,
			&i.ParentMessaggioID,
			&i.ThreadID,
			&i.Aggancio,
			&i.AgganciatoDa,
			&i.AgganciatoIl,
			&i.Direzione,
			&i.DataEvento,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.BuyerID,
			&i.Destinatari,
			&i.Oggetto,
			&i.CorpoTesto,
			&i.CorpoHtml,
			&i.Lingua,
			&i.Importanza,
			&i.NotaOperatore,
			&i.NAllegati,
			&i.RegistratoIl,
			&i.RegistratoDa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncCursori = `-- name: ListSyncCursori :many
SELECT cartella, ultimo_received, storico_fino_a, ultimo_sync, n_messaggi, errore FROM sync_cursore ORDER BY cartella
`

func (q *Queries) ListSyncCursori(ctx context.Context) ([]SyncCursore, error) {
	rows, err := q.db.Query(ctx, listSyncCursori)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncCursore{}
	for rows.Next() {
		var i SyncCursore
		if err := rows.Scan(
			&i.Cartella,
			&i.UltimoReceived,
			&i.StoricoFinoA,
			&i.UltimoSync,
			&i.NMessaggi,
			&i.Errore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBuyerMessaggiPerIndirizzo = `-- name: SetBuyerMessaggiPerIndirizzo :execrows
UPDATE messaggio SET buyer_id = $2 WHERE lower(mittente_indirizzo) = lower($1) AND buyer_id IS NULL
`

type SetBuyerMessaggiPerIndirizzoParams struct {
	Lower   string        `json:"lower"`
	BuyerID uuid.NullUUID `json:"buyer_id"`
}

func (q *Queries) SetBuyerMessaggiPerIndirizzo(ctx context.Context, arg SetBuyerMessaggiPerIndirizzoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBuyerMessaggiPerIndirizzo, arg.Lower, arg.BuyerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBuyerMessaggio = `-- name: SetBuyerMessaggio :exec
UPDATE messaggio SET buyer_id = $2 WHERE messaggio_id = $1
`

type SetBuyerMessaggioParams struct {
	MessaggioID uuid.UUID     `json:"messaggio_id"`
	BuyerID     uuid.NullUUID `json:"buyer_id"`
}

func (q *Queries) SetBuyerMessaggio(ctx context.Context, arg SetBuyerMessaggioParams) error {
	_, err := q.db.Exec(ctx, setBuyerMessaggio, arg.MessaggioID, arg.BuyerID)
	return err
}

const setEntryIDMessaggio = `-- name: SetEntryIDMessaggio :exec
UPDATE messaggio_outlook SET entry_id = $2, store_id = $3, cartella = COALESCE($4, cartella), aggiornato_il = now()
WHERE messaggio_id = $1
`

type SetEntryIDMessaggioParams struct {
	MessaggioID uuid.UUID   `json:"messaggio_id"`
	EntryID     string      `json:"entry_id"`
	StoreID     string      `json:"store_id"`
	Cartella    pgtype.Text `json:"cartella"`
}

func (q *Queries) SetEntryIDMessaggio(ctx context.Context, arg SetEntryIDMessaggioParams) error {
	_, err := q.db.Exec(ctx, setEntryIDMessaggio,
		arg.MessaggioID,
		arg.EntryID,
		arg.StoreID,
		arg.Cartella,
	)
	return err
}

const setStoricoFinoA = `-- name: SetStoricoFinoA :exec
UPDATE sync_cursore SET storico_fino_a = LEAST(COALESCE(storico_fino_a, $2), $2) WHERE cartella = $1
`

type SetStoricoFinoAParams struct {
	Cartella     string     `json:"cartella"`
	StoricoFinoA *time.Time `json:"storico_fino_a"`
}

func (q *Queries) SetStoricoFinoA(ctx context.Context, arg SetStoricoFinoAParams) error {
	_, err := q.db.Exec(ctx, setStoricoFinoA, arg.Cartella, arg.StoricoFinoA)
	return err
}

const sgangiaMessaggio = `-- name: SgangiaMessaggio :exec
UPDATE messaggio SET thread_id = NULL, aggancio = 'nessuno', agganciato_da = $2, agganciato_il = now()
WHERE messaggio_id = $1
`

type SgangiaMessaggioParams struct {
	MessaggioID  uuid.UUID     `json:"messaggio_id"`
	AgganciatoDa uuid.NullUUID `json:"agganciato_da"`
}

func (q *Queries) SgangiaMessaggio(ctx context.Context, arg SgangiaMessaggioParams) error {
	_, err := q.db.Exec(ctx, sgangiaMessaggio, arg.MessaggioID, arg.AgganciatoDa)
	return err
}

const threadDellaConversazione = `-- name: ThreadDellaConversazione :one
SELECT thread_id FROM messaggio
WHERE conversazione_id = $1 AND thread_id IS NOT NULL
ORDER BY data_evento DESC LIMIT 1
`

func (q *Queries) ThreadDellaConversazione(ctx context.Context, conversazioneID uuid.UUID) (uuid.NullUUID, error) {
	row := q.db.QueryRow(ctx, threadDellaConversazione, conversazioneID)
	var thread_id uuid.NullUUID
	err := row.Scan(&thread_id)
	return thread_id, err
}

const upsertConversazione = `-- name: UpsertConversazione :one
INSERT INTO conversazione (canale, chiave_esterna, primo_messaggio_il)
VALUES ($1, $2, $3)
ON CONFLICT (canale, chiave_esterna) DO UPDATE
    SET primo_messaggio_il = LEAST(conversazione.primo_messaggio_il, EXCLUDED.primo_messaggio_il)
RETURNING conversazione_id, canale, chiave_esterna, thread_id, collegata_da, primo_messaggio_il
`

type UpsertConversazioneParams struct {
	Canale           Canale    `json:"canale"`
	ChiaveEsterna    string    `json:"chiave_esterna"`
	PrimoMessaggioIl time.Time `json:"primo_messaggio_il"`
}

func (q *Queries) UpsertConversazione(ctx context.Context, arg UpsertConversazioneParams) (Conversazione, error) {
	row := q.db.QueryRow(ctx, upsertConversazione, arg.Canale, arg.ChiaveEsterna, arg.PrimoMessaggioIl)
	var i Conversazione
	err := row.Scan(
		&i.ConversazioneID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ThreadID,
		&i.CollegataDa,
		&i.PrimoMessaggioIl,
	)
	return i, err
}

const upsertMessaggio = `-- name: UpsertMessaggio :one
INSERT INTO messaggio (canale, chiave_esterna, conversazione_id, parent_messaggio_id, direzione, data_evento,
                       mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html,
                       lingua, importanza, nota_operatore, registrato_da)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (canale, chiave_esterna) DO UPDATE SET
    conversazione_id = EXCLUDED.conversazione_id,
    mittente_nome    = COALESCE(EXCLUDED.mittente_nome, messaggio.mittente_nome),
    destinatari      = EXCLUDED.destinatari,
    corpo_testo      = COALESCE(EXCLUDED.corpo_testo, messaggio.corpo_testo),
    corpo_html       = COALESCE(EXCLUDED.corpo_html, messaggio.corpo_html),
    importanza       = COALESCE(EXCLUDED.importanza, messaggio.importanza),
    buyer_id         = COALESCE(messaggio.buyer_id, EXCLUDED.buyer_id)
RETURNING messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, (xmax = 0) AS inserito
`

type UpsertMessaggioParams struct {
	Canale            Canale          `json:"canale"`
	ChiaveEsterna     string          `json:"chiave_esterna"`
	ConversazioneID   uuid.UUID       `json:"conversazione_id"`
	ParentMessaggioID uuid.NullUUID   `json:"parent_messaggio_id"`
	Direzione         Direzione       `json:"direzione"`
	DataEvento        time.Time       `json:"data_evento"`
	MittenteNome      pgtype.Text     `json:"mittente_nome"`
	MittenteIndirizzo pgtype.Text     `json:"mittente_indirizzo"`
	BuyerID           uuid.NullUUID   `json:"buyer_id"`
	Destinatari       json.RawMessage `json:"destinatari"`
	Oggetto           pgtype.Text     `json:"oggetto"`
	CorpoTesto        pgtype.Text     `json:"corpo_testo"`
	CorpoHtml         pgtype.Text     `json:"corpo_html"`
	Lingua            pgtype.Text     `json:"lingua"`
	Importanza        pgtype.Int2     `json:"importanza"`
	NotaOperatore     pgtype.Text     `json:"nota_operatore"`
	RegistratoDa      uuid.NullUUID   `json:"registrato_da"`
}

type UpsertMessaggioRow struct {
	MessaggioID       uuid.UUID       `json:"messaggio_id"`
	Canale            Canale          `json:"canale"`
	ChiaveEsterna     string          `json:"chiave_esterna"`
	ConversazioneID   uuid.UUID       `json:"conversazione_id"`
	ParentMessaggioID uuid.NullUUID   `json:"parent_messaggio_id"`
	ThreadID          uuid.NullUUID   `json:"thread_id"`
	Aggancio          Aggancio        `json:"aggancio"`
	AgganciatoDa      uuid.NullUUID   `json:"agganciato_da"`
	AgganciatoIl      *time.Time      `json:"agganciato_il"`
	Direzione         Direzione       `json:"direzione"`
	DataEvento        time.Time       `json:"data_evento"`
	MittenteNome      pgtype.Text     `json:"mittente_nome"`
	MittenteIndirizzo pgtype.Text     `json:"mittente_indirizzo"`
	BuyerID           uuid.NullUUID   `json:"buyer_id"`
	Destinatari       json.RawMessage `json:"destinatari"`
	Oggetto           pgtype.Text     `json:"oggetto"`
	CorpoTesto        pgtype.Text     `json:"corpo_testo"`
	CorpoHtml         pgtype.Text     `json:"corpo_html"`
	Lingua            pgtype.Text     `json:"lingua"`
	Importanza        pgtype.Int2     `json:"importanza"`
	NotaOperatore     pgtype.Text     `json:"nota_operatore"`
	NAllegati         int16           `json:"n_allegati"`
	RegistratoIl      time.Time       `json:"registrato_il"`
	RegistratoDa      uuid.NullUUID   `json:"registrato_da"`
	Inserito          bool            `json:"inserito"`
}

func (q *Queries) UpsertMessaggio(ctx context.Context, arg UpsertMessaggioParams) (UpsertMessaggioRow, error) {
	row := q.db.QueryRow(ctx, upsertMessaggio,
		arg.Canale,
		arg.ChiaveEsterna,
		arg.ConversazioneID,
		arg.ParentMessaggioID,
		arg.Direzione,
		arg.DataEvento,
		arg.MittenteNome,
		arg.MittenteIndirizzo,
		arg.BuyerID,
		arg.Destinatari,
		arg.Oggetto,
		arg.CorpoTesto,
		arg.CorpoHtml,
		arg.Lingua,
		arg.Importanza,
		arg.NotaOperatore,
		arg.RegistratoDa,
	)
	var i UpsertMessaggioRow
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
		&i.Inserito,
	)
	return i, err
}

const upsertMessaggioOutlook = `-- name: UpsertMessaggioOutlook :exec
INSERT INTO messaggio_outlook (messaggio_id, entry_id, store_id, conversation_id, conversation_index, in_reply_to,
                               riferimenti, cartella, categorie, non_letto, flag_stato)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (messaggio_id) DO UPDATE SET
    entry_id = EXCLUDED.entry_id, store_id = EXCLUDED.store_id, cartella = EXCLUDED.cartella,
    categorie = EXCLUDED.categorie, non_letto = EXCLUDED.non_letto, flag_stato = EXCLUDED.flag_stato,
    in_reply_to = COALESCE(EXCLUDED.in_reply_to, messaggio_outlook.in_reply_to),
    riferimenti = COALESCE(EXCLUDED.riferimenti, messaggio_outlook.riferimenti),
    aggiornato_il = now()
`

type UpsertMessaggioOutlookParams struct {
	MessaggioID       uuid.UUID   `json:"messaggio_id"`
	EntryID           string      `json:"entry_id"`
	StoreID           string      `json:"store_id"`
	ConversationID    pgtype.Text `json:"conversation_id"`
	ConversationIndex pgtype.Text `json:"conversation_index"`
	InReplyTo         pgtype.Text `json:"in_reply_to"`
	Riferimenti       []string    `json:"riferimenti"`
	Cartella          pgtype.Text `json:"cartella"`
	Categorie         []string    `json:"categorie"`
	NonLetto          bool        `json:"non_letto"`
	FlagStato         pgtype.Int2 `json:"flag_stato"`
}

func (q *Queries) UpsertMessaggioOutlook(ctx context.Context, arg UpsertMessaggioOutlookParams) error {
	_, err := q.db.Exec(ctx, upsertMessaggioOutlook,
		arg.MessaggioID,
		arg.EntryID,
		arg.StoreID,
		arg.ConversationID,
		arg.ConversationIndex,
		arg.InReplyTo,
		arg.Riferimenti,
		arg.Cartella,
		arg.Categorie,
		arg.NonLetto,
		arg.FlagStato,
	)
	return err
}

const upsertSyncCursore = `-- name: UpsertSyncCursore :exec
INSERT INTO sync_cursore (cartella, ultimo_received, ultimo_sync, n_messaggi, errore)
VALUES ($1, $2, now(), $3, $4)
ON CONFLICT (cartella) DO UPDATE SET
    ultimo_received = GREATEST(COALESCE(sync_cursore.ultimo_received, EXCLUDED.ultimo_received), EXCLUDED.ultimo_received),
    ultimo_sync = now(), n_messaggi = sync_cursore.n_messaggi + EXCLUDED.n_messaggi, errore = EXCLUDED.errore
`

type UpsertSyncCursoreParams struct {
	Cartella       string      `json:"cartella"`
	UltimoReceived *time.Time  `json:"ultimo_received"`
	NMessaggi      int32       `json:"n_messaggi"`
	Errore         pgtype.Text `json:"errore"`
}

func (q *Queries) UpsertSyncCursore(ctx context.Context, arg UpsertSyncCursoreParams) error {
	_, err := q.db.Exec(ctx, upsertSyncCursore,
		arg.Cartella,
		arg.UltimoReceived,
		arg.NMessaggi,
		arg.Errore,
	)
	return err
}
