// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaggi.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const agganciaMessaggio = `-- name: AgganciaMessaggio :exec
UPDATE messaggio SET thread_id = $2, aggancio = $3, agganciato_da = $4, agganciato_il = now()
WHERE messaggio_id = $1
`

type AgganciaMessaggioParams struct {
	MessaggioID  uuid.UUID     `json:"messaggio_id"`
	ThreadID     uuid.NullUUID `json:"thread_id"`
	Aggancio     Aggancio      `json:"aggancio"`
	AgganciatoDa uuid.NullUUID `json:"agganciato_da"`
}

func (q *Queries) AgganciaMessaggio(ctx context.Context, arg AgganciaMessaggioParams) error {
	_, err := q.db.Exec(ctx, agganciaMessaggio,
		arg.MessaggioID,
		arg.ThreadID,
		arg.Aggancio,
		arg.AgganciatoDa,
	)
	return err
}

const agganciaOrfaniConversazione = `-- name: AgganciaOrfaniConversazione :many
UPDATE messaggio SET thread_id = $2, aggancio = 'auto_conversazione', agganciato_il = now()
WHERE conversazione_id = $1 AND thread_id IS NULL AND messaggio_id <> $3
RETURNING messaggio_id
`

type AgganciaOrfaniConversazioneParams struct {
	ConversazioneID uuid.UUID     `json:"conversazione_id"`
	ThreadID        uuid.NullUUID `json:"thread_id"`
	MessaggioID     uuid.UUID     `json:"messaggio_id"`
}

// quando l'operatore crea/aggancia una RFQ, gli altri messaggi orfani della stessa conversazione la seguono
func (q *Queries) AgganciaOrfaniConversazione(ctx context.Context, arg AgganciaOrfaniConversazioneParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, agganciaOrfaniConversazione, arg.ConversazioneID, arg.ThreadID, arg.MessaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var messaggio_id uuid.UUID
		if err := rows.Scan(&messaggio_id); err != nil {
			return nil, err
		}
		items = append(items, messaggio_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bloccaMessaggio = `-- name: BloccaMessaggio :one
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il FROM messaggio WHERE messaggio_id = $1 FOR UPDATE
`

// Come GetMessaggio, ma la riga resta bloccata fino alla fine della transazione (voce 1.9, T13).
// Serve a ogni percorso che DECIDE qualcosa sul messaggio: nuova RFQ, aggancio, sgancio, ignora.
// Senza, due operatori che premono "Nuova RFQ" sullo stesso messaggio nello stesso momento leggono
// entrambi thread_id NULL, creano due RFQ e solo una resta agganciata: l'altra rimane in giro vuota,
// con la sua cartella sul NAS, e nessuno dei due operatori vede un errore. Con il blocco il secondo
// aspetta, rilegge il messaggio già agganciato e riceve un esito esplicito.
func (q *Queries) BloccaMessaggio(ctx context.Context, messaggioID uuid.UUID) (Messaggio, error) {
	row := q.db.QueryRow(ctx, bloccaMessaggio, messaggioID)
	var i Messaggio
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
		&i.Interno,
		&i.ControparteTipo,
		&i.ControparteClienteID,
		&i.ControparteFornitoreID,
		&i.ControparteVia,
		&i.ControparteIl,
	)
	return i, err
}

const caselleServiteDaPostazione = `-- name: CaselleServiteDaPostazione :many
SELECT DISTINCT c.casella_id, c.canale, c.indirizzo, c.nome, c.condivisa, c.utente_id, c.attiva, c.creato_il, c.aggiornato_il
FROM worker_credenziale w JOIN casella c ON c.casella_id = ANY (w.caselle)
WHERE w.attivo AND w.worker_tipo = 'outlook' AND w.postazione_id = $1
ORDER BY c.nome
`

// Le caselle su cui i worker Outlook di una postazione sono autorizzati: serve a dire PERCHÉ un'azione
// non parte («il worker di PC-FRANCESCO non serve Commerciale»), non solo che non parte.
func (q *Queries) CaselleServiteDaPostazione(ctx context.Context, postazioneID uuid.NullUUID) ([]Casella, error) {
	rows, err := q.db.Query(ctx, caselleServiteDaPostazione, postazioneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Casella{}
	for rows.Next() {
		var i Casella
		if err := rows.Scan(
			&i.CasellaID,
			&i.Canale,
			&i.Indirizzo,
			&i.Nome,
			&i.Condivisa,
			&i.UtenteID,
			&i.Attiva,
			&i.CreatoIl,
			&i.AggiornatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collegaConversazione = `-- name: CollegaConversazione :exec
UPDATE conversazione SET thread_id = $2, collegata_da = $3 WHERE conversazione_id = $1
`

type CollegaConversazioneParams struct {
	ConversazioneID uuid.UUID     `json:"conversazione_id"`
	ThreadID        uuid.NullUUID `json:"thread_id"`
	CollegataDa     Aggancio      `json:"collegata_da"`
}

func (q *Queries) CollegaConversazione(ctx context.Context, arg CollegaConversazioneParams) error {
	_, err := q.db.Exec(ctx, collegaConversazione, arg.ConversazioneID, arg.ThreadID, arg.CollegataDa)
	return err
}

const contaInbox = `-- name: ContaInbox :one
SELECT count(*) FILTER (WHERE thread_id IS NULL AND NOT ignorato) AS orfani,
       count(*) FILTER (WHERE thread_id IS NOT NULL)             AS agganciati,
       count(*) FILTER (WHERE thread_id IS NULL AND ignorato)     AS ignorati,
       count(*)                                                  AS tutti
FROM v_inbox
WHERE $1::uuid IS NULL OR $1::uuid = ANY (caselle_id)
`

type ContaInboxRow struct {
	Orfani     int64 `json:"orfani"`
	Agganciati int64 `json:"agganciati"`
	Ignorati   int64 `json:"ignorati"`
	Tutti      int64 `json:"tutti"`
}

func (q *Queries) ContaInbox(ctx context.Context, casella uuid.NullUUID) (ContaInboxRow, error) {
	row := q.db.QueryRow(ctx, contaInbox, casella)
	var i ContaInboxRow
	err := row.Scan(
		&i.Orfani,
		&i.Agganciati,
		&i.Ignorati,
		&i.Tutti,
	)
	return i, err
}

const copiaPerPostazione = `-- name: CopiaPerPostazione :one
SELECT mc.messaggio_id, mc.casella_id, mc.entry_id, mc.cartella, mc.ricevuto_il, mc.non_letto, mc.flag_stato, mc.categorie, mc.aggiornato_il, c.nome AS casella_nome, c.indirizzo AS casella_indirizzo, w.worker_nome
FROM messaggio_casella mc
JOIN casella c ON c.casella_id = mc.casella_id
JOIN worker_credenziale w ON w.attivo AND w.worker_tipo = 'outlook'
     AND w.postazione_id = $1 AND mc.casella_id = ANY (w.caselle)
WHERE mc.messaggio_id = $2 AND c.attiva
ORDER BY (c.utente_id IS NOT NULL AND c.utente_id = $3::uuid) DESC, mc.ricevuto_il, mc.casella_id
LIMIT 1
`

type CopiaPerPostazioneParams struct {
	PostazioneID uuid.NullUUID `json:"postazione_id"`
	MessaggioID  uuid.UUID     `json:"messaggio_id"`
	Richiedente  uuid.NullUUID `json:"richiedente"`
}

type CopiaPerPostazioneRow struct {
	MessaggioID      uuid.UUID   `json:"messaggio_id"`
	CasellaID        uuid.UUID   `json:"casella_id"`
	EntryID          string      `json:"entry_id"`
	Cartella         pgtype.Text `json:"cartella"`
	RicevutoIl       time.Time   `json:"ricevuto_il"`
	NonLetto         bool        `json:"non_letto"`
	FlagStato        pgtype.Int2 `json:"flag_stato"`
	Categorie        []string    `json:"categorie"`
	AggiornatoIl     time.Time   `json:"aggiornato_il"`
	CasellaNome      string      `json:"casella_nome"`
	CasellaIndirizzo string      `json:"casella_indirizzo"`
	WorkerNome       string      `json:"worker_nome"`
}

// ROUTING DEI JOB INTERATTIVI (voci 2.2 e 2.7, M3). La copia del messaggio che il worker Outlook di
// QUESTA postazione serve: presente in una casella attiva su cui la credenziale del worker della
// postazione è autorizzata. Se il messaggio è in più caselle servite, si preferisce la casella
// personale del richiedente, poi la copia più vecchia. Zero righe = nessun worker idoneo su quella
// postazione: il job NON si crea e l'operatore legge il motivo (M4, M10). Non si ripiega su un'altra
// postazione: una finestra aperta su un altro PC non è un'azione riuscita, è un'azione sbagliata.
func (q *Queries) CopiaPerPostazione(ctx context.Context, arg CopiaPerPostazioneParams) (CopiaPerPostazioneRow, error) {
	row := q.db.QueryRow(ctx, copiaPerPostazione, arg.PostazioneID, arg.MessaggioID, arg.Richiedente)
	var i CopiaPerPostazioneRow
	err := row.Scan(
		&i.MessaggioID,
		&i.CasellaID,
		&i.EntryID,
		&i.Cartella,
		&i.RicevutoIl,
		&i.NonLetto,
		&i.FlagStato,
		&i.Categorie,
		&i.AggiornatoIl,
		&i.CasellaNome,
		&i.CasellaIndirizzo,
		&i.WorkerNome,
	)
	return i, err
}

const getConversazione = `-- name: GetConversazione :one
SELECT conversazione_id, canale, chiave_esterna, thread_id, collegata_da, primo_messaggio_il FROM conversazione WHERE conversazione_id = $1
`

func (q *Queries) GetConversazione(ctx context.Context, conversazioneID uuid.UUID) (Conversazione, error) {
	row := q.db.QueryRow(ctx, getConversazione, conversazioneID)
	var i Conversazione
	err := row.Scan(
		&i.ConversazioneID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ThreadID,
		&i.CollegataDa,
		&i.PrimoMessaggioIl,
	)
	return i, err
}

const getInboxRiga = `-- name: GetInboxRiga :one
SELECT messaggio_id, canale, direzione, interno, data_evento, thread_id, aggancio, conversazione_id, mittente_nome, mittente_indirizzo, oggetto, n_allegati, buyer_id, dominio, cliente_id, cliente, buyer_cognome, n_rif_portale, n_cad, triage_esito, triage_confidenza, triage_motivi, thread_proposto, ignorato, caselle, caselle_id, n_caselle, non_letto, ricevuto_il, casella_id, cartella_outlook, entry_id, controparte_tipo, controparte FROM v_inbox WHERE messaggio_id = $1
`

func (q *Queries) GetInboxRiga(ctx context.Context, messaggioID uuid.UUID) (VInbox, error) {
	row := q.db.QueryRow(ctx, getInboxRiga, messaggioID)
	var i VInbox
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.Direzione,
		&i.Interno,
		&i.DataEvento,
		&i.ThreadID,
		&i.Aggancio,
		&i.ConversazioneID,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.Oggetto,
		&i.NAllegati,
		&i.BuyerID,
		&i.Dominio,
		&i.ClienteID,
		&i.Cliente,
		&i.BuyerCognome,
		&i.NRifPortale,
		&i.NCad,
		&i.TriageEsito,
		&i.TriageConfidenza,
		&i.TriageMotivi,
		&i.ThreadProposto,
		&i.Ignorato,
		&i.Caselle,
		&i.CaselleID,
		&i.NCaselle,
		&i.NonLetto,
		&i.RicevutoIl,
		&i.CasellaID,
		&i.CartellaOutlook,
		&i.EntryID,
		&i.ControparteTipo,
		&i.Controparte,
	)
	return i, err
}

const getMessaggio = `-- name: GetMessaggio :one
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il FROM messaggio WHERE messaggio_id = $1
`

func (q *Queries) GetMessaggio(ctx context.Context, messaggioID uuid.UUID) (Messaggio, error) {
	row := q.db.QueryRow(ctx, getMessaggio, messaggioID)
	var i Messaggio
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
		&i.Interno,
		&i.ControparteTipo,
		&i.ControparteClienteID,
		&i.ControparteFornitoreID,
		&i.ControparteVia,
		&i.ControparteIl,
	)
	return i, err
}

const getMessaggioOutlook = `-- name: GetMessaggioOutlook :one
SELECT messaggio_id, conversation_id, conversation_index, in_reply_to, riferimenti, aggiornato_il FROM messaggio_outlook WHERE messaggio_id = $1
`

func (q *Queries) GetMessaggioOutlook(ctx context.Context, messaggioID uuid.UUID) (MessaggioOutlook, error) {
	row := q.db.QueryRow(ctx, getMessaggioOutlook, messaggioID)
	var i MessaggioOutlook
	err := row.Scan(
		&i.MessaggioID,
		&i.ConversationID,
		&i.ConversationIndex,
		&i.InReplyTo,
		&i.Riferimenti,
		&i.AggiornatoIl,
	)
	return i, err
}

const getMessaggioPerChiave = `-- name: GetMessaggioPerChiave :one
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il FROM messaggio WHERE canale = $1 AND chiave_esterna = $2
`

type GetMessaggioPerChiaveParams struct {
	Canale        Canale `json:"canale"`
	ChiaveEsterna string `json:"chiave_esterna"`
}

func (q *Queries) GetMessaggioPerChiave(ctx context.Context, arg GetMessaggioPerChiaveParams) (Messaggio, error) {
	row := q.db.QueryRow(ctx, getMessaggioPerChiave, arg.Canale, arg.ChiaveEsterna)
	var i Messaggio
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
		&i.Interno,
		&i.ControparteTipo,
		&i.ControparteClienteID,
		&i.ControparteFornitoreID,
		&i.ControparteVia,
		&i.ControparteIl,
	)
	return i, err
}

const getPresenza = `-- name: GetPresenza :one
SELECT messaggio_id, casella_id, entry_id, cartella, ricevuto_il, non_letto, flag_stato, categorie, aggiornato_il FROM messaggio_casella WHERE messaggio_id = $1 AND casella_id = $2
`

type GetPresenzaParams struct {
	MessaggioID uuid.UUID `json:"messaggio_id"`
	CasellaID   uuid.UUID `json:"casella_id"`
}

func (q *Queries) GetPresenza(ctx context.Context, arg GetPresenzaParams) (MessaggioCasella, error) {
	row := q.db.QueryRow(ctx, getPresenza, arg.MessaggioID, arg.CasellaID)
	var i MessaggioCasella
	err := row.Scan(
		&i.MessaggioID,
		&i.CasellaID,
		&i.EntryID,
		&i.Cartella,
		&i.RicevutoIl,
		&i.NonLetto,
		&i.FlagStato,
		&i.Categorie,
		&i.AggiornatoIl,
	)
	return i, err
}

const getSyncCursore = `-- name: GetSyncCursore :one

SELECT cartella, ultimo_received, storico_fino_a, ultimo_sync, n_messaggi, errore, casella_id, coperto_fino_a FROM sync_cursore WHERE casella_id = $1 AND cartella = $2
`

type GetSyncCursoreParams struct {
	CasellaID uuid.UUID `json:"casella_id"`
	Cartella  string    `json:"cartella"`
}

// Il cursore ha per chiave (casella, cartella) dalla 0004. Con la sola cartella due caselle che hanno
// entrambe una «Posta in arrivo» si facevano avanzare il cursore a vicenda, e ogni avanzamento di
// troppo è una finestra di tempo che l'altra casella non legge mai: messaggi persi in silenzio.
func (q *Queries) GetSyncCursore(ctx context.Context, arg GetSyncCursoreParams) (SyncCursore, error) {
	row := q.db.QueryRow(ctx, getSyncCursore, arg.CasellaID, arg.Cartella)
	var i SyncCursore
	err := row.Scan(
		&i.Cartella,
		&i.UltimoReceived,
		&i.StoricoFinoA,
		&i.UltimoSync,
		&i.NMessaggi,
		&i.Errore,
		&i.CasellaID,
		&i.CopertoFinoA,
	)
	return i, err
}

const listInbox = `-- name: ListInbox :many
SELECT messaggio_id, canale, direzione, interno, data_evento, thread_id, aggancio, conversazione_id, mittente_nome, mittente_indirizzo, oggetto, n_allegati, buyer_id, dominio, cliente_id, cliente, buyer_cognome, n_rif_portale, n_cad, triage_esito, triage_confidenza, triage_motivi, thread_proposto, ignorato, caselle, caselle_id, n_caselle, non_letto, ricevuto_il, casella_id, cartella_outlook, entry_id, controparte_tipo, controparte FROM v_inbox
WHERE ($1::text = 'tutti'
    OR ($1::text = 'orfani'     AND thread_id IS NULL AND NOT ignorato)
    OR ($1::text = 'agganciati' AND thread_id IS NOT NULL)
    OR ($1::text = 'ignorati'   AND thread_id IS NULL AND ignorato))
  AND ($2::uuid IS NULL OR $2::uuid = ANY (caselle_id))
ORDER BY data_evento DESC
LIMIT $4 OFFSET $3
`

type ListInboxParams struct {
	Filtro  string        `json:"filtro"`
	Casella uuid.NullUUID `json:"casella"`
	Salta   int32         `json:"salta"`
	Limite  int32         `json:"limite"`
}

// `casella` vuoto = tutte le caselle. NON è un controllo di autorizzazione: è il filtro della
// schermata. Chi può vedere che cosa è la voce 2.2 (puoVedere) e resta restrittivo fino ad allora.
func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]VInbox, error) {
	rows, err := q.db.Query(ctx, listInbox,
		arg.Filtro,
		arg.Casella,
		arg.Salta,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VInbox{}
	for rows.Next() {
		var i VInbox
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.Direzione,
			&i.Interno,
			&i.DataEvento,
			&i.ThreadID,
			&i.Aggancio,
			&i.ConversazioneID,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.Oggetto,
			&i.NAllegati,
			&i.BuyerID,
			&i.Dominio,
			&i.ClienteID,
			&i.Cliente,
			&i.BuyerCognome,
			&i.NRifPortale,
			&i.NCad,
			&i.TriageEsito,
			&i.TriageConfidenza,
			&i.TriageMotivi,
			&i.ThreadProposto,
			&i.Ignorato,
			&i.Caselle,
			&i.CaselleID,
			&i.NCaselle,
			&i.NonLetto,
			&i.RicevutoIl,
			&i.CasellaID,
			&i.CartellaOutlook,
			&i.EntryID,
			&i.ControparteTipo,
			&i.Controparte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessaggiConversazione = `-- name: ListMessaggiConversazione :many
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il FROM messaggio WHERE conversazione_id = $1 ORDER BY data_evento
`

func (q *Queries) ListMessaggiConversazione(ctx context.Context, conversazioneID uuid.UUID) ([]Messaggio, error) {
	rows, err := q.db.Query(ctx, listMessaggiConversazione, conversazioneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messaggio{}
	for rows.Next() {
		var i Messaggio
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.ChiaveEsterna,
			&i.ConversazioneID,
			&i.ParentMessaggioID,
			&i.ThreadID,
			&i.Aggancio,
			&i.AgganciatoDa,
			&i.AgganciatoIl,
			&i.Direzione,
			&i.DataEvento,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.BuyerID,
			&i.Destinatari,
			&i.Oggetto,
			&i.CorpoTesto,
			&i.CorpoHtml,
			&i.Lingua,
			&i.Importanza,
			&i.NotaOperatore,
			&i.NAllegati,
			&i.RegistratoIl,
			&i.RegistratoDa,
			&i.Interno,
			&i.ControparteTipo,
			&i.ControparteClienteID,
			&i.ControparteFornitoreID,
			&i.ControparteVia,
			&i.ControparteIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessaggiThread = `-- name: ListMessaggiThread :many
SELECT messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il FROM messaggio WHERE thread_id = $1 ORDER BY data_evento
`

func (q *Queries) ListMessaggiThread(ctx context.Context, threadID uuid.NullUUID) ([]Messaggio, error) {
	rows, err := q.db.Query(ctx, listMessaggiThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messaggio{}
	for rows.Next() {
		var i Messaggio
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Canale,
			&i.ChiaveEsterna,
			&i.ConversazioneID,
			&i.ParentMessaggioID,
			&i.ThreadID,
			&i.Aggancio,
			&i.AgganciatoDa,
			&i.AgganciatoIl,
			&i.Direzione,
			&i.DataEvento,
			&i.MittenteNome,
			&i.MittenteIndirizzo,
			&i.BuyerID,
			&i.Destinatari,
			&i.Oggetto,
			&i.CorpoTesto,
			&i.CorpoHtml,
			&i.Lingua,
			&i.Importanza,
			&i.NotaOperatore,
			&i.NAllegati,
			&i.RegistratoIl,
			&i.RegistratoDa,
			&i.Interno,
			&i.ControparteTipo,
			&i.ControparteClienteID,
			&i.ControparteFornitoreID,
			&i.ControparteVia,
			&i.ControparteIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresenze = `-- name: ListPresenze :many
SELECT mc.messaggio_id, mc.casella_id, mc.entry_id, mc.cartella, mc.ricevuto_il, mc.non_letto, mc.flag_stato, mc.categorie, mc.aggiornato_il, c.nome AS casella_nome, c.indirizzo AS casella_indirizzo, c.condivisa
FROM messaggio_casella mc JOIN casella c ON c.casella_id = mc.casella_id
WHERE mc.messaggio_id = $1 ORDER BY c.nome
`

type ListPresenzeRow struct {
	MessaggioID      uuid.UUID   `json:"messaggio_id"`
	CasellaID        uuid.UUID   `json:"casella_id"`
	EntryID          string      `json:"entry_id"`
	Cartella         pgtype.Text `json:"cartella"`
	RicevutoIl       time.Time   `json:"ricevuto_il"`
	NonLetto         bool        `json:"non_letto"`
	FlagStato        pgtype.Int2 `json:"flag_stato"`
	Categorie        []string    `json:"categorie"`
	AggiornatoIl     time.Time   `json:"aggiornato_il"`
	CasellaNome      string      `json:"casella_nome"`
	CasellaIndirizzo string      `json:"casella_indirizzo"`
	Condivisa        bool        `json:"condivisa"`
}

func (q *Queries) ListPresenze(ctx context.Context, messaggioID uuid.UUID) ([]ListPresenzeRow, error) {
	rows, err := q.db.Query(ctx, listPresenze, messaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPresenzeRow{}
	for rows.Next() {
		var i ListPresenzeRow
		if err := rows.Scan(
			&i.MessaggioID,
			&i.CasellaID,
			&i.EntryID,
			&i.Cartella,
			&i.RicevutoIl,
			&i.NonLetto,
			&i.FlagStato,
			&i.Categorie,
			&i.AggiornatoIl,
			&i.CasellaNome,
			&i.CasellaIndirizzo,
			&i.Condivisa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncCursori = `-- name: ListSyncCursori :many
SELECT sc.cartella, sc.ultimo_received, sc.storico_fino_a, sc.ultimo_sync, sc.n_messaggi, sc.errore, sc.casella_id, sc.coperto_fino_a, c.indirizzo AS casella_indirizzo, c.nome AS casella_nome
FROM sync_cursore sc JOIN casella c ON c.casella_id = sc.casella_id
ORDER BY c.indirizzo, sc.cartella
`

type ListSyncCursoriRow struct {
	Cartella         string      `json:"cartella"`
	UltimoReceived   *time.Time  `json:"ultimo_received"`
	StoricoFinoA     *time.Time  `json:"storico_fino_a"`
	UltimoSync       *time.Time  `json:"ultimo_sync"`
	NMessaggi        int32       `json:"n_messaggi"`
	Errore           pgtype.Text `json:"errore"`
	CasellaID        uuid.UUID   `json:"casella_id"`
	CopertoFinoA     *time.Time  `json:"coperto_fino_a"`
	CasellaIndirizzo string      `json:"casella_indirizzo"`
	CasellaNome      string      `json:"casella_nome"`
}

func (q *Queries) ListSyncCursori(ctx context.Context) ([]ListSyncCursoriRow, error) {
	rows, err := q.db.Query(ctx, listSyncCursori)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncCursoriRow{}
	for rows.Next() {
		var i ListSyncCursoriRow
		if err := rows.Scan(
			&i.Cartella,
			&i.UltimoReceived,
			&i.StoricoFinoA,
			&i.UltimoSync,
			&i.NMessaggi,
			&i.Errore,
			&i.CasellaID,
			&i.CopertoFinoA,
			&i.CasellaIndirizzo,
			&i.CasellaNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncCursoriCasella = `-- name: ListSyncCursoriCasella :many
SELECT cartella, ultimo_received, storico_fino_a, ultimo_sync, n_messaggi, errore, casella_id, coperto_fino_a FROM sync_cursore WHERE casella_id = $1 ORDER BY cartella
`

func (q *Queries) ListSyncCursoriCasella(ctx context.Context, casellaID uuid.UUID) ([]SyncCursore, error) {
	rows, err := q.db.Query(ctx, listSyncCursoriCasella, casellaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncCursore{}
	for rows.Next() {
		var i SyncCursore
		if err := rows.Scan(
			&i.Cartella,
			&i.UltimoReceived,
			&i.StoricoFinoA,
			&i.UltimoSync,
			&i.NMessaggi,
			&i.Errore,
			&i.CasellaID,
			&i.CopertoFinoA,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const presenzaDaAprire = `-- name: PresenzaDaAprire :one
SELECT mc.messaggio_id, mc.casella_id, mc.entry_id, mc.cartella, mc.ricevuto_il, mc.non_letto, mc.flag_stato, mc.categorie, mc.aggiornato_il, c.nome AS casella_nome, c.indirizzo AS casella_indirizzo
FROM messaggio_casella mc
JOIN casella c ON c.casella_id = mc.casella_id
WHERE mc.messaggio_id = $1 AND c.attiva
ORDER BY mc.ricevuto_il, mc.casella_id
LIMIT 1
`

type PresenzaDaAprireRow struct {
	MessaggioID      uuid.UUID   `json:"messaggio_id"`
	CasellaID        uuid.UUID   `json:"casella_id"`
	EntryID          string      `json:"entry_id"`
	Cartella         pgtype.Text `json:"cartella"`
	RicevutoIl       time.Time   `json:"ricevuto_il"`
	NonLetto         bool        `json:"non_letto"`
	FlagStato        pgtype.Int2 `json:"flag_stato"`
	Categorie        []string    `json:"categorie"`
	AggiornatoIl     time.Time   `json:"aggiornato_il"`
	CasellaNome      string      `json:"casella_nome"`
	CasellaIndirizzo string      `json:"casella_indirizzo"`
}

// La copia «di riferimento» di un messaggio quando NON c'è una postazione da cui decidere: la più
// vecchia, a parità la casella con l'uuid minore. Arbitraria ma RIPETIBILE. Dalla voce 2.7 le azioni
// interattive non la usano più: usano CopiaPerPostazione, e senza postazione non partono. Resta per
// il download (che non apre finestre e può farlo qualunque worker autorizzato sulla casella) e per la
// lettura del pannello.
func (q *Queries) PresenzaDaAprire(ctx context.Context, messaggioID uuid.UUID) (PresenzaDaAprireRow, error) {
	row := q.db.QueryRow(ctx, presenzaDaAprire, messaggioID)
	var i PresenzaDaAprireRow
	err := row.Scan(
		&i.MessaggioID,
		&i.CasellaID,
		&i.EntryID,
		&i.Cartella,
		&i.RicevutoIl,
		&i.NonLetto,
		&i.FlagStato,
		&i.Categorie,
		&i.AggiornatoIl,
		&i.CasellaNome,
		&i.CasellaIndirizzo,
	)
	return i, err
}

const setBuyerMessaggiPerIndirizzo = `-- name: SetBuyerMessaggiPerIndirizzo :execrows
UPDATE messaggio SET buyer_id = $2 WHERE lower(mittente_indirizzo) = lower($1) AND buyer_id IS NULL
`

type SetBuyerMessaggiPerIndirizzoParams struct {
	Lower   string        `json:"lower"`
	BuyerID uuid.NullUUID `json:"buyer_id"`
}

func (q *Queries) SetBuyerMessaggiPerIndirizzo(ctx context.Context, arg SetBuyerMessaggiPerIndirizzoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBuyerMessaggiPerIndirizzo, arg.Lower, arg.BuyerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBuyerMessaggio = `-- name: SetBuyerMessaggio :exec
UPDATE messaggio SET buyer_id = $2 WHERE messaggio_id = $1
`

type SetBuyerMessaggioParams struct {
	MessaggioID uuid.UUID     `json:"messaggio_id"`
	BuyerID     uuid.NullUUID `json:"buyer_id"`
}

func (q *Queries) SetBuyerMessaggio(ctx context.Context, arg SetBuyerMessaggioParams) error {
	_, err := q.db.Exec(ctx, setBuyerMessaggio, arg.MessaggioID, arg.BuyerID)
	return err
}

const setCopertoFinoA = `-- name: SetCopertoFinoA :exec
INSERT INTO sync_cursore (casella_id, cartella, coperto_fino_a)
VALUES ($1, $2, $3)
ON CONFLICT (casella_id, cartella) DO UPDATE SET
    coperto_fino_a = GREATEST(COALESCE(sync_cursore.coperto_fino_a, EXCLUDED.coperto_fino_a), EXCLUDED.coperto_fino_a)
`

type SetCopertoFinoAParams struct {
	CasellaID    uuid.UUID  `json:"casella_id"`
	Cartella     string     `json:"cartella"`
	CopertoFinoA *time.Time `json:"coperto_fino_a"`
}

// La frontiera RECENTE: fin dove Outlook e' stato scandito per intero (0010).
//
// La scrive un punto solo, `applicaRisultato`, e solo per le cartelle che il worker ha dichiarato
// COMPLETE: non a ogni lotto, e non perche' il job HTTP e' finito senza eccezioni. In lettura dal
// piu' recente al piu' vecchio il primo lotto contiene gia' la mail piu' nuova della finestra: farla
// avanzare li' significherebbe dichiarare coperto tutto l'intervallo prima ancora di averlo letto,
// e un worker che muore subito dopo lascerebbe invisibile per sempre tutto cio' che sta sotto.
//
// E' un INSERT come SetStoricoFinoA e per lo stesso motivo: una (casella, cartella) sincronizzata
// per la prima volta in una finestra dove non c'era nessuna mail non ha ancora una riga, e proprio
// quello e' il caso che questa colonna esiste per ricordare.
//
// GREATEST: due tentativi non possono farla arretrare. Arretrare sarebbe innocuo (si rilegge), ma
// renderebbe illeggibile il significato della colonna.
func (q *Queries) SetCopertoFinoA(ctx context.Context, arg SetCopertoFinoAParams) error {
	_, err := q.db.Exec(ctx, setCopertoFinoA, arg.CasellaID, arg.Cartella, arg.CopertoFinoA)
	return err
}

const setEntryIDPresenza = `-- name: SetEntryIDPresenza :exec
UPDATE messaggio_casella SET entry_id = $1, cartella = COALESCE($2, cartella),
    aggiornato_il = now()
WHERE messaggio_id = $3 AND casella_id = $4
`

type SetEntryIDPresenzaParams struct {
	EntryID     string      `json:"entry_id"`
	Cartella    pgtype.Text `json:"cartella"`
	MessaggioID uuid.UUID   `json:"messaggio_id"`
	CasellaID   uuid.UUID   `json:"casella_id"`
}

func (q *Queries) SetEntryIDPresenza(ctx context.Context, arg SetEntryIDPresenzaParams) error {
	_, err := q.db.Exec(ctx, setEntryIDPresenza,
		arg.EntryID,
		arg.Cartella,
		arg.MessaggioID,
		arg.CasellaID,
	)
	return err
}

const setNonLettoPresenza = `-- name: SetNonLettoPresenza :exec
UPDATE messaggio_casella SET non_letto = $3, aggiornato_il = now()
WHERE messaggio_id = $1 AND casella_id = $2
`

type SetNonLettoPresenzaParams struct {
	MessaggioID uuid.UUID `json:"messaggio_id"`
	CasellaID   uuid.UUID `json:"casella_id"`
	NonLetto    bool      `json:"non_letto"`
}

func (q *Queries) SetNonLettoPresenza(ctx context.Context, arg SetNonLettoPresenzaParams) error {
	_, err := q.db.Exec(ctx, setNonLettoPresenza, arg.MessaggioID, arg.CasellaID, arg.NonLetto)
	return err
}

const setStoricoFinoA = `-- name: SetStoricoFinoA :exec
INSERT INTO sync_cursore (casella_id, cartella, storico_fino_a)
VALUES ($1, $2, $3)
ON CONFLICT (casella_id, cartella) DO UPDATE SET
    storico_fino_a = LEAST(COALESCE(sync_cursore.storico_fino_a, EXCLUDED.storico_fino_a), EXCLUDED.storico_fino_a)
`

type SetStoricoFinoAParams struct {
	CasellaID    uuid.UUID  `json:"casella_id"`
	Cartella     string     `json:"cartella"`
	StoricoFinoA *time.Time `json:"storico_fino_a"`
}

// Quanto indietro è già arrivato "Carica precedenti" su quella (casella, cartella).
//
// È un INSERT, non un UPDATE: la riga del cursore nasce con il primo sync ORDINARIO, e una casella
// da cui si carica l'archivio prima di averla mai sincronizzata non ce l'ha ancora. Con l'UPDATE non
// veniva scritto niente e non lo diceva nessuno: il clic dopo ricalcolava la stessa identica
// finestra, all'infinito. `ultimo_received` resta NULL - la riga dice fin dove si è scesi, non fin
// dove si è saliti - e il sync ordinario la riempirà quando toccherà a lui.
func (q *Queries) SetStoricoFinoA(ctx context.Context, arg SetStoricoFinoAParams) error {
	_, err := q.db.Exec(ctx, setStoricoFinoA, arg.CasellaID, arg.Cartella, arg.StoricoFinoA)
	return err
}

const sgangiaMessaggio = `-- name: SgangiaMessaggio :exec
UPDATE messaggio SET thread_id = NULL, aggancio = 'nessuno', agganciato_da = $2, agganciato_il = now()
WHERE messaggio_id = $1
`

type SgangiaMessaggioParams struct {
	MessaggioID  uuid.UUID     `json:"messaggio_id"`
	AgganciatoDa uuid.NullUUID `json:"agganciato_da"`
}

func (q *Queries) SgangiaMessaggio(ctx context.Context, arg SgangiaMessaggioParams) error {
	_, err := q.db.Exec(ctx, sgangiaMessaggio, arg.MessaggioID, arg.AgganciatoDa)
	return err
}

const threadDellaConversazione = `-- name: ThreadDellaConversazione :one
SELECT thread_id FROM messaggio
WHERE conversazione_id = $1 AND thread_id IS NOT NULL
ORDER BY data_evento DESC LIMIT 1
`

func (q *Queries) ThreadDellaConversazione(ctx context.Context, conversazioneID uuid.UUID) (uuid.NullUUID, error) {
	row := q.db.QueryRow(ctx, threadDellaConversazione, conversazioneID)
	var thread_id uuid.NullUUID
	err := row.Scan(&thread_id)
	return thread_id, err
}

const upsertConversazione = `-- name: UpsertConversazione :one
INSERT INTO conversazione (canale, chiave_esterna, primo_messaggio_il)
VALUES ($1, $2, $3)
ON CONFLICT (canale, chiave_esterna) DO UPDATE
    SET primo_messaggio_il = LEAST(conversazione.primo_messaggio_il, EXCLUDED.primo_messaggio_il)
RETURNING conversazione_id, canale, chiave_esterna, thread_id, collegata_da, primo_messaggio_il
`

type UpsertConversazioneParams struct {
	Canale           Canale    `json:"canale"`
	ChiaveEsterna    string    `json:"chiave_esterna"`
	PrimoMessaggioIl time.Time `json:"primo_messaggio_il"`
}

func (q *Queries) UpsertConversazione(ctx context.Context, arg UpsertConversazioneParams) (Conversazione, error) {
	row := q.db.QueryRow(ctx, upsertConversazione, arg.Canale, arg.ChiaveEsterna, arg.PrimoMessaggioIl)
	var i Conversazione
	err := row.Scan(
		&i.ConversazioneID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ThreadID,
		&i.CollegataDa,
		&i.PrimoMessaggioIl,
	)
	return i, err
}

const upsertMessaggio = `-- name: UpsertMessaggio :one
INSERT INTO messaggio (canale, chiave_esterna, conversazione_id, parent_messaggio_id, direzione, data_evento,
                       mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html,
                       lingua, importanza, nota_operatore, registrato_da, interno)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (canale, chiave_esterna) DO UPDATE SET
    conversazione_id = EXCLUDED.conversazione_id,
    direzione        = CASE WHEN 'uscita' IN (messaggio.direzione, EXCLUDED.direzione)
                            THEN 'uscita'::direzione ELSE EXCLUDED.direzione END,
    interno          = EXCLUDED.interno,
    mittente_nome    = COALESCE(EXCLUDED.mittente_nome, messaggio.mittente_nome),
    destinatari      = EXCLUDED.destinatari,
    corpo_testo      = COALESCE(EXCLUDED.corpo_testo, messaggio.corpo_testo),
    corpo_html       = COALESCE(EXCLUDED.corpo_html, messaggio.corpo_html),
    importanza       = COALESCE(EXCLUDED.importanza, messaggio.importanza),
    buyer_id         = COALESCE(messaggio.buyer_id, EXCLUDED.buyer_id)
RETURNING messaggio_id, canale, chiave_esterna, conversazione_id, parent_messaggio_id, thread_id, aggancio, agganciato_da, agganciato_il, direzione, data_evento, mittente_nome, mittente_indirizzo, buyer_id, destinatari, oggetto, corpo_testo, corpo_html, lingua, importanza, nota_operatore, n_allegati, registrato_il, registrato_da, interno, controparte_tipo, controparte_cliente_id, controparte_fornitore_id, controparte_via, controparte_il, (xmax = 0) AS inserito
`

type UpsertMessaggioParams struct {
	Canale            Canale          `json:"canale"`
	ChiaveEsterna     string          `json:"chiave_esterna"`
	ConversazioneID   uuid.UUID       `json:"conversazione_id"`
	ParentMessaggioID uuid.NullUUID   `json:"parent_messaggio_id"`
	Direzione         Direzione       `json:"direzione"`
	DataEvento        time.Time       `json:"data_evento"`
	MittenteNome      pgtype.Text     `json:"mittente_nome"`
	MittenteIndirizzo pgtype.Text     `json:"mittente_indirizzo"`
	BuyerID           uuid.NullUUID   `json:"buyer_id"`
	Destinatari       json.RawMessage `json:"destinatari"`
	Oggetto           pgtype.Text     `json:"oggetto"`
	CorpoTesto        pgtype.Text     `json:"corpo_testo"`
	CorpoHtml         pgtype.Text     `json:"corpo_html"`
	Lingua            pgtype.Text     `json:"lingua"`
	Importanza        pgtype.Int2     `json:"importanza"`
	NotaOperatore     pgtype.Text     `json:"nota_operatore"`
	RegistratoDa      uuid.NullUUID   `json:"registrato_da"`
	Interno           bool            `json:"interno"`
}

type UpsertMessaggioRow struct {
	MessaggioID            uuid.UUID          `json:"messaggio_id"`
	Canale                 Canale             `json:"canale"`
	ChiaveEsterna          string             `json:"chiave_esterna"`
	ConversazioneID        uuid.UUID          `json:"conversazione_id"`
	ParentMessaggioID      uuid.NullUUID      `json:"parent_messaggio_id"`
	ThreadID               uuid.NullUUID      `json:"thread_id"`
	Aggancio               Aggancio           `json:"aggancio"`
	AgganciatoDa           uuid.NullUUID      `json:"agganciato_da"`
	AgganciatoIl           *time.Time         `json:"agganciato_il"`
	Direzione              Direzione          `json:"direzione"`
	DataEvento             time.Time          `json:"data_evento"`
	MittenteNome           pgtype.Text        `json:"mittente_nome"`
	MittenteIndirizzo      pgtype.Text        `json:"mittente_indirizzo"`
	BuyerID                uuid.NullUUID      `json:"buyer_id"`
	Destinatari            json.RawMessage    `json:"destinatari"`
	Oggetto                pgtype.Text        `json:"oggetto"`
	CorpoTesto             pgtype.Text        `json:"corpo_testo"`
	CorpoHtml              pgtype.Text        `json:"corpo_html"`
	Lingua                 pgtype.Text        `json:"lingua"`
	Importanza             pgtype.Int2        `json:"importanza"`
	NotaOperatore          pgtype.Text        `json:"nota_operatore"`
	NAllegati              int16              `json:"n_allegati"`
	RegistratoIl           time.Time          `json:"registrato_il"`
	RegistratoDa           uuid.NullUUID      `json:"registrato_da"`
	Interno                bool               `json:"interno"`
	ControparteTipo        TipoControparte    `json:"controparte_tipo"`
	ControparteClienteID   uuid.NullUUID      `json:"controparte_cliente_id"`
	ControparteFornitoreID uuid.NullUUID      `json:"controparte_fornitore_id"`
	ControparteVia         NullViaControparte `json:"controparte_via"`
	ControparteIl          *time.Time         `json:"controparte_il"`
	Inserito               bool               `json:"inserito"`
}

// La direzione si CONSOLIDA: la stessa mail può arrivare da due caselle, e una copia che ci risulta
// in entrata non deve cancellare il fatto che l'abbiamo mandata noi. «Uscita» vince (voce 2.1, D10).
// `interno` è separato dalla direzione: una mail fra colleghi è in uscita ma non è traffico con il
// cliente, e confondere le due cose farebbe nascere RFQ da conversazioni interne.
func (q *Queries) UpsertMessaggio(ctx context.Context, arg UpsertMessaggioParams) (UpsertMessaggioRow, error) {
	row := q.db.QueryRow(ctx, upsertMessaggio,
		arg.Canale,
		arg.ChiaveEsterna,
		arg.ConversazioneID,
		arg.ParentMessaggioID,
		arg.Direzione,
		arg.DataEvento,
		arg.MittenteNome,
		arg.MittenteIndirizzo,
		arg.BuyerID,
		arg.Destinatari,
		arg.Oggetto,
		arg.CorpoTesto,
		arg.CorpoHtml,
		arg.Lingua,
		arg.Importanza,
		arg.NotaOperatore,
		arg.RegistratoDa,
		arg.Interno,
	)
	var i UpsertMessaggioRow
	err := row.Scan(
		&i.MessaggioID,
		&i.Canale,
		&i.ChiaveEsterna,
		&i.ConversazioneID,
		&i.ParentMessaggioID,
		&i.ThreadID,
		&i.Aggancio,
		&i.AgganciatoDa,
		&i.AgganciatoIl,
		&i.Direzione,
		&i.DataEvento,
		&i.MittenteNome,
		&i.MittenteIndirizzo,
		&i.BuyerID,
		&i.Destinatari,
		&i.Oggetto,
		&i.CorpoTesto,
		&i.CorpoHtml,
		&i.Lingua,
		&i.Importanza,
		&i.NotaOperatore,
		&i.NAllegati,
		&i.RegistratoIl,
		&i.RegistratoDa,
		&i.Interno,
		&i.ControparteTipo,
		&i.ControparteClienteID,
		&i.ControparteFornitoreID,
		&i.ControparteVia,
		&i.ControparteIl,
		&i.Inserito,
	)
	return i, err
}

const upsertMessaggioOutlook = `-- name: UpsertMessaggioOutlook :exec
INSERT INTO messaggio_outlook (messaggio_id, conversation_id, conversation_index, in_reply_to, riferimenti)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (messaggio_id) DO UPDATE SET
    in_reply_to = COALESCE(EXCLUDED.in_reply_to, messaggio_outlook.in_reply_to),
    riferimenti = COALESCE(EXCLUDED.riferimenti, messaggio_outlook.riferimenti),
    aggiornato_il = now()
`

type UpsertMessaggioOutlookParams struct {
	MessaggioID       uuid.UUID   `json:"messaggio_id"`
	ConversationID    pgtype.Text `json:"conversation_id"`
	ConversationIndex pgtype.Text `json:"conversation_index"`
	InReplyTo         pgtype.Text `json:"in_reply_to"`
	Riferimenti       []string    `json:"riferimenti"`
}

// Solo ciò che è del MESSAGGIO. Entry_id, cartella, categorie, non_letto e flag_stato sono della
// COPIA e stanno in messaggio_casella dalla 0004: tenerli qui significava che la seconda casella
// sovrascriveva l'EntryID della prima, e «Apri in Outlook» apriva l'elemento sbagliato.
func (q *Queries) UpsertMessaggioOutlook(ctx context.Context, arg UpsertMessaggioOutlookParams) error {
	_, err := q.db.Exec(ctx, upsertMessaggioOutlook,
		arg.MessaggioID,
		arg.ConversationID,
		arg.ConversationIndex,
		arg.InReplyTo,
		arg.Riferimenti,
	)
	return err
}

const upsertPresenza = `-- name: UpsertPresenza :exec
INSERT INTO messaggio_casella (messaggio_id, casella_id, entry_id, cartella, ricevuto_il, non_letto, flag_stato, categorie)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (messaggio_id, casella_id) DO UPDATE SET
    entry_id = EXCLUDED.entry_id, cartella = EXCLUDED.cartella, ricevuto_il = EXCLUDED.ricevuto_il,
    non_letto = EXCLUDED.non_letto, flag_stato = EXCLUDED.flag_stato, categorie = EXCLUDED.categorie,
    aggiornato_il = now()
`

type UpsertPresenzaParams struct {
	MessaggioID uuid.UUID   `json:"messaggio_id"`
	CasellaID   uuid.UUID   `json:"casella_id"`
	EntryID     string      `json:"entry_id"`
	Cartella    pgtype.Text `json:"cartella"`
	RicevutoIl  time.Time   `json:"ricevuto_il"`
	NonLetto    bool        `json:"non_letto"`
	FlagStato   pgtype.Int2 `json:"flag_stato"`
	Categorie   []string    `json:"categorie"`
}

// La presenza di un messaggio in una casella (voce 2.1). Due caselle = due righe, ognuna con il suo
// EntryID, la sua cartella e il suo stato di lettura: sono fatti di quella copia, non del messaggio.
// Nessuno store_id (0005): lo StoreID è del profilo Outlook della postazione, non della copia, e sta
// in casella_store dove ogni worker lo scrive per sé (voce 2.6, N44).
func (q *Queries) UpsertPresenza(ctx context.Context, arg UpsertPresenzaParams) error {
	_, err := q.db.Exec(ctx, upsertPresenza,
		arg.MessaggioID,
		arg.CasellaID,
		arg.EntryID,
		arg.Cartella,
		arg.RicevutoIl,
		arg.NonLetto,
		arg.FlagStato,
		arg.Categorie,
	)
	return err
}

const upsertSyncCursore = `-- name: UpsertSyncCursore :exec
INSERT INTO sync_cursore (casella_id, cartella, ultimo_received, ultimo_sync, n_messaggi, errore)
VALUES ($1, $2, $3, now(), $4, $5)
ON CONFLICT (casella_id, cartella) DO UPDATE SET
    ultimo_received = GREATEST(COALESCE(sync_cursore.ultimo_received, EXCLUDED.ultimo_received), EXCLUDED.ultimo_received),
    ultimo_sync = now(), n_messaggi = sync_cursore.n_messaggi + EXCLUDED.n_messaggi, errore = EXCLUDED.errore
`

type UpsertSyncCursoreParams struct {
	CasellaID      uuid.UUID   `json:"casella_id"`
	Cartella       string      `json:"cartella"`
	UltimoReceived *time.Time  `json:"ultimo_received"`
	NMessaggi      int32       `json:"n_messaggi"`
	Errore         pgtype.Text `json:"errore"`
}

// `ultimo_received` e' la mail piu' RECENTE che abbiamo di quella (casella, cartella), non fin dove
// si e' guardato: avanza per lotto, in transazione con gli elementi, e GREATEST impedisce che due
// tentativi la facciano arretrare (Q22). Dalla 0010 non decide piu' nessuna finestra — la frontiera
// e' `coperto_fino_a`, che si scrive altrove e a condizioni molto piu' severe.
func (q *Queries) UpsertSyncCursore(ctx context.Context, arg UpsertSyncCursoreParams) error {
	_, err := q.db.Exec(ctx, upsertSyncCursore,
		arg.CasellaID,
		arg.Cartella,
		arg.UltimoReceived,
		arg.NMessaggi,
		arg.Errore,
	)
	return err
}
