// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: richieste.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const agganciaRispostaFornitore = `-- name: AgganciaRispostaFornitore :exec

UPDATE messaggio SET richiesta_fornitore_id = $2 WHERE messaggio_id = $1
`

type AgganciaRispostaFornitoreParams struct {
	MessaggioID          uuid.UUID     `json:"messaggio_id"`
	RichiestaFornitoreID uuid.NullUUID `json:"richiesta_fornitore_id"`
}

// ---------------------------------------------------------------- le decisioni
func (q *Queries) AgganciaRispostaFornitore(ctx context.Context, arg AgganciaRispostaFornitoreParams) error {
	_, err := q.db.Exec(ctx, agganciaRispostaFornitore, arg.MessaggioID, arg.RichiestaFornitoreID)
	return err
}

const cancellaCandidatiRichiesta = `-- name: CancellaCandidatiRichiesta :exec
DELETE FROM candidato_richiesta WHERE messaggio_id = $1
`

func (q *Queries) CancellaCandidatiRichiesta(ctx context.Context, messaggioID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancellaCandidatiRichiesta, messaggioID)
	return err
}

const clientiConRichiesteAlFornitore = `-- name: ClientiConRichiesteAlFornitore :many
SELECT DISTINCT c.cliente_id, c.cartella_nas, c.ragione_sociale, c.profilo, c.lingua, c.portale_url, c.portale_note, c.regole, c.attivo, c.note, c.creato_il, c.peso
FROM richiesta_fornitore r
JOIN thread_offerta t ON t.thread_id = r.thread_id
JOIN cliente c ON c.cliente_id = t.cliente_id
WHERE r.fornitore_id = $1 AND r.stato IN ('inviata', 'offerta_ricevuta')
`

// I clienti che hanno richieste aperte a questo fornitore: le SOLE famiglie con cui si cercano codici
// nella posta di un fornitore (IB8: materiali e norme non sono codici di nessuno).
func (q *Queries) ClientiConRichiesteAlFornitore(ctx context.Context, fornitoreID uuid.UUID) ([]Cliente, error) {
	rows, err := q.db.Query(ctx, clientiConRichiesteAlFornitore, fornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cliente{}
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.ClienteID,
			&i.CartellaNas,
			&i.RagioneSociale,
			&i.Profilo,
			&i.Lingua,
			&i.PortaleUrl,
			&i.PortaleNote,
			&i.Regole,
			&i.Attivo,
			&i.Note,
			&i.CreatoIl,
			&i.Peso,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contaRichiesteAperte = `-- name: ContaRichiesteAperte :one
SELECT count(*) FROM richiesta_fornitore WHERE thread_id = $1 AND stato IN ('bozza', 'inviata')
`

func (q *Queries) ContaRichiesteAperte(ctx context.Context, threadID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contaRichiesteAperte, threadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRichiesta = `-- name: GetRichiesta :one
SELECT richiesta_id, thread_id, fornitore_id, lavorazione, codici, messaggio_id, stato, inviata_il, offerta_ricevuta_il, note, creata_da, creata_il, declinata_il FROM richiesta_fornitore WHERE richiesta_id = $1
`

func (q *Queries) GetRichiesta(ctx context.Context, richiestaID uuid.UUID) (RichiestaFornitore, error) {
	row := q.db.QueryRow(ctx, getRichiesta, richiestaID)
	var i RichiestaFornitore
	err := row.Scan(
		&i.RichiestaID,
		&i.ThreadID,
		&i.FornitoreID,
		&i.Lavorazione,
		&i.Codici,
		&i.MessaggioID,
		&i.Stato,
		&i.InviataIl,
		&i.OffertaRicevutaIl,
		&i.Note,
		&i.CreataDa,
		&i.CreataIl,
		&i.DeclinataIl,
	)
	return i, err
}

const insertBozzaRichiesta = `-- name: InsertBozzaRichiesta :one
INSERT INTO bozza (thread_id, in_risposta_a, tipo, destinatari, oggetto, corpo, documenti, creata_da, richiesta_fornitore_id)
VALUES ($1, NULL, 'nuovo', $2, $3, $4, '{}', $5, $6) RETURNING bozza_id, thread_id, in_risposta_a, tipo, destinatari, oggetto, corpo, documenti, entry_id, stato, errore, inviata_messaggio_id, creata_da, creata_il, richiesta_fornitore_id
`

type InsertBozzaRichiestaParams struct {
	ThreadID             uuid.NullUUID   `json:"thread_id"`
	Destinatari          json.RawMessage `json:"destinatari"`
	Oggetto              pgtype.Text     `json:"oggetto"`
	Corpo                pgtype.Text     `json:"corpo"`
	CreataDa             uuid.UUID       `json:"creata_da"`
	RichiestaFornitoreID uuid.NullUUID   `json:"richiesta_fornitore_id"`
}

func (q *Queries) InsertBozzaRichiesta(ctx context.Context, arg InsertBozzaRichiestaParams) (Bozza, error) {
	row := q.db.QueryRow(ctx, insertBozzaRichiesta,
		arg.ThreadID,
		arg.Destinatari,
		arg.Oggetto,
		arg.Corpo,
		arg.CreataDa,
		arg.RichiestaFornitoreID,
	)
	var i Bozza
	err := row.Scan(
		&i.BozzaID,
		&i.ThreadID,
		&i.InRispostaA,
		&i.Tipo,
		&i.Destinatari,
		&i.Oggetto,
		&i.Corpo,
		&i.Documenti,
		&i.EntryID,
		&i.Stato,
		&i.Errore,
		&i.InviataMessaggioID,
		&i.CreataDa,
		&i.CreataIl,
		&i.RichiestaFornitoreID,
	)
	return i, err
}

const insertCandidatoRichiesta = `-- name: InsertCandidatoRichiesta :exec
INSERT INTO candidato_richiesta (messaggio_id, richiesta_id, regola, punteggio, evidenza)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (messaggio_id, richiesta_id, regola) DO UPDATE SET punteggio = EXCLUDED.punteggio, evidenza = EXCLUDED.evidenza, creato_il = now()
`

type InsertCandidatoRichiestaParams struct {
	MessaggioID uuid.UUID       `json:"messaggio_id"`
	RichiestaID uuid.UUID       `json:"richiesta_id"`
	Regola      RegolaRichiesta `json:"regola"`
	Punteggio   int16           `json:"punteggio"`
	Evidenza    string          `json:"evidenza"`
}

func (q *Queries) InsertCandidatoRichiesta(ctx context.Context, arg InsertCandidatoRichiestaParams) error {
	_, err := q.db.Exec(ctx, insertCandidatoRichiesta,
		arg.MessaggioID,
		arg.RichiestaID,
		arg.Regola,
		arg.Punteggio,
		arg.Evidenza,
	)
	return err
}

const insertRichiestaFornitore = `-- name: InsertRichiestaFornitore :one


INSERT INTO richiesta_fornitore (thread_id, fornitore_id, lavorazione, codici, note, creata_da, stato, messaggio_id, inviata_il)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING richiesta_id, thread_id, fornitore_id, lavorazione, codici, messaggio_id, stato, inviata_il, offerta_ricevuta_il, note, creata_da, creata_il, declinata_il
`

type InsertRichiestaFornitoreParams struct {
	ThreadID    uuid.UUID               `json:"thread_id"`
	FornitoreID uuid.UUID               `json:"fornitore_id"`
	Lavorazione pgtype.Text             `json:"lavorazione"`
	Codici      []string                `json:"codici"`
	Note        pgtype.Text             `json:"note"`
	CreataDa    uuid.NullUUID           `json:"creata_da"`
	Stato       StatoRichiestaFornitore `json:"stato"`
	MessaggioID uuid.NullUUID           `json:"messaggio_id"`
	InviataIl   *time.Time              `json:"inviata_il"`
}

// Blocco 7B: le richieste d'offerta ai fornitori (0015). Nessuna di queste query decide: scrivere
// `messaggio.thread_id` o `messaggio.richiesta_fornitore_id` e' una decisione, e passa da
// `AgganciaRispostaFornitore` che chiama solo il gestore della conferma.
// ---------------------------------------------------------------- la richiesta
func (q *Queries) InsertRichiestaFornitore(ctx context.Context, arg InsertRichiestaFornitoreParams) (RichiestaFornitore, error) {
	row := q.db.QueryRow(ctx, insertRichiestaFornitore,
		arg.ThreadID,
		arg.FornitoreID,
		arg.Lavorazione,
		arg.Codici,
		arg.Note,
		arg.CreataDa,
		arg.Stato,
		arg.MessaggioID,
		arg.InviataIl,
	)
	var i RichiestaFornitore
	err := row.Scan(
		&i.RichiestaID,
		&i.ThreadID,
		&i.FornitoreID,
		&i.Lavorazione,
		&i.Codici,
		&i.MessaggioID,
		&i.Stato,
		&i.InviataIl,
		&i.OffertaRicevutaIl,
		&i.Note,
		&i.CreataDa,
		&i.CreataIl,
		&i.DeclinataIl,
	)
	return i, err
}

const listCandidatiRichiesta = `-- name: ListCandidatiRichiesta :many
SELECT k.messaggio_id, k.richiesta_id, k.regola, k.punteggio, k.evidenza, k.creato_il, r.thread_id, r.fornitore_id, r.stato AS richiesta_stato, r.codici, r.lavorazione,
       f.ragione_sociale AS fornitore, t.oggetto AS oggetto_rfq, t.cartella_relativa, c.cartella_nas AS cliente
FROM candidato_richiesta k
JOIN richiesta_fornitore r ON r.richiesta_id = k.richiesta_id
JOIN fornitore f ON f.fornitore_id = r.fornitore_id
JOIN thread_offerta t ON t.thread_id = r.thread_id
JOIN cliente c ON c.cliente_id = t.cliente_id
WHERE k.messaggio_id = $1
ORDER BY k.punteggio DESC, k.creato_il
`

type ListCandidatiRichiestaRow struct {
	MessaggioID      uuid.UUID               `json:"messaggio_id"`
	RichiestaID      uuid.UUID               `json:"richiesta_id"`
	Regola           RegolaRichiesta         `json:"regola"`
	Punteggio        int16                   `json:"punteggio"`
	Evidenza         string                  `json:"evidenza"`
	CreatoIl         time.Time               `json:"creato_il"`
	ThreadID         uuid.UUID               `json:"thread_id"`
	FornitoreID      uuid.UUID               `json:"fornitore_id"`
	RichiestaStato   StatoRichiestaFornitore `json:"richiesta_stato"`
	Codici           []string                `json:"codici"`
	Lavorazione      pgtype.Text             `json:"lavorazione"`
	Fornitore        string                  `json:"fornitore"`
	OggettoRfq       pgtype.Text             `json:"oggetto_rfq"`
	CartellaRelativa pgtype.Text             `json:"cartella_relativa"`
	Cliente          string                  `json:"cliente"`
}

func (q *Queries) ListCandidatiRichiesta(ctx context.Context, messaggioID uuid.UUID) ([]ListCandidatiRichiestaRow, error) {
	rows, err := q.db.Query(ctx, listCandidatiRichiesta, messaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidatiRichiestaRow{}
	for rows.Next() {
		var i ListCandidatiRichiestaRow
		if err := rows.Scan(
			&i.MessaggioID,
			&i.RichiestaID,
			&i.Regola,
			&i.Punteggio,
			&i.Evidenza,
			&i.CreatoIl,
			&i.ThreadID,
			&i.FornitoreID,
			&i.RichiestaStato,
			&i.Codici,
			&i.Lavorazione,
			&i.Fornitore,
			&i.OggettoRfq,
			&i.CartellaRelativa,
			&i.Cliente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRichiesteFornitore = `-- name: ListRichiesteFornitore :many
SELECT r.richiesta_id, r.thread_id, r.fornitore_id, r.lavorazione, r.codici, r.messaggio_id, r.stato, r.inviata_il, r.offerta_ricevuta_il, r.note, r.creata_da, r.creata_il, r.declinata_il, t.oggetto AS oggetto_rfq, t.cartella_relativa, c.cartella_nas AS cliente
FROM richiesta_fornitore r
JOIN thread_offerta t ON t.thread_id = r.thread_id
JOIN cliente c ON c.cliente_id = t.cliente_id
WHERE r.fornitore_id = $1 ORDER BY r.creata_il DESC LIMIT 50
`

type ListRichiesteFornitoreRow struct {
	RichiestaID       uuid.UUID               `json:"richiesta_id"`
	ThreadID          uuid.UUID               `json:"thread_id"`
	FornitoreID       uuid.UUID               `json:"fornitore_id"`
	Lavorazione       pgtype.Text             `json:"lavorazione"`
	Codici            []string                `json:"codici"`
	MessaggioID       uuid.NullUUID           `json:"messaggio_id"`
	Stato             StatoRichiestaFornitore `json:"stato"`
	InviataIl         *time.Time              `json:"inviata_il"`
	OffertaRicevutaIl *time.Time              `json:"offerta_ricevuta_il"`
	Note              pgtype.Text             `json:"note"`
	CreataDa          uuid.NullUUID           `json:"creata_da"`
	CreataIl          time.Time               `json:"creata_il"`
	DeclinataIl       *time.Time              `json:"declinata_il"`
	OggettoRfq        pgtype.Text             `json:"oggetto_rfq"`
	CartellaRelativa  pgtype.Text             `json:"cartella_relativa"`
	Cliente           string                  `json:"cliente"`
}

func (q *Queries) ListRichiesteFornitore(ctx context.Context, fornitoreID uuid.UUID) ([]ListRichiesteFornitoreRow, error) {
	rows, err := q.db.Query(ctx, listRichiesteFornitore, fornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRichiesteFornitoreRow{}
	for rows.Next() {
		var i ListRichiesteFornitoreRow
		if err := rows.Scan(
			&i.RichiestaID,
			&i.ThreadID,
			&i.FornitoreID,
			&i.Lavorazione,
			&i.Codici,
			&i.MessaggioID,
			&i.Stato,
			&i.InviataIl,
			&i.OffertaRicevutaIl,
			&i.Note,
			&i.CreataDa,
			&i.CreataIl,
			&i.DeclinataIl,
			&i.OggettoRfq,
			&i.CartellaRelativa,
			&i.Cliente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRichiesteThread = `-- name: ListRichiesteThread :many
SELECT r.richiesta_id, r.thread_id, r.fornitore_id, r.lavorazione, r.codici, r.messaggio_id, r.stato, r.inviata_il, r.offerta_ricevuta_il, r.note, r.creata_da, r.creata_il, r.declinata_il, f.ragione_sociale AS fornitore, l.descrizione AS lavorazione_descrizione,
       m.oggetto AS oggetto_mail, m.data_evento AS data_mail,
       (SELECT count(*) FROM messaggio x WHERE x.richiesta_fornitore_id = r.richiesta_id AND x.direzione = 'entrata') AS n_risposte
FROM richiesta_fornitore r
JOIN fornitore f ON f.fornitore_id = r.fornitore_id
LEFT JOIN lavorazione l ON l.codice = r.lavorazione
LEFT JOIN messaggio m ON m.messaggio_id = r.messaggio_id
WHERE r.thread_id = $1 ORDER BY r.creata_il
`

type ListRichiesteThreadRow struct {
	RichiestaID            uuid.UUID               `json:"richiesta_id"`
	ThreadID               uuid.UUID               `json:"thread_id"`
	FornitoreID            uuid.UUID               `json:"fornitore_id"`
	Lavorazione            pgtype.Text             `json:"lavorazione"`
	Codici                 []string                `json:"codici"`
	MessaggioID            uuid.NullUUID           `json:"messaggio_id"`
	Stato                  StatoRichiestaFornitore `json:"stato"`
	InviataIl              *time.Time              `json:"inviata_il"`
	OffertaRicevutaIl      *time.Time              `json:"offerta_ricevuta_il"`
	Note                   pgtype.Text             `json:"note"`
	CreataDa               uuid.NullUUID           `json:"creata_da"`
	CreataIl               time.Time               `json:"creata_il"`
	DeclinataIl            *time.Time              `json:"declinata_il"`
	Fornitore              string                  `json:"fornitore"`
	LavorazioneDescrizione pgtype.Text             `json:"lavorazione_descrizione"`
	OggettoMail            pgtype.Text             `json:"oggetto_mail"`
	DataMail               *time.Time              `json:"data_mail"`
	NRisposte              int64                   `json:"n_risposte"`
}

func (q *Queries) ListRichiesteThread(ctx context.Context, threadID uuid.UUID) ([]ListRichiesteThreadRow, error) {
	rows, err := q.db.Query(ctx, listRichiesteThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRichiesteThreadRow{}
	for rows.Next() {
		var i ListRichiesteThreadRow
		if err := rows.Scan(
			&i.RichiestaID,
			&i.ThreadID,
			&i.FornitoreID,
			&i.Lavorazione,
			&i.Codici,
			&i.MessaggioID,
			&i.Stato,
			&i.InviataIl,
			&i.OffertaRicevutaIl,
			&i.Note,
			&i.CreataDa,
			&i.CreataIl,
			&i.DeclinataIl,
			&i.Fornitore,
			&i.LavorazioneDescrizione,
			&i.OggettoMail,
			&i.DataMail,
			&i.NRisposte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const richiestaPerMarcatore = `-- name: RichiestaPerMarcatore :one
SELECT richiesta_id, thread_id, fornitore_id, lavorazione, codici, messaggio_id, stato, inviata_il, offerta_ricevuta_il, note, creata_da, creata_il, declinata_il FROM richiesta_fornitore WHERE richiesta_id = $1
`

func (q *Queries) RichiestaPerMarcatore(ctx context.Context, richiestaID uuid.UUID) (RichiestaFornitore, error) {
	row := q.db.QueryRow(ctx, richiestaPerMarcatore, richiestaID)
	var i RichiestaFornitore
	err := row.Scan(
		&i.RichiestaID,
		&i.ThreadID,
		&i.FornitoreID,
		&i.Lavorazione,
		&i.Codici,
		&i.MessaggioID,
		&i.Stato,
		&i.InviataIl,
		&i.OffertaRicevutaIl,
		&i.Note,
		&i.CreataDa,
		&i.CreataIl,
		&i.DeclinataIl,
	)
	return i, err
}

const richiestePerChiaviCitate = `-- name: RichiestePerChiaviCitate :many

SELECT r.richiesta_id, r.thread_id, r.fornitore_id, r.lavorazione, r.codici, r.messaggio_id, r.stato, r.inviata_il, r.offerta_ricevuta_il, r.note, r.creata_da, r.creata_il, r.declinata_il, m.chiave_esterna
FROM richiesta_fornitore r
JOIN messaggio m ON m.messaggio_id = r.messaggio_id
WHERE m.chiave_esterna = ANY($1::text[]) AND r.fornitore_id = $2
`

type RichiestePerChiaviCitateParams struct {
	Chiavi      []string  `json:"chiavi"`
	FornitoreID uuid.UUID `json:"fornitore_id"`
}

type RichiestePerChiaviCitateRow struct {
	RichiestaID       uuid.UUID               `json:"richiesta_id"`
	ThreadID          uuid.UUID               `json:"thread_id"`
	FornitoreID       uuid.UUID               `json:"fornitore_id"`
	Lavorazione       pgtype.Text             `json:"lavorazione"`
	Codici            []string                `json:"codici"`
	MessaggioID       uuid.NullUUID           `json:"messaggio_id"`
	Stato             StatoRichiestaFornitore `json:"stato"`
	InviataIl         *time.Time              `json:"inviata_il"`
	OffertaRicevutaIl *time.Time              `json:"offerta_ricevuta_il"`
	Note              pgtype.Text             `json:"note"`
	CreataDa          uuid.NullUUID           `json:"creata_da"`
	CreataIl          time.Time               `json:"creata_il"`
	DeclinataIl       *time.Time              `json:"declinata_il"`
	ChiaveEsterna     string                  `json:"chiave_esterna"`
}

// ---------------------------------------------------------------- i candidati verso una richiesta (7B.2)
// R0: In-Reply-To / References verso LA NOSTRA mail di richiesta.
func (q *Queries) RichiestePerChiaviCitate(ctx context.Context, arg RichiestePerChiaviCitateParams) ([]RichiestePerChiaviCitateRow, error) {
	rows, err := q.db.Query(ctx, richiestePerChiaviCitate, arg.Chiavi, arg.FornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RichiestePerChiaviCitateRow{}
	for rows.Next() {
		var i RichiestePerChiaviCitateRow
		if err := rows.Scan(
			&i.RichiestaID,
			&i.ThreadID,
			&i.FornitoreID,
			&i.Lavorazione,
			&i.Codici,
			&i.MessaggioID,
			&i.Stato,
			&i.InviataIl,
			&i.OffertaRicevutaIl,
			&i.Note,
			&i.CreataDa,
			&i.CreataIl,
			&i.DeclinataIl,
			&i.ChiaveEsterna,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const richiestePerCodiciFornitore = `-- name: RichiestePerCodiciFornitore :many
SELECT DISTINCT r.richiesta_id, r.thread_id, r.fornitore_id, r.lavorazione, r.codici, r.messaggio_id, r.stato, r.inviata_il, r.offerta_ricevuta_il, r.note, r.creata_da, r.creata_il, r.declinata_il, i.codice
FROM richiesta_fornitore r
JOIN thread_offerta t ON t.thread_id = r.thread_id
JOIN identificativo_thread i ON i.thread_id = t.thread_id
WHERE r.fornitore_id = $1 AND r.stato IN ('inviata', 'offerta_ricevuta')
  AND (upper(i.codice) = ANY($2::text[]) OR EXISTS (SELECT 1 FROM unnest(r.codici) c WHERE upper(c) = ANY($2::text[])))
LIMIT 20
`

type RichiestePerCodiciFornitoreParams struct {
	FornitoreID uuid.UUID `json:"fornitore_id"`
	Codici      []string  `json:"codici"`
}

type RichiestePerCodiciFornitoreRow struct {
	RichiestaID       uuid.UUID               `json:"richiesta_id"`
	ThreadID          uuid.UUID               `json:"thread_id"`
	FornitoreID       uuid.UUID               `json:"fornitore_id"`
	Lavorazione       pgtype.Text             `json:"lavorazione"`
	Codici            []string                `json:"codici"`
	MessaggioID       uuid.NullUUID           `json:"messaggio_id"`
	Stato             StatoRichiestaFornitore `json:"stato"`
	InviataIl         *time.Time              `json:"inviata_il"`
	OffertaRicevutaIl *time.Time              `json:"offerta_ricevuta_il"`
	Note              pgtype.Text             `json:"note"`
	CreataDa          uuid.NullUUID           `json:"creata_da"`
	CreataIl          time.Time               `json:"creata_il"`
	DeclinataIl       *time.Time              `json:"declinata_il"`
	Codice            string                  `json:"codice"`
}

// R3f: un codice cliente citato che appartiene a una RFQ con una richiesta a QUESTO fornitore,
// nei codici chiesti o fra gli identificativi della RFQ.
func (q *Queries) RichiestePerCodiciFornitore(ctx context.Context, arg RichiestePerCodiciFornitoreParams) ([]RichiestePerCodiciFornitoreRow, error) {
	rows, err := q.db.Query(ctx, richiestePerCodiciFornitore, arg.FornitoreID, arg.Codici)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RichiestePerCodiciFornitoreRow{}
	for rows.Next() {
		var i RichiestePerCodiciFornitoreRow
		if err := rows.Scan(
			&i.RichiestaID,
			&i.ThreadID,
			&i.FornitoreID,
			&i.Lavorazione,
			&i.Codici,
			&i.MessaggioID,
			&i.Stato,
			&i.InviataIl,
			&i.OffertaRicevutaIl,
			&i.Note,
			&i.CreataDa,
			&i.CreataIl,
			&i.DeclinataIl,
			&i.Codice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const richiestePerConversazione = `-- name: RichiestePerConversazione :many
SELECT r.richiesta_id, r.thread_id, r.fornitore_id, r.lavorazione, r.codici, r.messaggio_id, r.stato, r.inviata_il, r.offerta_ricevuta_il, r.note, r.creata_da, r.creata_il, r.declinata_il
FROM richiesta_fornitore r
JOIN messaggio m ON m.messaggio_id = r.messaggio_id
WHERE m.conversazione_id = $1 AND r.fornitore_id = $2
`

type RichiestePerConversazioneParams struct {
	ConversazioneID uuid.UUID `json:"conversazione_id"`
	FornitoreID     uuid.UUID `json:"fornitore_id"`
}

// R1: la conversazione di Outlook della nostra mail di richiesta.
func (q *Queries) RichiestePerConversazione(ctx context.Context, arg RichiestePerConversazioneParams) ([]RichiestaFornitore, error) {
	rows, err := q.db.Query(ctx, richiestePerConversazione, arg.ConversazioneID, arg.FornitoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RichiestaFornitore{}
	for rows.Next() {
		var i RichiestaFornitore
		if err := rows.Scan(
			&i.RichiestaID,
			&i.ThreadID,
			&i.FornitoreID,
			&i.Lavorazione,
			&i.Codici,
			&i.MessaggioID,
			&i.Stato,
			&i.InviataIl,
			&i.OffertaRicevutaIl,
			&i.Note,
			&i.CreataDa,
			&i.CreataIl,
			&i.DeclinataIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riproponiAllegatiComeOffertaFornitore = `-- name: RiproponiAllegatiComeOffertaFornitore :execrows
UPDATE documento_proposta p SET tipo_proposto = 'offerta_fornitore'
FROM allegato a
WHERE p.allegato_id = a.allegato_id AND a.messaggio_id = $1 AND p.stato = 'aperta' AND a.natura = 'file'
  AND lower(a.estensione) IN ('pdf', 'xls', 'xlsx', 'doc', 'docx')
`

// Alla conferma «e' la risposta del fornitore» le proposte ancora aperte sui suoi allegati (file, non
// inline) diventano `offerta_fornitore`: e' il tipo che le porta in OFFERTE FORNITORI della RFQ cliente.
// Solo le proposte APERTE: una gia' confermata e' una decisione.
func (q *Queries) RiproponiAllegatiComeOffertaFornitore(ctx context.Context, messaggioID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, riproponiAllegatiComeOffertaFornitore, messaggioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAttoTriage = `-- name: SetAttoTriage :execrows
UPDATE proposta_triage SET atto = $2, legame = $3, richiesta_proposta = $4, fornitore_proposto = $5
WHERE messaggio_id = $1 AND fonte = 'deterministico' AND stato = 'proposta'
`

type SetAttoTriageParams struct {
	MessaggioID       uuid.UUID           `json:"messaggio_id"`
	Atto              pgtype.Text         `json:"atto"`
	Legame            NullLegameOperativo `json:"legame"`
	RichiestaProposta uuid.NullUUID       `json:"richiesta_proposta"`
	FornitoreProposto uuid.NullUUID       `json:"fornitore_proposto"`
}

func (q *Queries) SetAttoTriage(ctx context.Context, arg SetAttoTriageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAttoTriage,
		arg.MessaggioID,
		arg.Atto,
		arg.Legame,
		arg.RichiestaProposta,
		arg.FornitoreProposto,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBozzaInviata = `-- name: SetBozzaInviata :execrows
UPDATE bozza SET stato = 'inviata', inviata_messaggio_id = $2 WHERE bozza_id = $1 AND inviata_messaggio_id IS NULL
`

type SetBozzaInviataParams struct {
	BozzaID            uuid.UUID     `json:"bozza_id"`
	InviataMessaggioID uuid.NullUUID `json:"inviata_messaggio_id"`
}

// Il marcatore CockpitBozza sulla mail in Posta inviata chiude il cerchio: la bozza e' partita.
func (q *Queries) SetBozzaInviata(ctx context.Context, arg SetBozzaInviataParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBozzaInviata, arg.BozzaID, arg.InviataMessaggioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRichiestaDeclinata = `-- name: SetRichiestaDeclinata :execrows
UPDATE richiesta_fornitore SET stato = 'declinata', declinata_il = COALESCE(declinata_il, $2)
WHERE richiesta_id = $1 AND stato = 'inviata'
`

type SetRichiestaDeclinataParams struct {
	RichiestaID uuid.UUID  `json:"richiesta_id"`
	DeclinataIl *time.Time `json:"declinata_il"`
}

// «Non quotiamo»: la richiesta e' chiusa senza offerta.
func (q *Queries) SetRichiestaDeclinata(ctx context.Context, arg SetRichiestaDeclinataParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRichiestaDeclinata, arg.RichiestaID, arg.DeclinataIl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRichiestaInviata = `-- name: SetRichiestaInviata :execrows
UPDATE richiesta_fornitore SET messaggio_id = $2, stato = 'inviata', inviata_il = $3
WHERE richiesta_id = $1 AND messaggio_id IS NULL AND stato IN ('bozza', 'inviata')
`

type SetRichiestaInviataParams struct {
	RichiestaID uuid.UUID     `json:"richiesta_id"`
	MessaggioID uuid.NullUUID `json:"messaggio_id"`
	InviataIl   *time.Time    `json:"inviata_il"`
}

// La nostra mail e' nota: dal marcatore (sync della Posta inviata) o dalla conferma a mano. Non
// si sovrascrive una richiesta che ha gia' la sua mail.
func (q *Queries) SetRichiestaInviata(ctx context.Context, arg SetRichiestaInviataParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRichiestaInviata, arg.RichiestaID, arg.MessaggioID, arg.InviataIl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRichiestaOffertaRicevuta = `-- name: SetRichiestaOffertaRicevuta :execrows
UPDATE richiesta_fornitore SET stato = 'offerta_ricevuta', offerta_ricevuta_il = COALESCE(offerta_ricevuta_il, $2)
WHERE richiesta_id = $1 AND stato IN ('inviata', 'offerta_ricevuta')
`

type SetRichiestaOffertaRicevutaParams struct {
	RichiestaID       uuid.UUID  `json:"richiesta_id"`
	OffertaRicevutaIl *time.Time `json:"offerta_ricevuta_il"`
}

// Solo con la conferma di un atto `offerta` (7C.0): una mail collegata alla richiesta, da sola,
// non cambia lo stato.
func (q *Queries) SetRichiestaOffertaRicevuta(ctx context.Context, arg SetRichiestaOffertaRicevutaParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRichiestaOffertaRicevuta, arg.RichiestaID, arg.OffertaRicevutaIl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRichiestaStato = `-- name: SetRichiestaStato :execrows
UPDATE richiesta_fornitore SET stato = $2 WHERE richiesta_id = $1 AND thread_id = $3
`

type SetRichiestaStatoParams struct {
	RichiestaID uuid.UUID               `json:"richiesta_id"`
	Stato       StatoRichiestaFornitore `json:"stato"`
	ThreadID    uuid.UUID               `json:"thread_id"`
}

func (q *Queries) SetRichiestaStato(ctx context.Context, arg SetRichiestaStatoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRichiestaStato, arg.RichiestaID, arg.Stato, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const threadApertePerCodici = `-- name: ThreadApertePerCodici :many
SELECT DISTINCT t.thread_id, t.oggetto, t.cartella_relativa, c.cartella_nas AS cliente, i.codice
FROM identificativo_thread i
JOIN thread_offerta t ON t.thread_id = i.thread_id
JOIN cliente c ON c.cliente_id = t.cliente_id
WHERE t.stato = 'APERTA' AND t.unito_in IS NULL AND upper(i.codice) = ANY($1::text[])
LIMIT 20
`

type ThreadApertePerCodiciRow struct {
	ThreadID         uuid.UUID   `json:"thread_id"`
	Oggetto          pgtype.Text `json:"oggetto"`
	CartellaRelativa pgtype.Text `json:"cartella_relativa"`
	Cliente          string      `json:"cliente"`
	Codice           string      `json:"codice"`
}

// RF_oggetto: una nostra mail a un fornitore che cita un codice di una RFQ aperta (di qualunque
// cliente): la richiesta mandata a mano.
func (q *Queries) ThreadApertePerCodici(ctx context.Context, codici []string) ([]ThreadApertePerCodiciRow, error) {
	rows, err := q.db.Query(ctx, threadApertePerCodici, codici)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadApertePerCodiciRow{}
	for rows.Next() {
		var i ThreadApertePerCodiciRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Oggetto,
			&i.CartellaRelativa,
			&i.Cliente,
			&i.Codice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
