// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: utenti.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const creaSessione = `-- name: CreaSessione :one
INSERT INTO sessione (token, utente_id, scade_il) VALUES ($1, $2, $3) RETURNING token, utente_id, creata_il, scade_il, ultimo_accesso, postazione_id, postazione_origine
`

type CreaSessioneParams struct {
	Token    string    `json:"token"`
	UtenteID uuid.UUID `json:"utente_id"`
	ScadeIl  time.Time `json:"scade_il"`
}

func (q *Queries) CreaSessione(ctx context.Context, arg CreaSessioneParams) (Sessione, error) {
	row := q.db.QueryRow(ctx, creaSessione, arg.Token, arg.UtenteID, arg.ScadeIl)
	var i Sessione
	err := row.Scan(
		&i.Token,
		&i.UtenteID,
		&i.CreataIl,
		&i.ScadeIl,
		&i.UltimoAccesso,
		&i.PostazioneID,
		&i.PostazioneOrigine,
	)
	return i, err
}

const creaSessioneConPostazione = `-- name: CreaSessioneConPostazione :one
INSERT INTO sessione (token, utente_id, scade_il, postazione_id, postazione_origine)
VALUES ($1, $2, $3, $4, $5) RETURNING token, utente_id, creata_il, scade_il, ultimo_accesso, postazione_id, postazione_origine
`

type CreaSessioneConPostazioneParams struct {
	Token             string        `json:"token"`
	UtenteID          uuid.UUID     `json:"utente_id"`
	ScadeIl           time.Time     `json:"scade_il"`
	PostazioneID      uuid.NullUUID `json:"postazione_id"`
	PostazioneOrigine pgtype.Text   `json:"postazione_origine"`
}

func (q *Queries) CreaSessioneConPostazione(ctx context.Context, arg CreaSessioneConPostazioneParams) (Sessione, error) {
	row := q.db.QueryRow(ctx, creaSessioneConPostazione,
		arg.Token,
		arg.UtenteID,
		arg.ScadeIl,
		arg.PostazioneID,
		arg.PostazioneOrigine,
	)
	var i Sessione
	err := row.Scan(
		&i.Token,
		&i.UtenteID,
		&i.CreataIl,
		&i.ScadeIl,
		&i.UltimoAccesso,
		&i.PostazioneID,
		&i.PostazioneOrigine,
	)
	return i, err
}

const eliminaSessione = `-- name: EliminaSessione :exec
DELETE FROM sessione WHERE token = $1
`

func (q *Queries) EliminaSessione(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, eliminaSessione, token)
	return err
}

const eliminaSessioniScadute = `-- name: EliminaSessioniScadute :execrows
DELETE FROM sessione WHERE scade_il < now()
`

func (q *Queries) EliminaSessioniScadute(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaSessioniScadute)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessione = `-- name: GetSessione :one
SELECT s.postazione_id, s.postazione_origine, p.nome_host, u.utente_id, u.sigla, u.nome, u.ufficio, u.ruolo, u.password_hash, u.attivo, u.creato_il, u.ultima_vista_inbox
FROM sessione s
JOIN utente u ON u.utente_id = s.utente_id
LEFT JOIN postazione p ON p.postazione_id = s.postazione_id
WHERE s.token = $1 AND s.scade_il > now() AND u.attivo
`

type GetSessioneRow struct {
	PostazioneID      uuid.NullUUID `json:"postazione_id"`
	PostazioneOrigine pgtype.Text   `json:"postazione_origine"`
	NomeHost          pgtype.Text   `json:"nome_host"`
	Utente            Utente        `json:"utente"`
}

// Utente E postazione della sessione (voce 2.7): la postazione decide dove vanno i job interattivi.
func (q *Queries) GetSessione(ctx context.Context, token string) (GetSessioneRow, error) {
	row := q.db.QueryRow(ctx, getSessione, token)
	var i GetSessioneRow
	err := row.Scan(
		&i.PostazioneID,
		&i.PostazioneOrigine,
		&i.NomeHost,
		&i.Utente.UtenteID,
		&i.Utente.Sigla,
		&i.Utente.Nome,
		&i.Utente.Ufficio,
		&i.Utente.Ruolo,
		&i.Utente.PasswordHash,
		&i.Utente.Attivo,
		&i.Utente.CreatoIl,
		&i.Utente.UltimaVistaInbox,
	)
	return i, err
}

const getSessioneUtente = `-- name: GetSessioneUtente :one
SELECT u.utente_id, u.sigla, u.nome, u.ufficio, u.ruolo, u.password_hash, u.attivo, u.creato_il, u.ultima_vista_inbox FROM sessione s JOIN utente u ON u.utente_id = s.utente_id
WHERE s.token = $1 AND s.scade_il > now() AND u.attivo
`

func (q *Queries) GetSessioneUtente(ctx context.Context, token string) (Utente, error) {
	row := q.db.QueryRow(ctx, getSessioneUtente, token)
	var i Utente
	err := row.Scan(
		&i.UtenteID,
		&i.Sigla,
		&i.Nome,
		&i.Ufficio,
		&i.Ruolo,
		&i.PasswordHash,
		&i.Attivo,
		&i.CreatoIl,
		&i.UltimaVistaInbox,
	)
	return i, err
}

const getUtente = `-- name: GetUtente :one
SELECT utente_id, sigla, nome, ufficio, ruolo, password_hash, attivo, creato_il, ultima_vista_inbox FROM utente WHERE utente_id = $1
`

func (q *Queries) GetUtente(ctx context.Context, utenteID uuid.UUID) (Utente, error) {
	row := q.db.QueryRow(ctx, getUtente, utenteID)
	var i Utente
	err := row.Scan(
		&i.UtenteID,
		&i.Sigla,
		&i.Nome,
		&i.Ufficio,
		&i.Ruolo,
		&i.PasswordHash,
		&i.Attivo,
		&i.CreatoIl,
		&i.UltimaVistaInbox,
	)
	return i, err
}

const getUtentePerSigla = `-- name: GetUtentePerSigla :one
SELECT utente_id, sigla, nome, ufficio, ruolo, password_hash, attivo, creato_il, ultima_vista_inbox FROM utente WHERE sigla = $1 AND attivo
`

func (q *Queries) GetUtentePerSigla(ctx context.Context, sigla string) (Utente, error) {
	row := q.db.QueryRow(ctx, getUtentePerSigla, sigla)
	var i Utente
	err := row.Scan(
		&i.UtenteID,
		&i.Sigla,
		&i.Nome,
		&i.Ufficio,
		&i.Ruolo,
		&i.PasswordHash,
		&i.Attivo,
		&i.CreatoIl,
		&i.UltimaVistaInbox,
	)
	return i, err
}

const listUtenti = `-- name: ListUtenti :many
SELECT utente_id, sigla, nome, ufficio, ruolo, password_hash, attivo, creato_il, ultima_vista_inbox FROM utente ORDER BY sigla
`

func (q *Queries) ListUtenti(ctx context.Context) ([]Utente, error) {
	rows, err := q.db.Query(ctx, listUtenti)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Utente{}
	for rows.Next() {
		var i Utente
		if err := rows.Scan(
			&i.UtenteID,
			&i.Sigla,
			&i.Nome,
			&i.Ufficio,
			&i.Ruolo,
			&i.PasswordHash,
			&i.Attivo,
			&i.CreatoIl,
			&i.UltimaVistaInbox,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionePostazione = `-- name: SetSessionePostazione :exec
UPDATE sessione SET postazione_id = $1, postazione_origine = $2
WHERE token = $3
`

type SetSessionePostazioneParams struct {
	PostazioneID      uuid.NullUUID `json:"postazione_id"`
	PostazioneOrigine pgtype.Text   `json:"postazione_origine"`
	Token             string        `json:"token"`
}

// La scelta esplicita dell'operatore ('scelta') o la rimozione (NULL, NULL). Chi chiama ha già
// verificato che l'utente sia abilitato a quella postazione (P1).
func (q *Queries) SetSessionePostazione(ctx context.Context, arg SetSessionePostazioneParams) error {
	_, err := q.db.Exec(ctx, setSessionePostazione, arg.PostazioneID, arg.PostazioneOrigine, arg.Token)
	return err
}

const toccaSessione = `-- name: ToccaSessione :exec
UPDATE sessione SET ultimo_accesso = now() WHERE token = $1
`

func (q *Queries) ToccaSessione(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, toccaSessione, token)
	return err
}

const upsertUtente = `-- name: UpsertUtente :one
INSERT INTO utente (sigla, nome, ufficio, ruolo, password_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (sigla) DO UPDATE SET nome = EXCLUDED.nome, ufficio = EXCLUDED.ufficio, ruolo = EXCLUDED.ruolo,
    password_hash = COALESCE(EXCLUDED.password_hash, utente.password_hash), attivo = true
RETURNING utente_id, sigla, nome, ufficio, ruolo, password_hash, attivo, creato_il, ultima_vista_inbox
`

type UpsertUtenteParams struct {
	Sigla        string      `json:"sigla"`
	Nome         string      `json:"nome"`
	Ufficio      string      `json:"ufficio"`
	Ruolo        RuoloUtente `json:"ruolo"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpsertUtente(ctx context.Context, arg UpsertUtenteParams) (Utente, error) {
	row := q.db.QueryRow(ctx, upsertUtente,
		arg.Sigla,
		arg.Nome,
		arg.Ufficio,
		arg.Ruolo,
		arg.PasswordHash,
	)
	var i Utente
	err := row.Scan(
		&i.UtenteID,
		&i.Sigla,
		&i.Nome,
		&i.Ufficio,
		&i.Ruolo,
		&i.PasswordHash,
		&i.Attivo,
		&i.CreatoIl,
		&i.UltimaVistaInbox,
	)
	return i, err
}
