// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aggancio.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggiornaTriageCandidato = `-- name: AggiornaTriageCandidato :execrows
UPDATE proposta_triage
SET esito = 'aggancia', thread_proposto = $2, confidenza = $3,
    motivi = motivi || $4::jsonb
WHERE messaggio_id = $1 AND fonte = 'deterministico' AND stato = 'proposta'
`

type AggiornaTriageCandidatoParams struct {
	MessaggioID    uuid.UUID       `json:"messaggio_id"`
	ThreadProposto uuid.NullUUID   `json:"thread_proposto"`
	Confidenza     int16           `json:"confidenza"`
	Motivo         json.RawMessage `json:"motivo"`
}

// AggiornaTriageCandidato: la proposta di un messaggio cambia quando compare un'evidenza nuova (per
// esempio: un operatore aggancia un messaggio, e gli altri orfani della stessa conversazione acquistano
// un candidato R1). Cambia la PROPOSTA, non la decisione: tocca solo le righe ancora `proposta`.
func (q *Queries) AggiornaTriageCandidato(ctx context.Context, arg AggiornaTriageCandidatoParams) (int64, error) {
	result, err := q.db.Exec(ctx, aggiornaTriageCandidato,
		arg.MessaggioID,
		arg.ThreadProposto,
		arg.Confidenza,
		arg.Motivo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contaCandidatiAggancio = `-- name: ContaCandidatiAggancio :one
SELECT count(*) FROM candidato_aggancio WHERE messaggio_id = $1
`

func (q *Queries) ContaCandidatiAggancio(ctx context.Context, messaggioID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contaCandidatiAggancio, messaggioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eliminaCandidatiAggancio = `-- name: EliminaCandidatiAggancio :execrows
DELETE FROM candidato_aggancio WHERE messaggio_id = $1
`

func (q *Queries) EliminaCandidatiAggancio(ctx context.Context, messaggioID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaCandidatiAggancio, messaggioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eliminaCandidatiCodice = `-- name: EliminaCandidatiCodice :execrows
DELETE FROM candidato_codice WHERE messaggio_id = $1
`

func (q *Queries) EliminaCandidatiCodice(ctx context.Context, messaggioID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaCandidatiCodice, messaggioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCandidatoAggancio = `-- name: InsertCandidatoAggancio :exec

INSERT INTO candidato_aggancio (messaggio_id, thread_id, regola, punteggio, evidenza, thread_stato)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (messaggio_id, thread_id, regola) DO UPDATE
    SET punteggio = EXCLUDED.punteggio, evidenza = EXCLUDED.evidenza, thread_stato = EXCLUDED.thread_stato
`

type InsertCandidatoAggancioParams struct {
	MessaggioID uuid.UUID      `json:"messaggio_id"`
	ThreadID    uuid.UUID      `json:"thread_id"`
	Regola      RegolaAggancio `json:"regola"`
	Punteggio   int16          `json:"punteggio"`
	Evidenza    string         `json:"evidenza"`
	ThreadStato StatoThread    `json:"thread_stato"`
}

// Candidati di aggancio e di codice (checkpoint 3R, fase 4.1).
// Nessuna di queste query scrive `messaggio.thread_id`: quello lo fa solo una decisione dell'operatore.
func (q *Queries) InsertCandidatoAggancio(ctx context.Context, arg InsertCandidatoAggancioParams) error {
	_, err := q.db.Exec(ctx, insertCandidatoAggancio,
		arg.MessaggioID,
		arg.ThreadID,
		arg.Regola,
		arg.Punteggio,
		arg.Evidenza,
		arg.ThreadStato,
	)
	return err
}

const insertCandidatoCodice = `-- name: InsertCandidatoCodice :exec
INSERT INTO candidato_codice (messaggio_id, codice, ruolo, rev, origine, famiglia, punteggio, evidenza)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (messaggio_id, codice) DO UPDATE
    SET ruolo = EXCLUDED.ruolo, rev = EXCLUDED.rev, origine = EXCLUDED.origine,
        famiglia = EXCLUDED.famiglia, punteggio = EXCLUDED.punteggio, evidenza = EXCLUDED.evidenza
`

type InsertCandidatoCodiceParams struct {
	MessaggioID uuid.UUID     `json:"messaggio_id"`
	Codice      string        `json:"codice"`
	Ruolo       RuoloCodice   `json:"ruolo"`
	Rev         string        `json:"rev"`
	Origine     OrigineCodice `json:"origine"`
	Famiglia    string        `json:"famiglia"`
	Punteggio   int16         `json:"punteggio"`
	Evidenza    string        `json:"evidenza"`
}

func (q *Queries) InsertCandidatoCodice(ctx context.Context, arg InsertCandidatoCodiceParams) error {
	_, err := q.db.Exec(ctx, insertCandidatoCodice,
		arg.MessaggioID,
		arg.Codice,
		arg.Ruolo,
		arg.Rev,
		arg.Origine,
		arg.Famiglia,
		arg.Punteggio,
		arg.Evidenza,
	)
	return err
}

const listCandidatiAggancio = `-- name: ListCandidatiAggancio :many
SELECT k.messaggio_id, k.thread_id, k.regola, k.punteggio, k.evidenza, k.thread_stato,
       t.oggetto, t.data_inizio, t.riferimento_cliente, c.ragione_sociale AS cliente
FROM candidato_aggancio k
JOIN thread_offerta t ON t.thread_id = k.thread_id
JOIN cliente c        ON c.cliente_id = t.cliente_id
WHERE k.messaggio_id = $1
ORDER BY k.punteggio DESC, k.regola
`

type ListCandidatiAggancioRow struct {
	MessaggioID        uuid.UUID      `json:"messaggio_id"`
	ThreadID           uuid.UUID      `json:"thread_id"`
	Regola             RegolaAggancio `json:"regola"`
	Punteggio          int16          `json:"punteggio"`
	Evidenza           string         `json:"evidenza"`
	ThreadStato        StatoThread    `json:"thread_stato"`
	Oggetto            pgtype.Text    `json:"oggetto"`
	DataInizio         time.Time      `json:"data_inizio"`
	RiferimentoCliente pgtype.Text    `json:"riferimento_cliente"`
	Cliente            string         `json:"cliente"`
}

// ListCandidatiAggancio: tutti i candidati di un messaggio, i piu' forti in cima. TUTTI, non il primo:
// scegliere per l'operatore e' esattamente cio' che questo checkpoint toglie (T16).
func (q *Queries) ListCandidatiAggancio(ctx context.Context, messaggioID uuid.UUID) ([]ListCandidatiAggancioRow, error) {
	rows, err := q.db.Query(ctx, listCandidatiAggancio, messaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidatiAggancioRow{}
	for rows.Next() {
		var i ListCandidatiAggancioRow
		if err := rows.Scan(
			&i.MessaggioID,
			&i.ThreadID,
			&i.Regola,
			&i.Punteggio,
			&i.Evidenza,
			&i.ThreadStato,
			&i.Oggetto,
			&i.DataInizio,
			&i.RiferimentoCliente,
			&i.Cliente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidatiCodice = `-- name: ListCandidatiCodice :many
SELECT messaggio_id, codice, ruolo, rev, origine, famiglia, punteggio, evidenza, creato_il FROM candidato_codice WHERE messaggio_id = $1
ORDER BY array_position(ARRAY['riferimento_rfq','prodotto','parte','non_classificato']::ruolo_codice[], ruolo),
         punteggio DESC, codice
`

func (q *Queries) ListCandidatiCodice(ctx context.Context, messaggioID uuid.UUID) ([]CandidatoCodice, error) {
	rows, err := q.db.Query(ctx, listCandidatiCodice, messaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CandidatoCodice{}
	for rows.Next() {
		var i CandidatoCodice
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Codice,
			&i.Ruolo,
			&i.Rev,
			&i.Origine,
			&i.Famiglia,
			&i.Punteggio,
			&i.Evidenza,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrfaniConversazione = `-- name: ListOrfaniConversazione :many
SELECT messaggio_id FROM messaggio
WHERE conversazione_id = $1 AND thread_id IS NULL AND messaggio_id <> $2
ORDER BY data_evento
`

type ListOrfaniConversazioneParams struct {
	ConversazioneID uuid.UUID `json:"conversazione_id"`
	MessaggioID     uuid.UUID `json:"messaggio_id"`
}

// ListOrfaniConversazione: gli altri messaggi orfani della stessa conversazione. Prima venivano
// AGGANCIATI in blocco; adesso si leggono per proporli, uno per uno, con il loro candidato (T21).
func (q *Queries) ListOrfaniConversazione(ctx context.Context, arg ListOrfaniConversazioneParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrfaniConversazione, arg.ConversazioneID, arg.MessaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var messaggio_id uuid.UUID
		if err := rows.Scan(&messaggio_id); err != nil {
			return nil, err
		}
		items = append(items, messaggio_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRiferimentoCliente = `-- name: SetRiferimentoCliente :exec
UPDATE thread_offerta SET riferimento_cliente = $2 WHERE thread_id = $1
`

type SetRiferimentoClienteParams struct {
	ThreadID    uuid.UUID   `json:"thread_id"`
	Riferimento pgtype.Text `json:"riferimento"`
}

func (q *Queries) SetRiferimentoCliente(ctx context.Context, arg SetRiferimentoClienteParams) error {
	_, err := q.db.Exec(ctx, setRiferimentoCliente, arg.ThreadID, arg.Riferimento)
	return err
}

const threadDellaConversazioneConStato = `-- name: ThreadDellaConversazioneConStato :one
SELECT c.thread_id, t.stato
FROM conversazione c JOIN thread_offerta t ON t.thread_id = c.thread_id
WHERE c.conversazione_id = $1 AND c.thread_id IS NOT NULL
`

type ThreadDellaConversazioneConStatoRow struct {
	ThreadID uuid.NullUUID `json:"thread_id"`
	Stato    StatoThread   `json:"stato"`
}

// R1: la conversazione, se un operatore l'ha gia' collegata a una RFQ.
func (q *Queries) ThreadDellaConversazioneConStato(ctx context.Context, conversazioneID uuid.UUID) (ThreadDellaConversazioneConStatoRow, error) {
	row := q.db.QueryRow(ctx, threadDellaConversazioneConStato, conversazioneID)
	var i ThreadDellaConversazioneConStatoRow
	err := row.Scan(&i.ThreadID, &i.Stato)
	return i, err
}

const threadPerChiaviCitate = `-- name: ThreadPerChiaviCitate :many

SELECT DISTINCT m.thread_id, m.chiave_esterna, t.stato
FROM messaggio m
JOIN thread_offerta t ON t.thread_id = m.thread_id
WHERE m.canale = 'outlook' AND m.chiave_esterna = ANY($1::text[]) AND m.thread_id IS NOT NULL
`

type ThreadPerChiaviCitateRow struct {
	ThreadID      uuid.NullUUID `json:"thread_id"`
	ChiaveEsterna string        `json:"chiave_esterna"`
	Stato         StatoThread   `json:"stato"`
}

// ---------------------------------------------------------------- le sorgenti delle regole R0–R5
// R0: i Message-ID citati da In-Reply-To e References, risolti su messaggi GIA' agganciati.
// Il canale sta nella condizione perche' l'indice unico e' (canale, chiave_esterna): senza, ogni
// messaggio con delle References scorreva tutta la tabella dei messaggi.
func (q *Queries) ThreadPerChiaviCitate(ctx context.Context, chiavi []string) ([]ThreadPerChiaviCitateRow, error) {
	rows, err := q.db.Query(ctx, threadPerChiaviCitate, chiavi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadPerChiaviCitateRow{}
	for rows.Next() {
		var i ThreadPerChiaviCitateRow
		if err := rows.Scan(&i.ThreadID, &i.ChiaveEsterna, &i.Stato); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadPerCodiciCliente = `-- name: ThreadPerCodiciCliente :many
SELECT DISTINCT t.thread_id, t.stato, t.data_inizio, i.codice
FROM identificativo_thread i
JOIN thread_offerta t ON t.thread_id = i.thread_id
WHERE t.cliente_id = $1 AND t.unito_in IS NULL
  AND upper(i.codice) = ANY($2::text[])
  AND t.data_inizio >= $3::timestamptz
ORDER BY t.data_inizio DESC
LIMIT 10
`

type ThreadPerCodiciClienteParams struct {
	ClienteID uuid.UUID `json:"cliente_id"`
	Codici    []string  `json:"codici"`
	Dal       time.Time `json:"dal"`
}

type ThreadPerCodiciClienteRow struct {
	ThreadID   uuid.UUID   `json:"thread_id"`
	Stato      StatoThread `json:"stato"`
	DataInizio time.Time   `json:"data_inizio"`
	Codice     string      `json:"codice"`
}

// R3: un codice gia' identificativo di una RFQ dello stesso cliente. Solo dello stesso cliente: due
// clienti diversi usano gli stessi numeri e non vuol dire niente (T4).
func (q *Queries) ThreadPerCodiciCliente(ctx context.Context, arg ThreadPerCodiciClienteParams) ([]ThreadPerCodiciClienteRow, error) {
	rows, err := q.db.Query(ctx, threadPerCodiciCliente, arg.ClienteID, arg.Codici, arg.Dal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadPerCodiciClienteRow{}
	for rows.Next() {
		var i ThreadPerCodiciClienteRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Stato,
			&i.DataInizio,
			&i.Codice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadPerOggettoCliente = `-- name: ThreadPerOggettoCliente :many
SELECT t.thread_id, t.stato, t.oggetto, t.data_inizio
FROM thread_offerta t
WHERE t.cliente_id = $1 AND t.unito_in IS NULL
  AND upper(t.oggetto) = upper($2::text)
  AND t.data_inizio >= $3::timestamptz
ORDER BY t.data_inizio DESC
LIMIT 5
`

type ThreadPerOggettoClienteParams struct {
	ClienteID uuid.UUID `json:"cliente_id"`
	Oggetto   string    `json:"oggetto"`
	Dal       time.Time `json:"dal"`
}

type ThreadPerOggettoClienteRow struct {
	ThreadID   uuid.UUID   `json:"thread_id"`
	Stato      StatoThread `json:"stato"`
	Oggetto    pgtype.Text `json:"oggetto"`
	DataInizio time.Time   `json:"data_inizio"`
}

// R2: stesso oggetto (gia' normalizzato: `thread_offerta.oggetto` e' l'oggetto pulito), stesso cliente,
// dentro la finestra. Senza finestra, «Richiesta offerta» aggancerebbe richieste di quattro anni fa (T3).
func (q *Queries) ThreadPerOggettoCliente(ctx context.Context, arg ThreadPerOggettoClienteParams) ([]ThreadPerOggettoClienteRow, error) {
	rows, err := q.db.Query(ctx, threadPerOggettoCliente, arg.ClienteID, arg.Oggetto, arg.Dal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadPerOggettoClienteRow{}
	for rows.Next() {
		var i ThreadPerOggettoClienteRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Stato,
			&i.Oggetto,
			&i.DataInizio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadPerRiferimentoCliente = `-- name: ThreadPerRiferimentoCliente :many
SELECT t.thread_id, t.stato, t.data_inizio, t.riferimento_cliente
FROM thread_offerta t
WHERE t.cliente_id = $1 AND t.unito_in IS NULL
  AND upper(t.riferimento_cliente) = upper($2::text)
ORDER BY t.data_inizio DESC
LIMIT 5
`

type ThreadPerRiferimentoClienteParams struct {
	ClienteID   uuid.UUID `json:"cliente_id"`
	Riferimento string    `json:"riferimento"`
}

type ThreadPerRiferimentoClienteRow struct {
	ThreadID           uuid.UUID   `json:"thread_id"`
	Stato              StatoThread `json:"stato"`
	DataInizio         time.Time   `json:"data_inizio"`
	RiferimentoCliente pgtype.Text `json:"riferimento_cliente"`
}

// R4: il riferimento con cui il cliente chiama la richiesta.
func (q *Queries) ThreadPerRiferimentoCliente(ctx context.Context, arg ThreadPerRiferimentoClienteParams) ([]ThreadPerRiferimentoClienteRow, error) {
	rows, err := q.db.Query(ctx, threadPerRiferimentoCliente, arg.ClienteID, arg.Riferimento)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadPerRiferimentoClienteRow{}
	for rows.Next() {
		var i ThreadPerRiferimentoClienteRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Stato,
			&i.DataInizio,
			&i.RiferimentoCliente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadRecentiBuyer = `-- name: ThreadRecentiBuyer :many
SELECT t.thread_id, t.stato, t.oggetto, t.data_inizio
FROM thread_offerta t
WHERE t.buyer_id = $1 AND t.unito_in IS NULL AND t.stato = 'APERTA'
  AND t.data_inizio >= $2::timestamptz
ORDER BY t.data_inizio DESC
LIMIT 5
`

type ThreadRecentiBuyerParams struct {
	BuyerID uuid.NullUUID `json:"buyer_id"`
	Dal     time.Time     `json:"dal"`
}

type ThreadRecentiBuyerRow struct {
	ThreadID   uuid.UUID   `json:"thread_id"`
	Stato      StatoThread `json:"stato"`
	Oggetto    pgtype.Text `json:"oggetto"`
	DataInizio time.Time   `json:"data_inizio"`
}

// R5: lo stesso buyer, di recente. Da sola non decide niente e non basta mai: mette in fila i candidati
// quando le regole forti non hanno parlato.
func (q *Queries) ThreadRecentiBuyer(ctx context.Context, arg ThreadRecentiBuyerParams) ([]ThreadRecentiBuyerRow, error) {
	rows, err := q.db.Query(ctx, threadRecentiBuyer, arg.BuyerID, arg.Dal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadRecentiBuyerRow{}
	for rows.Next() {
		var i ThreadRecentiBuyerRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Stato,
			&i.Oggetto,
			&i.DataInizio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
