// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotazioni.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const allegatoDelThread = `-- name: AllegatoDelThread :one
SELECT EXISTS (SELECT 1 FROM allegato a JOIN messaggio m ON m.messaggio_id = a.messaggio_id
                WHERE a.allegato_id = $1 AND m.thread_id = $2::uuid)::boolean AS del_thread
`

type AllegatoDelThreadParams struct {
	AllegatoID uuid.UUID `json:"allegato_id"`
	ThreadID   uuid.UUID `json:"thread_id"`
}

// Il file e' della RFQ: un allegato di un messaggio agganciato a lei.
func (q *Queries) AllegatoDelThread(ctx context.Context, arg AllegatoDelThreadParams) (bool, error) {
	row := q.db.QueryRow(ctx, allegatoDelThread, arg.AllegatoID, arg.ThreadID)
	var del_thread bool
	err := row.Scan(&del_thread)
	return del_thread, err
}

const deleteAnnotazione = `-- name: DeleteAnnotazione :execrows
DELETE FROM annotazione_pdf
 WHERE annotazione_id = $1 AND thread_id = $2 AND creata_da = $3
`

type DeleteAnnotazioneParams struct {
	AnnotazioneID uuid.UUID `json:"annotazione_id"`
	ThreadID      uuid.UUID `json:"thread_id"`
	UtenteID      uuid.UUID `json:"utente_id"`
}

// La toglie solo chi l'ha scritta.
func (q *Queries) DeleteAnnotazione(ctx context.Context, arg DeleteAnnotazioneParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnotazione, arg.AnnotazioneID, arg.ThreadID, arg.UtenteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAnnotazione = `-- name: InsertAnnotazione :one
INSERT INTO annotazione_pdf (thread_id, componente_id, allegato_id, pagina, x_norm, y_norm, testo, creata_da)
VALUES ($1, $2, $3, $4,
        round($5::float8::numeric, 6), round($6::float8::numeric, 6), $7, $8)
RETURNING annotazione_id
`

type InsertAnnotazioneParams struct {
	ThreadID     uuid.UUID     `json:"thread_id"`
	ComponenteID uuid.NullUUID `json:"componente_id"`
	AllegatoID   uuid.UUID     `json:"allegato_id"`
	Pagina       int32         `json:"pagina"`
	X            float64       `json:"x"`
	Y            float64       `json:"y"`
	Testo        string        `json:"testo"`
	CreataDa     uuid.UUID     `json:"creata_da"`
}

func (q *Queries) InsertAnnotazione(ctx context.Context, arg InsertAnnotazioneParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAnnotazione,
		arg.ThreadID,
		arg.ComponenteID,
		arg.AllegatoID,
		arg.Pagina,
		arg.X,
		arg.Y,
		arg.Testo,
		arg.CreataDa,
	)
	var annotazione_id uuid.UUID
	err := row.Scan(&annotazione_id)
	return annotazione_id, err
}

const listAnnotazioniThread = `-- name: ListAnnotazioniThread :many

SELECT n.annotazione_id, n.componente_id, n.allegato_id, a.sha256, n.pagina,
       n.x_norm::float8 AS x, n.y_norm::float8 AS y, n.testo,
       n.creata_da, u.sigla AS autore_sigla, u.nome AS autore_nome, n.creata_il, n.modificata_il,
       coalesce(c.codice, '')::text AS codice_componente
  FROM annotazione_pdf n
  JOIN allegato a ON a.allegato_id = n.allegato_id
  JOIN utente u ON u.utente_id = n.creata_da
  LEFT JOIN componente c ON c.componente_id = n.componente_id
 WHERE n.thread_id = $1
 ORDER BY n.creata_il, n.annotazione_id
`

type ListAnnotazioniThreadRow struct {
	AnnotazioneID    uuid.UUID     `json:"annotazione_id"`
	ComponenteID     uuid.NullUUID `json:"componente_id"`
	AllegatoID       uuid.UUID     `json:"allegato_id"`
	Sha256           pgtype.Text   `json:"sha256"`
	Pagina           int32         `json:"pagina"`
	X                float64       `json:"x"`
	Y                float64       `json:"y"`
	Testo            string        `json:"testo"`
	CreataDa         uuid.UUID     `json:"creata_da"`
	AutoreSigla      string        `json:"autore_sigla"`
	AutoreNome       string        `json:"autore_nome"`
	CreataIl         time.Time     `json:"creata_il"`
	ModificataIl     *time.Time    `json:"modificata_il"`
	CodiceComponente string        `json:"codice_componente"`
}

// Le note tecniche sui disegni (0021, Fascicolo v3): un punto di una pagina di un file, con il testo.
// Le coordinate stanno in numeric(7,6) nella tabella; qui si leggono e si scrivono come float8, perche'
// al Go serve un numero e non un pgtype.Numeric.
// Tutte le note della RFQ, con lo sha256 del file su cui sono state scritte (la schermata le mostra per
// contenuto), chi le ha scritte e il codice del componente che si stava guardando ("" = nessuno).
func (q *Queries) ListAnnotazioniThread(ctx context.Context, threadID uuid.UUID) ([]ListAnnotazioniThreadRow, error) {
	rows, err := q.db.Query(ctx, listAnnotazioniThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnotazioniThreadRow{}
	for rows.Next() {
		var i ListAnnotazioniThreadRow
		if err := rows.Scan(
			&i.AnnotazioneID,
			&i.ComponenteID,
			&i.AllegatoID,
			&i.Sha256,
			&i.Pagina,
			&i.X,
			&i.Y,
			&i.Testo,
			&i.CreataDa,
			&i.AutoreSigla,
			&i.AutoreNome,
			&i.CreataIl,
			&i.ModificataIl,
			&i.CodiceComponente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modificaAnnotazione = `-- name: ModificaAnnotazione :execrows
UPDATE annotazione_pdf SET testo = $1, modificata_da = $2::uuid, modificata_il = now()
 WHERE annotazione_id = $3 AND thread_id = $4 AND creata_da = $2
`

type ModificaAnnotazioneParams struct {
	Testo         string    `json:"testo"`
	UtenteID      uuid.UUID `json:"utente_id"`
	AnnotazioneID uuid.UUID `json:"annotazione_id"`
	ThreadID      uuid.UUID `json:"thread_id"`
}

// Il testo lo cambia solo chi l'ha scritta.
func (q *Queries) ModificaAnnotazione(ctx context.Context, arg ModificaAnnotazioneParams) (int64, error) {
	result, err := q.db.Exec(ctx, modificaAnnotazione,
		arg.Testo,
		arg.UtenteID,
		arg.AnnotazioneID,
		arg.ThreadID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
