// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bom.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const congelaBomVersione = `-- name: CongelaBomVersione :execrows
UPDATE bom_versione SET stato = 'congelata', congelata_da = $1, congelata_il = now()
WHERE bom_versione_id = $2 AND stato = 'bozza'
`

type CongelaBomVersioneParams struct {
	CongelataDa   uuid.NullUUID `json:"congelata_da"`
	BomVersioneID uuid.UUID     `json:"bom_versione_id"`
}

func (q *Queries) CongelaBomVersione(ctx context.Context, arg CongelaBomVersioneParams) (int64, error) {
	result, err := q.db.Exec(ctx, congelaBomVersione, arg.CongelataDa, arg.BomVersioneID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const diffBomWorking = `-- name: DiffBomWorking :many

SELECT 'componente'::text AS oggetto, coalesce(s.componente_id, w.componente_id)::text AS chiave,
       CASE WHEN s.componente_id IS NOT NULL THEN jsonb_build_object('codice', s.codice, 'rev', s.rev, 'tipo', s.tipo,
            'descrizione', s.descrizione, 'qta', s.qta, 'esito_fattibilita', s.esito_fattibilita,
            'note_fattibilita', s.note_fattibilita, 'step_strutturale_id', s.step_strutturale_id) END::jsonb AS prima,
       CASE WHEN w.componente_id IS NOT NULL THEN jsonb_build_object('codice', w.codice, 'rev', w.rev, 'tipo', w.tipo,
            'descrizione', w.descrizione, 'qta', w.qta, 'esito_fattibilita', w.esito_fattibilita,
            'note_fattibilita', w.note_fattibilita, 'step_strutturale_id', w.step_strutturale_id) END::jsonb AS dopo
  FROM (SELECT bom_versione_id, thread_id, componente_id, codice, rev, tipo, descrizione, qta, esito_fattibilita, note_fattibilita, step_strutturale_id, step_sha256, deroga_struttura_id FROM bom_versione_componente x WHERE x.bom_versione_id = $1) s
  FULL JOIN (SELECT componente_id, thread_id, codice, rev, descrizione, qta, tipo, origine, materiale_testo, spessore_mm, peso_kg, esito_fattibilita, note_fattibilita, confermato_da, creato_il, archiviato_il, archiviato_da, motivo_archiviazione, step_strutturale_id FROM componente y WHERE y.thread_id = $2 AND y.archiviato_il IS NULL) w
         ON w.componente_id = s.componente_id
UNION ALL
SELECT 'arco', coalesce(s.padre_id, w.padre_id)::text || '>' || coalesce(s.figlio_id, w.figlio_id)::text,
       CASE WHEN s.padre_id IS NOT NULL THEN jsonb_build_object('qta', s.qta, 'posizione', s.posizione) END,
       CASE WHEN w.padre_id IS NOT NULL THEN jsonb_build_object('qta', w.qta, 'posizione', w.posizione) END
  FROM (SELECT bom_versione_id, padre_id, figlio_id, qta, posizione FROM bom_versione_relazione x WHERE x.bom_versione_id = $1) s
  FULL JOIN (SELECT r.thread_id, r.padre_id, r.figlio_id, r.qta, r.posizione, r.origine, r.confermato_da, r.creato_il FROM componente_relazione r
               JOIN componente p ON p.componente_id = r.padre_id AND p.archiviato_il IS NULL
               JOIN componente f ON f.componente_id = r.figlio_id AND f.archiviato_il IS NULL
              WHERE r.thread_id = $2) w
         ON w.padre_id = s.padre_id AND w.figlio_id = s.figlio_id
UNION ALL
SELECT 'documento', coalesce(s.documento_id, w.documento_id)::text,
       CASE WHEN s.documento_id IS NOT NULL THEN jsonb_build_object('componente_id', s.componente_id, 'tipo', s.tipo, 'rev', s.rev, 'sha256', s.sha256) END,
       CASE WHEN w.documento_id IS NOT NULL THEN jsonb_build_object('componente_id', w.componente_id, 'tipo', w.tipo, 'rev', w.rev, 'sha256', w.sha256) END
  FROM (SELECT bom_versione_id, componente_id, documento_id, tipo, rev, sha256, path_al_congelamento FROM bom_versione_documento x WHERE x.bom_versione_id = $1) s
  FULL JOIN (SELECT d.documento_id, d.thread_id, d.componente_id, d.tipo, d.codice, d.rev, d.nome_file, d.estensione, d.sha256, d.bytes, d.path_relativo, d.stato_nas, d.errore_nas, d.scritto_il, d.confermato_da, d.confermato_il, d.sostituito_da, d.nota, d.verificato_il FROM documento d
               JOIN componente c ON c.componente_id = d.componente_id AND c.archiviato_il IS NULL
              WHERE d.thread_id = $2 AND d.sostituito_da IS NULL) w
         ON w.documento_id = s.documento_id
UNION ALL
SELECT 'deroga', coalesce(s.componente_id, w.componente_id)::text || ':' || coalesce(s.tipo, w.tipo)::text,
       CASE WHEN s.componente_id IS NOT NULL THEN jsonb_build_object('motivo', s.motivo) END,
       CASE WHEN w.componente_id IS NOT NULL THEN jsonb_build_object('motivo', w.motivo) END
  FROM (SELECT bom_versione_id, componente_id, deroga_id, tipo, motivo, utente_id, creata_il FROM bom_versione_deroga x WHERE x.bom_versione_id = $1) s
  FULL JOIN (SELECT g.deroga_id, g.thread_id, g.componente_id, g.tipo, g.motivo, g.utente_id, g.creata_il FROM deroga_fabbisogno g
               JOIN componente c ON c.componente_id = g.componente_id AND c.archiviato_il IS NULL
              WHERE g.thread_id = $2) w
         ON w.componente_id = s.componente_id AND w.tipo = s.tipo
UNION ALL
SELECT 'deroga_struttura', ds.deroga_struttura_id::text, NULL::jsonb,
       jsonb_build_object('componente_id', ds.componente_id, 'step_documento_id', ds.step_documento_id, 'motivo', ds.motivo)
  FROM deroga_struttura ds
  JOIN bom_versione v ON v.bom_versione_id = $1
 WHERE ds.thread_id = $2 AND ds.concessa_il > v.congelata_il
ORDER BY 1, 2
`

type DiffBomWorkingParams struct {
	BomVersioneID uuid.UUID `json:"bom_versione_id"`
	ThreadID      uuid.UUID `json:"thread_id"`
}

type DiffBomWorkingRow struct {
	Oggetto string          `json:"oggetto"`
	Chiave  string          `json:"chiave"`
	Prima   json.RawMessage `json:"prima"`
	Dopo    json.RawMessage `json:"dopo"`
}

// ------------------------------------------------------------------ differenza V(n) ↔ working (A4.7)
// Le coppie (istantanea, working) di ogni oggetto, con FULL JOIN: prima NULL = aggiunto, dopo NULL =
// tolto, tutte e due = da confrontare. Il confronto lo fa una funzione pura (fascicolo.Differenze),
// che si prova da sola. Conta solo quello che e' scritto: una deroga strutturale decaduta per una
// rianalisi non e' una differenza, una deroga strutturale nuova si'.
func (q *Queries) DiffBomWorking(ctx context.Context, arg DiffBomWorkingParams) ([]DiffBomWorkingRow, error) {
	rows, err := q.db.Query(ctx, diffBomWorking, arg.BomVersioneID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiffBomWorkingRow{}
	for rows.Next() {
		var i DiffBomWorkingRow
		if err := rows.Scan(
			&i.Oggetto,
			&i.Chiave,
			&i.Prima,
			&i.Dopo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eliminaBozza = `-- name: EliminaBozza :execrows
DELETE FROM bom_versione WHERE bom_versione_id = $1 AND stato = 'bozza'
`

func (q *Queries) EliminaBozza(ctx context.Context, bomVersioneID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaBozza, bomVersioneID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const gateCongelamento = `-- name: GateCongelamento :one

SELECT coalesce((SELECT b.n_bloccanti FROM v_thread_bloccanti b WHERE b.thread_id = $1), 0)::int AS n_bloccanti,
       (SELECT count(*) FROM componente_proposta p WHERE p.thread_id = $1 AND p.stato = 'aperta')::int AS n_proposte_componente,
       (SELECT count(*) FROM relazione_proposta p WHERE p.thread_id = $1 AND p.stato = 'aperta')::int AS n_proposte_relazione,
       (SELECT count(*) FROM rimozione_proposta p WHERE p.thread_id = $1 AND p.stato = 'aperta')::int AS n_proposte_rimozione,
       (SELECT count(*) FROM documento d
          JOIN componente c ON c.componente_id = d.componente_id AND c.archiviato_il IS NULL
         WHERE d.thread_id = $1 AND d.sostituito_da IS NULL AND d.stato_nas = 'errore')::int AS n_documenti_errore,
       (SELECT count(*) FROM nas_anomalia a
          JOIN documento d ON d.documento_id = a.documento_id
          JOIN componente c ON c.componente_id = d.componente_id AND c.archiviato_il IS NULL
         WHERE d.thread_id = $1 AND d.sostituito_da IS NULL AND a.risolta_il IS NULL)::int AS n_anomalie_nas
`

type GateCongelamentoRow struct {
	NBloccanti          int32 `json:"n_bloccanti"`
	NProposteComponente int32 `json:"n_proposte_componente"`
	NProposteRelazione  int32 `json:"n_proposte_relazione"`
	NProposteRimozione  int32 `json:"n_proposte_rimozione"`
	NDocumentiErrore    int32 `json:"n_documenti_errore"`
	NAnomalieNas        int32 `json:"n_anomalie_nas"`
}

// ------------------------------------------------------------------ il gate del congelamento (A4.6, passo 3)
// Una riga di conteggi per la RFQ. Lo STEP dei prodotti finiti e la struttura senza cicli si guardano
// a parte (ListGateStep, ListRelazioniAttive), perche' la regola sta in una funzione pura.
func (q *Queries) GateCongelamento(ctx context.Context, threadID uuid.UUID) (GateCongelamentoRow, error) {
	row := q.db.QueryRow(ctx, gateCongelamento, threadID)
	var i GateCongelamentoRow
	err := row.Scan(
		&i.NBloccanti,
		&i.NProposteComponente,
		&i.NProposteRelazione,
		&i.NProposteRimozione,
		&i.NDocumentiErrore,
		&i.NAnomalieNas,
	)
	return i, err
}

const getBomVersione = `-- name: GetBomVersione :one
SELECT bom_versione_id, thread_id, numero, stato, contesto, fase_all_apertura, fase_log_id_all_apertura, versione_precedente_id, numero_precedente, stato_precedente, motivo, creata_da, creata_il, congelata_da, congelata_il FROM bom_versione WHERE bom_versione_id = $1
`

func (q *Queries) GetBomVersione(ctx context.Context, bomVersioneID uuid.UUID) (BomVersione, error) {
	row := q.db.QueryRow(ctx, getBomVersione, bomVersioneID)
	var i BomVersione
	err := row.Scan(
		&i.BomVersioneID,
		&i.ThreadID,
		&i.Numero,
		&i.Stato,
		&i.Contesto,
		&i.FaseAllApertura,
		&i.FaseLogIDAllApertura,
		&i.VersionePrecedenteID,
		&i.NumeroPrecedente,
		&i.StatoPrecedente,
		&i.Motivo,
		&i.CreataDa,
		&i.CreataIl,
		&i.CongelataDa,
		&i.CongelataIl,
	)
	return i, err
}

const getBozzaAperta = `-- name: GetBozzaAperta :one
SELECT bom_versione_id, thread_id, numero, stato, contesto, fase_all_apertura, fase_log_id_all_apertura, versione_precedente_id, numero_precedente, stato_precedente, motivo, creata_da, creata_il, congelata_da, congelata_il FROM bom_versione WHERE thread_id = $1 AND stato = 'bozza'
`

func (q *Queries) GetBozzaAperta(ctx context.Context, threadID uuid.UUID) (BomVersione, error) {
	row := q.db.QueryRow(ctx, getBozzaAperta, threadID)
	var i BomVersione
	err := row.Scan(
		&i.BomVersioneID,
		&i.ThreadID,
		&i.Numero,
		&i.Stato,
		&i.Contesto,
		&i.FaseAllApertura,
		&i.FaseLogIDAllApertura,
		&i.VersionePrecedenteID,
		&i.NumeroPrecedente,
		&i.StatoPrecedente,
		&i.Motivo,
		&i.CreataDa,
		&i.CreataIl,
		&i.CongelataDa,
		&i.CongelataIl,
	)
	return i, err
}

const getUltimaCongelata = `-- name: GetUltimaCongelata :one
SELECT bom_versione_id, thread_id, numero, stato, contesto, fase_all_apertura, fase_log_id_all_apertura, versione_precedente_id, numero_precedente, stato_precedente, motivo, creata_da, creata_il, congelata_da, congelata_il FROM bom_versione WHERE thread_id = $1 AND stato = 'congelata' ORDER BY numero DESC LIMIT 1
`

func (q *Queries) GetUltimaCongelata(ctx context.Context, threadID uuid.UUID) (BomVersione, error) {
	row := q.db.QueryRow(ctx, getUltimaCongelata, threadID)
	var i BomVersione
	err := row.Scan(
		&i.BomVersioneID,
		&i.ThreadID,
		&i.Numero,
		&i.Stato,
		&i.Contesto,
		&i.FaseAllApertura,
		&i.FaseLogIDAllApertura,
		&i.VersionePrecedenteID,
		&i.NumeroPrecedente,
		&i.StatoPrecedente,
		&i.Motivo,
		&i.CreataDa,
		&i.CreataIl,
		&i.CongelataDa,
		&i.CongelataIl,
	)
	return i, err
}

const getUltimaVersione = `-- name: GetUltimaVersione :one
SELECT bom_versione_id, thread_id, numero, stato, contesto, fase_all_apertura, fase_log_id_all_apertura, versione_precedente_id, numero_precedente, stato_precedente, motivo, creata_da, creata_il, congelata_da, congelata_il FROM bom_versione WHERE thread_id = $1 ORDER BY numero DESC LIMIT 1
`

// L'ultima versione della RFQ, bozza o congelata. Per la catena la bozza, se c'e', e' sempre l'ultima.
func (q *Queries) GetUltimaVersione(ctx context.Context, threadID uuid.UUID) (BomVersione, error) {
	row := q.db.QueryRow(ctx, getUltimaVersione, threadID)
	var i BomVersione
	err := row.Scan(
		&i.BomVersioneID,
		&i.ThreadID,
		&i.Numero,
		&i.Stato,
		&i.Contesto,
		&i.FaseAllApertura,
		&i.FaseLogIDAllApertura,
		&i.VersionePrecedenteID,
		&i.NumeroPrecedente,
		&i.StatoPrecedente,
		&i.Motivo,
		&i.CreataDa,
		&i.CreataIl,
		&i.CongelataDa,
		&i.CongelataIl,
	)
	return i, err
}

const insertBomVersione = `-- name: InsertBomVersione :one

INSERT INTO bom_versione (thread_id, numero, contesto, fase_all_apertura, fase_log_id_all_apertura,
                          versione_precedente_id, numero_precedente, stato_precedente, motivo, creata_da)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10)
RETURNING bom_versione_id, thread_id, numero, stato, contesto, fase_all_apertura, fase_log_id_all_apertura, versione_precedente_id, numero_precedente, stato_precedente, motivo, creata_da, creata_il, congelata_da, congelata_il
`

type InsertBomVersioneParams struct {
	ThreadID             uuid.UUID     `json:"thread_id"`
	Numero               int32         `json:"numero"`
	Contesto             ContestoBom   `json:"contesto"`
	FaseAllApertura      Fase          `json:"fase_all_apertura"`
	FaseLogIDAllApertura uuid.UUID     `json:"fase_log_id_all_apertura"`
	VersionePrecedenteID uuid.NullUUID `json:"versione_precedente_id"`
	NumeroPrecedente     pgtype.Int4   `json:"numero_precedente"`
	StatoPrecedente      NullStatoBom  `json:"stato_precedente"`
	Motivo               string        `json:"motivo"`
	CreataDa             uuid.UUID     `json:"creata_da"`
}

// Versioni della BOM (Blocco 8, A4, B8.A4a): una baseline congelata e le sue istantanee (addendum
// A4.6, A4.7). Le versioni le scrive solo core/rfq/fascicolo (congelamento, apertura e abbandono di
// una revisione). Le regole che contano le tiene il database: una versione nasce bozza, congelata non
// cambia piu', la catena Vn → V(n-1) non ha salti, la working e' bloccata dopo il congelamento.
func (q *Queries) InsertBomVersione(ctx context.Context, arg InsertBomVersioneParams) (BomVersione, error) {
	row := q.db.QueryRow(ctx, insertBomVersione,
		arg.ThreadID,
		arg.Numero,
		arg.Contesto,
		arg.FaseAllApertura,
		arg.FaseLogIDAllApertura,
		arg.VersionePrecedenteID,
		arg.NumeroPrecedente,
		arg.StatoPrecedente,
		arg.Motivo,
		arg.CreataDa,
	)
	var i BomVersione
	err := row.Scan(
		&i.BomVersioneID,
		&i.ThreadID,
		&i.Numero,
		&i.Stato,
		&i.Contesto,
		&i.FaseAllApertura,
		&i.FaseLogIDAllApertura,
		&i.VersionePrecedenteID,
		&i.NumeroPrecedente,
		&i.StatoPrecedente,
		&i.Motivo,
		&i.CreataDa,
		&i.CreataIl,
		&i.CongelataDa,
		&i.CongelataIl,
	)
	return i, err
}

const listBomComponenti = `-- name: ListBomComponenti :many

SELECT bom_versione_id, thread_id, componente_id, codice, rev, tipo, descrizione, qta, esito_fattibilita, note_fattibilita, step_strutturale_id, step_sha256, deroga_struttura_id FROM bom_versione_componente WHERE bom_versione_id = $1 ORDER BY codice
`

// ------------------------------------------------------------------ una versione com'era (A4.7)
// Leggono solo le istantanee, mai le tabelle vive: Vn resta interrogabile esattamente com'era.
func (q *Queries) ListBomComponenti(ctx context.Context, bomVersioneID uuid.UUID) ([]BomVersioneComponente, error) {
	rows, err := q.db.Query(ctx, listBomComponenti, bomVersioneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BomVersioneComponente{}
	for rows.Next() {
		var i BomVersioneComponente
		if err := rows.Scan(
			&i.BomVersioneID,
			&i.ThreadID,
			&i.ComponenteID,
			&i.Codice,
			&i.Rev,
			&i.Tipo,
			&i.Descrizione,
			&i.Qta,
			&i.EsitoFattibilita,
			&i.NoteFattibilita,
			&i.StepStrutturaleID,
			&i.StepSha256,
			&i.DerogaStrutturaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBomDeroghe = `-- name: ListBomDeroghe :many
SELECT bom_versione_id, componente_id, deroga_id, tipo, motivo, utente_id, creata_il FROM bom_versione_deroga WHERE bom_versione_id = $1 ORDER BY componente_id, tipo
`

func (q *Queries) ListBomDeroghe(ctx context.Context, bomVersioneID uuid.UUID) ([]BomVersioneDeroga, error) {
	rows, err := q.db.Query(ctx, listBomDeroghe, bomVersioneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BomVersioneDeroga{}
	for rows.Next() {
		var i BomVersioneDeroga
		if err := rows.Scan(
			&i.BomVersioneID,
			&i.ComponenteID,
			&i.DerogaID,
			&i.Tipo,
			&i.Motivo,
			&i.UtenteID,
			&i.CreataIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBomDocumenti = `-- name: ListBomDocumenti :many
SELECT bom_versione_id, componente_id, documento_id, tipo, rev, sha256, path_al_congelamento FROM bom_versione_documento WHERE bom_versione_id = $1 ORDER BY componente_id, tipo, documento_id
`

func (q *Queries) ListBomDocumenti(ctx context.Context, bomVersioneID uuid.UUID) ([]BomVersioneDocumento, error) {
	rows, err := q.db.Query(ctx, listBomDocumenti, bomVersioneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BomVersioneDocumento{}
	for rows.Next() {
		var i BomVersioneDocumento
		if err := rows.Scan(
			&i.BomVersioneID,
			&i.ComponenteID,
			&i.DocumentoID,
			&i.Tipo,
			&i.Rev,
			&i.Sha256,
			&i.PathAlCongelamento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBomRelazioni = `-- name: ListBomRelazioni :many
SELECT bom_versione_id, padre_id, figlio_id, qta, posizione FROM bom_versione_relazione WHERE bom_versione_id = $1 ORDER BY padre_id, figlio_id
`

func (q *Queries) ListBomRelazioni(ctx context.Context, bomVersioneID uuid.UUID) ([]BomVersioneRelazione, error) {
	rows, err := q.db.Query(ctx, listBomRelazioni, bomVersioneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BomVersioneRelazione{}
	for rows.Next() {
		var i BomVersioneRelazione
		if err := rows.Scan(
			&i.BomVersioneID,
			&i.PadreID,
			&i.FiglioID,
			&i.Qta,
			&i.Posizione,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBomVersioni = `-- name: ListBomVersioni :many
SELECT thread_id, bom_versione_id, numero, stato, contesto, fase_all_apertura, fase_log_id_all_apertura, versione_precedente_id, motivo, creata_da, creata_il, congelata_da, congelata_il, superata, corrente FROM v_bom_versioni WHERE thread_id = $1 ORDER BY numero
`

func (q *Queries) ListBomVersioni(ctx context.Context, threadID uuid.UUID) ([]VBomVersioni, error) {
	rows, err := q.db.Query(ctx, listBomVersioni, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VBomVersioni{}
	for rows.Next() {
		var i VBomVersioni
		if err := rows.Scan(
			&i.ThreadID,
			&i.BomVersioneID,
			&i.Numero,
			&i.Stato,
			&i.Contesto,
			&i.FaseAllApertura,
			&i.FaseLogIDAllApertura,
			&i.VersionePrecedenteID,
			&i.Motivo,
			&i.CreataDa,
			&i.CreataIl,
			&i.CongelataDa,
			&i.CongelataIl,
			&i.Superata,
			&i.Corrente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGateStep = `-- name: ListGateStep :many
SELECT sp.thread_id, sp.componente_id, sp.codice, sp.step_strutturale_id, sp.n_step_correnti, sp.analisi_completa, sp.motivo_parziale, sp.deroga_struttura_id, sp.altro_3d_documento_id, sp.proposta_aperta, sp.atteso_da_portale, sp.esito,
       EXISTS (SELECT 1 FROM deroga_fabbisogno g WHERE g.componente_id = sp.componente_id AND g.tipo = 'cad_3d') AS deroga_cad
  FROM v_step_prodotto sp
 WHERE sp.thread_id = $1
 ORDER BY sp.codice
`

type ListGateStepRow struct {
	VStepProdotto VStepProdotto `json:"vstep_prodotto"`
	DerogaCad     bool          `json:"deroga_cad"`
}

// Lo STEP di ogni prodotto finito, con la deroga del fabbisogno cad_3d se c'e' (A4.5).
func (q *Queries) ListGateStep(ctx context.Context, threadID uuid.UUID) ([]ListGateStepRow, error) {
	rows, err := q.db.Query(ctx, listGateStep, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGateStepRow{}
	for rows.Next() {
		var i ListGateStepRow
		if err := rows.Scan(
			&i.VStepProdotto.ThreadID,
			&i.VStepProdotto.ComponenteID,
			&i.VStepProdotto.Codice,
			&i.VStepProdotto.StepStrutturaleID,
			&i.VStepProdotto.NStepCorrenti,
			&i.VStepProdotto.AnalisiCompleta,
			&i.VStepProdotto.MotivoParziale,
			&i.VStepProdotto.DerogaStrutturaID,
			&i.VStepProdotto.Altro3dDocumentoID,
			&i.VStepProdotto.PropostaAperta,
			&i.VStepProdotto.AttesoDaPortale,
			&i.VStepProdotto.Esito,
			&i.DerogaCad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelazioniAttive = `-- name: ListRelazioniAttive :many
SELECT r.thread_id, r.padre_id, r.figlio_id, r.qta, r.posizione, r.origine, r.confermato_da, r.creato_il FROM componente_relazione r
  JOIN componente p ON p.componente_id = r.padre_id AND p.archiviato_il IS NULL
  JOIN componente f ON f.componente_id = r.figlio_id AND f.archiviato_il IS NULL
 WHERE r.thread_id = $1
 ORDER BY r.padre_id, r.figlio_id
`

// Gli archi della working fra componenti attivi.
func (q *Queries) ListRelazioniAttive(ctx context.Context, threadID uuid.UUID) ([]ComponenteRelazione, error) {
	rows, err := q.db.Query(ctx, listRelazioniAttive, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponenteRelazione{}
	for rows.Next() {
		var i ComponenteRelazione
		if err := rows.Scan(
			&i.ThreadID,
			&i.PadreID,
			&i.FiglioID,
			&i.Qta,
			&i.Posizione,
			&i.Origine,
			&i.ConfermatoDa,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotComponenti = `-- name: SnapshotComponenti :execrows

INSERT INTO bom_versione_componente (bom_versione_id, thread_id, componente_id, codice, rev, tipo, descrizione, qta,
                                     esito_fattibilita, note_fattibilita, step_strutturale_id, step_sha256, deroga_struttura_id)
SELECT $1::uuid, c.thread_id, c.componente_id, c.codice, c.rev, c.tipo, c.descrizione, c.qta,
       c.esito_fattibilita, c.note_fattibilita, c.step_strutturale_id, d.sha256,
       CASE WHEN sp.esito IN ('presente_parziale', 'presente_non_analizzato') THEN sp.deroga_struttura_id END
  FROM componente c
  LEFT JOIN documento d ON d.documento_id = c.step_strutturale_id
  LEFT JOIN v_step_prodotto sp ON sp.componente_id = c.componente_id
 WHERE c.thread_id = $2 AND c.archiviato_il IS NULL
`

type SnapshotComponentiParams struct {
	BomVersioneID uuid.UUID `json:"bom_versione_id"`
	ThreadID      uuid.UUID `json:"thread_id"`
}

// ------------------------------------------------------------------ le istantanee (A4.6, passo 5)
// Si scrivono mentre la versione e' bozza, nella transazione che poi la congela. Contano solo i
// componenti attivi, e di loro: gli archi fra due attivi, i documenti correnti, le deroghe del
// fabbisogno in vigore. La deroga strutturale entra solo se e' servita, cioe' se lo STEP era letto in
// parte o non ancora analizzato, ed e' quella valida adesso (v_step_prodotto).
func (q *Queries) SnapshotComponenti(ctx context.Context, arg SnapshotComponentiParams) (int64, error) {
	result, err := q.db.Exec(ctx, snapshotComponenti, arg.BomVersioneID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snapshotDeroghe = `-- name: SnapshotDeroghe :execrows
INSERT INTO bom_versione_deroga (bom_versione_id, componente_id, deroga_id, tipo, motivo, utente_id, creata_il)
SELECT $1::uuid, g.componente_id, g.deroga_id, g.tipo, g.motivo, g.utente_id, g.creata_il
  FROM deroga_fabbisogno g
  JOIN componente c ON c.componente_id = g.componente_id AND c.archiviato_il IS NULL
 WHERE g.thread_id = $2
`

type SnapshotDerogheParams struct {
	BomVersioneID uuid.UUID `json:"bom_versione_id"`
	ThreadID      uuid.UUID `json:"thread_id"`
}

func (q *Queries) SnapshotDeroghe(ctx context.Context, arg SnapshotDerogheParams) (int64, error) {
	result, err := q.db.Exec(ctx, snapshotDeroghe, arg.BomVersioneID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snapshotDocumenti = `-- name: SnapshotDocumenti :execrows
INSERT INTO bom_versione_documento (bom_versione_id, componente_id, documento_id, tipo, rev, sha256, path_al_congelamento)
SELECT $1::uuid, d.componente_id, d.documento_id, d.tipo, d.rev, d.sha256, d.path_relativo
  FROM documento d
  JOIN componente c ON c.componente_id = d.componente_id AND c.archiviato_il IS NULL
 WHERE d.thread_id = $2 AND d.sostituito_da IS NULL
`

type SnapshotDocumentiParams struct {
	BomVersioneID uuid.UUID `json:"bom_versione_id"`
	ThreadID      uuid.UUID `json:"thread_id"`
}

// path_al_congelamento e' storico (R1.8): dice dove stava il file, non serve ad aprirlo.
func (q *Queries) SnapshotDocumenti(ctx context.Context, arg SnapshotDocumentiParams) (int64, error) {
	result, err := q.db.Exec(ctx, snapshotDocumenti, arg.BomVersioneID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snapshotRelazioni = `-- name: SnapshotRelazioni :execrows
INSERT INTO bom_versione_relazione (bom_versione_id, padre_id, figlio_id, qta, posizione)
SELECT $1::uuid, r.padre_id, r.figlio_id, r.qta, r.posizione
  FROM componente_relazione r
  JOIN componente p ON p.componente_id = r.padre_id AND p.archiviato_il IS NULL
  JOIN componente f ON f.componente_id = r.figlio_id AND f.archiviato_il IS NULL
 WHERE r.thread_id = $2
`

type SnapshotRelazioniParams struct {
	BomVersioneID uuid.UUID `json:"bom_versione_id"`
	ThreadID      uuid.UUID `json:"thread_id"`
}

func (q *Queries) SnapshotRelazioni(ctx context.Context, arg SnapshotRelazioniParams) (int64, error) {
	result, err := q.db.Exec(ctx, snapshotRelazioni, arg.BomVersioneID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const versioniConLoStep = `-- name: VersioniConLoStep :many
SELECT DISTINCT v.numero FROM bom_versione_componente c
  JOIN bom_versione v ON v.bom_versione_id = c.bom_versione_id
 WHERE c.step_strutturale_id = $1
 ORDER BY v.numero
`

// Le versioni congelate che registrano il documento come STEP strutturale: finche' ce n'e' una, il
// documento non cambia componente (la FK della baseline, R2.5). Serve al rifiuto che la nomina.
func (q *Queries) VersioniConLoStep(ctx context.Context, stepStrutturaleID uuid.NullUUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, versioniConLoStep, stepStrutturaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var numero int32
		if err := rows.Scan(&numero); err != nil {
			return nil, err
		}
		items = append(items, numero)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
