// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidati.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listCodiciCandidatiThread = `-- name: ListCodiciCandidatiThread :many

SELECT COALESCE(v.codice, '')::text AS codice, COALESCE(v.rev, '')::text AS rev,
       COALESCE(v.sorgente, '')::text AS sorgente, COALESCE(v.origine, '')::text AS origine,
       COALESCE(v.famiglia, '')::text AS famiglia, COALESCE(v.punteggio, 0)::int AS punteggio,
       COALESCE(v.evidenza, '')::text AS evidenza, COALESCE(v.ruolo, '')::text AS ruolo,
       v.messaggio_id, v.allegato_id, COALESCE(p.tipo_proposto::text, '')::text AS tipo_file
  FROM v_codici_candidati_thread v
  LEFT JOIN documento_proposta p ON p.allegato_id = v.allegato_id AND v.sorgente IN ('proposta_documento', 'nome_file')
 WHERE v.thread_id = $1
 ORDER BY upper(v.codice), v.sorgente, v.evidenza, v.messaggio_id
`

type ListCodiciCandidatiThreadRow struct {
	Codice      string        `json:"codice"`
	Rev         string        `json:"rev"`
	Sorgente    string        `json:"sorgente"`
	Origine     string        `json:"origine"`
	Famiglia    string        `json:"famiglia"`
	Punteggio   int32         `json:"punteggio"`
	Evidenza    string        `json:"evidenza"`
	Ruolo       string        `json:"ruolo"`
	MessaggioID uuid.UUID     `json:"messaggio_id"`
	AllegatoID  uuid.NullUUID `json:"allegato_id"`
	TipoFile    string        `json:"tipo_file"`
}

// I codici candidati di una RFQ (Blocco 8, B8.6; piano §6): le evidenze che la RFQ ha gia' prodotto.
//
// Qui non si classifica niente. v_codici_candidati_thread (0018) prende le righe da candidato_codice,
// documento_proposta e componente_proposta, gia' classificate da chi le ha scritte; il Go le unisce per
// upper(codice) (fascicolo.Unisci). Componenti e identificativi non sono evidenze: dicono se un codice e'
// gia' deciso, e li leggono le loro query.
// Una riga per evidenza, con il tipo che la proposta del documento da' al file per le righe che vengono
// dal suo nome: il nome di un file tecnico e' un'evidenza forte, quello di un'offerta no (piano §6.1).
// I testi passano da COALESCE: nella vista ruolo e' NULL fuori da candidato_codice.
func (q *Queries) ListCodiciCandidatiThread(ctx context.Context, threadID uuid.NullUUID) ([]ListCodiciCandidatiThreadRow, error) {
	rows, err := q.db.Query(ctx, listCodiciCandidatiThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodiciCandidatiThreadRow{}
	for rows.Next() {
		var i ListCodiciCandidatiThreadRow
		if err := rows.Scan(
			&i.Codice,
			&i.Rev,
			&i.Sorgente,
			&i.Origine,
			&i.Famiglia,
			&i.Punteggio,
			&i.Evidenza,
			&i.Ruolo,
			&i.MessaggioID,
			&i.AllegatoID,
			&i.TipoFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposteNodoAperte = `-- name: ListProposteNodoAperte :many
SELECT cp.proposta_id, cp.allegato_id, cp.chiave, cp.codice::text AS codice, COALESCE(cp.rev, '')::text AS rev,
       cp.nome_grezzo, cp.tipo_proposto, COALESCE(cp.nota, '')::text AS nota, a.nome_file
  FROM componente_proposta cp JOIN allegato a ON a.allegato_id = cp.allegato_id
 WHERE cp.thread_id = $1 AND cp.stato = 'aperta' AND nullif(btrim(cp.codice), '') IS NOT NULL
 ORDER BY upper(cp.codice), a.ricevuto_il, cp.allegato_id, cp.chiave
`

type ListProposteNodoAperteRow struct {
	PropostaID   uuid.UUID          `json:"proposta_id"`
	AllegatoID   uuid.UUID          `json:"allegato_id"`
	Chiave       string             `json:"chiave"`
	Codice       string             `json:"codice"`
	Rev          string             `json:"rev"`
	NomeGrezzo   string             `json:"nome_grezzo"`
	TipoProposto NullTipoComponente `json:"tipo_proposto"`
	Nota         string             `json:"nota"`
	NomeFile     string             `json:"nome_file"`
}

// I nodi proposti dagli STEP ancora aperti e con un codice, con il file da cui vengono: un codice che ne
// ha uno si porta alla sua proposta, non diventa un componente parallelo (B8.6).
func (q *Queries) ListProposteNodoAperte(ctx context.Context, threadID uuid.UUID) ([]ListProposteNodoAperteRow, error) {
	rows, err := q.db.Query(ctx, listProposteNodoAperte, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProposteNodoAperteRow{}
	for rows.Next() {
		var i ListProposteNodoAperteRow
		if err := rows.Scan(
			&i.PropostaID,
			&i.AllegatoID,
			&i.Chiave,
			&i.Codice,
			&i.Rev,
			&i.NomeGrezzo,
			&i.TipoProposto,
			&i.Nota,
			&i.NomeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
