// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fotografia.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listCandidatiCodiceThread = `-- name: ListCandidatiCodiceThread :many
SELECT c.messaggio_id, c.codice, c.ruolo, c.rev, c.origine, c.famiglia, c.punteggio
  FROM candidato_codice c JOIN messaggio m ON m.messaggio_id = c.messaggio_id
 WHERE m.thread_id = $1::uuid AND c.origine <> 'agente'
 ORDER BY c.messaggio_id, c.codice
`

type ListCandidatiCodiceThreadRow struct {
	MessaggioID uuid.UUID     `json:"messaggio_id"`
	Codice      string        `json:"codice"`
	Ruolo       RuoloCodice   `json:"ruolo"`
	Rev         string        `json:"rev"`
	Origine     OrigineCodice `json:"origine"`
	Famiglia    string        `json:"famiglia"`
	Punteggio   int16         `json:"punteggio"`
}

// I codici della mail del vecchio motore, senza quelli dell'agente LLM (origine 'agente', 0008:74): servono al
// confronto, mai al motore A.
func (q *Queries) ListCandidatiCodiceThread(ctx context.Context, threadID uuid.UUID) ([]ListCandidatiCodiceThreadRow, error) {
	rows, err := q.db.Query(ctx, listCandidatiCodiceThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidatiCodiceThreadRow{}
	for rows.Next() {
		var i ListCandidatiCodiceThreadRow
		if err := rows.Scan(
			&i.MessaggioID,
			&i.Codice,
			&i.Ruolo,
			&i.Rev,
			&i.Origine,
			&i.Famiglia,
			&i.Punteggio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientiDellaFotografia = `-- name: ListClientiDellaFotografia :many
SELECT cliente_id, ragione_sociale FROM cliente
 WHERE cliente_id = ANY($1::uuid[])
 ORDER BY cliente_id
`

type ListClientiDellaFotografiaRow struct {
	ClienteID      uuid.UUID `json:"cliente_id"`
	RagioneSociale string    `json:"ragione_sociale"`
}

// Identificativo e ragione sociale dei clienti della fotografia: la ragione sociale e' solo un controllo contro il
// file delle regole (mai una chiave), e cliente.regole non si legge (le regole del motore A vengono dai file).
func (q *Queries) ListClientiDellaFotografia(ctx context.Context, clienti []uuid.UUID) ([]ListClientiDellaFotografiaRow, error) {
	rows, err := q.db.Query(ctx, listClientiDellaFotografia, clienti)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientiDellaFotografiaRow{}
	for rows.Next() {
		var i ListClientiDellaFotografiaRow
		if err := rows.Scan(&i.ClienteID, &i.RagioneSociale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFattiDelThread = `-- name: ListFattiDelThread :many

SELECT af.sha256::text              AS sha256,
       af.versione_analizzatore,
       af.hash_configurazione::text AS hash_configurazione,
       af.fatti,
       af.calcolato_il,
       (af.fatti ? 'struttura')::boolean AS con_struttura,
       CASE WHEN af.fatti ? 'struttura'
            THEN COALESCE(struttura_motivo_parziale(af.fatti -> 'struttura'), '') ELSE '' END::text AS motivo_parziale
  FROM analisi_fatti af
 WHERE af.versione_analizzatore = $1
   AND af.hash_configurazione   = $2
   AND af.sha256 IN (SELECT a.sha256 FROM allegato a
                       JOIN messaggio m ON m.messaggio_id = a.messaggio_id
                      WHERE m.thread_id = $3::uuid AND a.sha256 IS NOT NULL
                     UNION
                     SELECT d.sha256 FROM documento d
                      WHERE d.thread_id = $3::uuid)
 ORDER BY af.sha256
`

type ListFattiDelThreadParams struct {
	VersioneAnalizzatore int16     `json:"versione_analizzatore"`
	HashConfigurazione   string    `json:"hash_configurazione"`
	ThreadID             uuid.UUID `json:"thread_id"`
}

type ListFattiDelThreadRow struct {
	Sha256               string          `json:"sha256"`
	VersioneAnalizzatore int16           `json:"versione_analizzatore"`
	HashConfigurazione   string          `json:"hash_configurazione"`
	Fatti                json.RawMessage `json:"fatti"`
	CalcolatoIl          time.Time       `json:"calcolato_il"`
	ConStruttura         bool            `json:"con_struttura"`
	MotivoParziale       string          `json:"motivo_parziale"`
}

// LA FOTOGRAFIA DEL MOTORE A (giro 5, A1c; piano A, 6.5): le sei query nuove del caricatore in sola lettura
// (core/fotorfq/caricatore). Non e' una migrazione. Tutte sono solo SELECT, senza lucchetti (niente FOR UPDATE,
// FOR SHARE, FOR KEY SHARE, nessuna funzione che scrive o blocca: struttura_motivo_parziale e' LANGUAGE sql
// IMMUTABLE), quindi valgono dentro una transazione READ ONLY; non leggono la tabella dei suggerimenti
// dell'agente, le credenziali dei worker ne' le sessioni, e nessuna colonna password_hash o regole.
// I fatti di tutti i contenuti della RFQ alla terna data: gli allegati dei messaggi del thread e i documenti del
// thread (T-04: anche un documento confermato ha i suoi fatti, per la validita' del 2D). La terna la passa chi
// chiama, letta da analizzatore_corrente NELLA STESSA transazione: mai «la riga piu' recente». motivo_parziale
// viene dalla definizione unica della 0020 (struttura_motivo_parziale), solo per i fatti con la struttura STEP
// (con_struttura): vuoto = completa. Per i fatti senza struttura (con_struttura falso) il motivo non c'e': sqlc
// non sa che un CASE senza ELSE puo' dare NULL e lo leggerebbe come testo, quindi la mancanza la dice
// con_struttura, e chi legge mette NULL. Nessun lucchetto: vale dentro una transazione READ ONLY.
func (q *Queries) ListFattiDelThread(ctx context.Context, arg ListFattiDelThreadParams) ([]ListFattiDelThreadRow, error) {
	rows, err := q.db.Query(ctx, listFattiDelThread, arg.VersioneAnalizzatore, arg.HashConfigurazione, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFattiDelThreadRow{}
	for rows.Next() {
		var i ListFattiDelThreadRow
		if err := rows.Scan(
			&i.Sha256,
			&i.VersioneAnalizzatore,
			&i.HashConfigurazione,
			&i.Fatti,
			&i.CalcolatoIl,
			&i.ConStruttura,
			&i.MotivoParziale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFattiPerSha = `-- name: ListFattiPerSha :many
SELECT af.sha256::text AS sha256, af.versione_analizzatore, af.hash_configurazione::text AS hash_configurazione,
       af.fatti, af.calcolato_il, (af.fatti ? 'struttura')::boolean AS con_struttura,
       CASE WHEN af.fatti ? 'struttura'
            THEN COALESCE(struttura_motivo_parziale(af.fatti -> 'struttura'), '') ELSE '' END::text AS motivo_parziale
  FROM analisi_fatti af
 WHERE af.sha256 = ANY($1::bpchar[])
   AND af.versione_analizzatore = $2
   AND af.hash_configurazione   = $3
 ORDER BY af.sha256
`

type ListFattiPerShaParams struct {
	Sha256               []interface{} `json:"sha256"`
	VersioneAnalizzatore int16         `json:"versione_analizzatore"`
	HashConfigurazione   string        `json:"hash_configurazione"`
}

type ListFattiPerShaRow struct {
	Sha256               string          `json:"sha256"`
	VersioneAnalizzatore int16           `json:"versione_analizzatore"`
	HashConfigurazione   string          `json:"hash_configurazione"`
	Fatti                json.RawMessage `json:"fatti"`
	CalcolatoIl          time.Time       `json:"calcolato_il"`
	ConStruttura         bool            `json:"con_struttura"`
	MotivoParziale       string          `json:"motivo_parziale"`
}

// Come ListFattiDelThread, per un elenco di contenuti: gli allegati dei messaggi senza RFQ dei casi del banco.
func (q *Queries) ListFattiPerSha(ctx context.Context, arg ListFattiPerShaParams) ([]ListFattiPerShaRow, error) {
	rows, err := q.db.Query(ctx, listFattiPerSha, arg.Sha256, arg.VersioneAnalizzatore, arg.HashConfigurazione)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFattiPerShaRow{}
	for rows.Next() {
		var i ListFattiPerShaRow
		if err := rows.Scan(
			&i.Sha256,
			&i.VersioneAnalizzatore,
			&i.HashConfigurazione,
			&i.Fatti,
			&i.CalcolatoIl,
			&i.ConStruttura,
			&i.MotivoParziale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigleUtenti = `-- name: ListSigleUtenti :many
SELECT utente_id, sigla FROM utente ORDER BY sigla, utente_id
`

type ListSigleUtentiRow struct {
	UtenteID uuid.UUID `json:"utente_id"`
	Sigla    string    `json:"sigla"`
}

// Chi ha deciso, nel rapporto del banco: identificativo e sigla. Mai password_hash.
func (q *Queries) ListSigleUtenti(ctx context.Context) ([]ListSigleUtentiRow, error) {
	rows, err := q.db.Query(ctx, listSigleUtenti)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSigleUtentiRow{}
	for rows.Next() {
		var i ListSigleUtentiRow
		if err := rows.Scan(&i.UtenteID, &i.Sigla); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriageThread = `-- name: ListTriageThread :many
SELECT pt.triage_id, pt.messaggio_id, pt.esito, pt.atto, pt.legame, pt.stato, pt.identificativi,
       pt.creato_il, pt.deciso_il
  FROM proposta_triage pt JOIN messaggio m ON m.messaggio_id = pt.messaggio_id
 WHERE m.thread_id = $1::uuid AND pt.fonte = 'deterministico'
 ORDER BY pt.messaggio_id
`

type ListTriageThreadRow struct {
	TriageID       uuid.UUID           `json:"triage_id"`
	MessaggioID    uuid.UUID           `json:"messaggio_id"`
	Esito          EsitoTriage         `json:"esito"`
	Atto           pgtype.Text         `json:"atto"`
	Legame         NullLegameOperativo `json:"legame"`
	Stato          StatoTriage         `json:"stato"`
	Identificativi []string            `json:"identificativi"`
	CreatoIl       time.Time           `json:"creato_il"`
	DecisoIl       *time.Time          `json:"deciso_il"`
}

// Il triage DETERMINISTICO dei messaggi della RFQ (fonte_triage, 0001:46): il motore A non usa mai quello
// dell'agente.
func (q *Queries) ListTriageThread(ctx context.Context, threadID uuid.UUID) ([]ListTriageThreadRow, error) {
	rows, err := q.db.Query(ctx, listTriageThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTriageThreadRow{}
	for rows.Next() {
		var i ListTriageThreadRow
		if err := rows.Scan(
			&i.TriageID,
			&i.MessaggioID,
			&i.Esito,
			&i.Atto,
			&i.Legame,
			&i.Stato,
			&i.Identificativi,
			&i.CreatoIl,
			&i.DecisoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
