// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrita.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const apriAnomaliaNas = `-- name: ApriAnomaliaNas :one
INSERT INTO nas_anomalia (documento_id, thread_id, problema, stato_db, percorso, sha_atteso, sha_trovato, dettaglio)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (documento_id) WHERE risolta_il IS NULL DO UPDATE SET
    problema = EXCLUDED.problema, stato_db = EXCLUDED.stato_db, percorso = EXCLUDED.percorso,
    sha_atteso = EXCLUDED.sha_atteso, sha_trovato = EXCLUDED.sha_trovato,
    dettaglio = EXCLUDED.dettaglio, vista_il = now()
RETURNING anomalia_id, documento_id, thread_id, problema, stato_db, percorso, sha_atteso, sha_trovato, dettaglio, rilevata_il, vista_il, risolta_il
`

type ApriAnomaliaNasParams struct {
	DocumentoID uuid.UUID   `json:"documento_id"`
	ThreadID    uuid.UUID   `json:"thread_id"`
	Problema    ProblemaNas `json:"problema"`
	StatoDb     StatoNas    `json:"stato_db"`
	Percorso    string      `json:"percorso"`
	ShaAtteso   string      `json:"sha_atteso"`
	ShaTrovato  pgtype.Text `json:"sha_trovato"`
	Dettaglio   string      `json:"dettaglio"`
}

func (q *Queries) ApriAnomaliaNas(ctx context.Context, arg ApriAnomaliaNasParams) (NasAnomalium, error) {
	row := q.db.QueryRow(ctx, apriAnomaliaNas,
		arg.DocumentoID,
		arg.ThreadID,
		arg.Problema,
		arg.StatoDb,
		arg.Percorso,
		arg.ShaAtteso,
		arg.ShaTrovato,
		arg.Dettaglio,
	)
	var i NasAnomalium
	err := row.Scan(
		&i.AnomaliaID,
		&i.DocumentoID,
		&i.ThreadID,
		&i.Problema,
		&i.StatoDb,
		&i.Percorso,
		&i.ShaAtteso,
		&i.ShaTrovato,
		&i.Dettaglio,
		&i.RilevataIl,
		&i.VistaIl,
		&i.RisoltaIl,
	)
	return i, err
}

const chiudiAnomaliaNas = `-- name: ChiudiAnomaliaNas :execrows
UPDATE nas_anomalia SET risolta_il = now() WHERE documento_id = $1 AND risolta_il IS NULL
`

func (q *Queries) ChiudiAnomaliaNas(ctx context.Context, documentoID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, chiudiAnomaliaNas, documentoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contaAnomalieNas = `-- name: ContaAnomalieNas :many
SELECT problema, count(*)::int AS n FROM nas_anomalia WHERE risolta_il IS NULL GROUP BY problema ORDER BY problema
`

type ContaAnomalieNasRow struct {
	Problema ProblemaNas `json:"problema"`
	N        int32       `json:"n"`
}

func (q *Queries) ContaAnomalieNas(ctx context.Context) ([]ContaAnomalieNasRow, error) {
	rows, err := q.db.Query(ctx, contaAnomalieNas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContaAnomalieNasRow{}
	for rows.Next() {
		var i ContaAnomalieNasRow
		if err := rows.Scan(&i.Problema, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contaAnomalieThread = `-- name: ContaAnomalieThread :one
SELECT count(*)::int FROM nas_anomalia WHERE thread_id = $1 AND risolta_il IS NULL
`

func (q *Queries) ContaAnomalieThread(ctx context.Context, threadID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, contaAnomalieThread, threadID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getAnomaliaNas = `-- name: GetAnomaliaNas :one
SELECT anomalia_id, documento_id, thread_id, problema, stato_db, percorso, sha_atteso, sha_trovato, dettaglio, rilevata_il, vista_il, risolta_il FROM nas_anomalia WHERE documento_id = $1 AND risolta_il IS NULL
`

func (q *Queries) GetAnomaliaNas(ctx context.Context, documentoID uuid.UUID) (NasAnomalium, error) {
	row := q.db.QueryRow(ctx, getAnomaliaNas, documentoID)
	var i NasAnomalium
	err := row.Scan(
		&i.AnomaliaID,
		&i.DocumentoID,
		&i.ThreadID,
		&i.Problema,
		&i.StatoDb,
		&i.Percorso,
		&i.ShaAtteso,
		&i.ShaTrovato,
		&i.Dettaglio,
		&i.RilevataIl,
		&i.VistaIl,
		&i.RisoltaIl,
	)
	return i, err
}

const getNasCreazione = `-- name: GetNasCreazione :one
SELECT job_id, percorso, sha256, creato_il FROM nas_creazione WHERE job_id = $1 AND percorso = $2
`

type GetNasCreazioneParams struct {
	JobID    int64  `json:"job_id"`
	Percorso string `json:"percorso"`
}

func (q *Queries) GetNasCreazione(ctx context.Context, arg GetNasCreazioneParams) (NasCreazione, error) {
	row := q.db.QueryRow(ctx, getNasCreazione, arg.JobID, arg.Percorso)
	var i NasCreazione
	err := row.Scan(
		&i.JobID,
		&i.Percorso,
		&i.Sha256,
		&i.CreatoIl,
	)
	return i, err
}

const insertNasCreazione = `-- name: InsertNasCreazione :exec
INSERT INTO nas_creazione (job_id, percorso, sha256) VALUES ($1, $2, $3)
ON CONFLICT (job_id, percorso) DO NOTHING
`

type InsertNasCreazioneParams struct {
	JobID    int64  `json:"job_id"`
	Percorso string `json:"percorso"`
	Sha256   string `json:"sha256"`
}

func (q *Queries) InsertNasCreazione(ctx context.Context, arg InsertNasCreazioneParams) error {
	_, err := q.db.Exec(ctx, insertNasCreazione, arg.JobID, arg.Percorso, arg.Sha256)
	return err
}

const insertNasOrfano = `-- name: InsertNasOrfano :execrows
INSERT INTO nas_orfano (thread_id, percorso, sha256, motivo, job_id, nota)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (thread_id, lower(percorso)) WHERE risolto_il IS NULL DO NOTHING
`

type InsertNasOrfanoParams struct {
	ThreadID uuid.UUID    `json:"thread_id"`
	Percorso string       `json:"percorso"`
	Sha256   pgtype.Text  `json:"sha256"`
	Motivo   MotivoOrfano `json:"motivo"`
	JobID    pgtype.Int8  `json:"job_id"`
	Nota     pgtype.Text  `json:"nota"`
}

// ------------------------------------------------------------------ A4 (B8.A4a): orfani e prove di creazione (0019)
// Una sola riga aperta per file: se c'e' gia', zero righe, e chi chiama lo dice nel risultato del job.
func (q *Queries) InsertNasOrfano(ctx context.Context, arg InsertNasOrfanoParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNasOrfano,
		arg.ThreadID,
		arg.Percorso,
		arg.Sha256,
		arg.Motivo,
		arg.JobID,
		arg.Nota,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAnomalieNas = `-- name: ListAnomalieNas :many
SELECT a.anomalia_id, a.documento_id, a.thread_id, a.problema, a.stato_db, a.percorso, a.sha_atteso, a.sha_trovato, a.dettaglio, a.rilevata_il, a.vista_il, a.risolta_il, d.nome_file, d.codice, d.rev, d.tipo, d.verificato_il,
       t.oggetto, c.ragione_sociale
FROM nas_anomalia a
JOIN documento d ON d.documento_id = a.documento_id
JOIN thread_offerta t ON t.thread_id = a.thread_id
JOIN cliente c ON c.cliente_id = t.cliente_id
WHERE a.risolta_il IS NULL
ORDER BY a.problema, a.rilevata_il
`

type ListAnomalieNasRow struct {
	NasAnomalium   NasAnomalium  `json:"nas_anomalium"`
	NomeFile       string        `json:"nome_file"`
	Codice         pgtype.Text   `json:"codice"`
	Rev            pgtype.Text   `json:"rev"`
	Tipo           TipoDocumento `json:"tipo"`
	VerificatoIl   *time.Time    `json:"verificato_il"`
	Oggetto        pgtype.Text   `json:"oggetto"`
	RagioneSociale string        `json:"ragione_sociale"`
}

func (q *Queries) ListAnomalieNas(ctx context.Context) ([]ListAnomalieNasRow, error) {
	rows, err := q.db.Query(ctx, listAnomalieNas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnomalieNasRow{}
	for rows.Next() {
		var i ListAnomalieNasRow
		if err := rows.Scan(
			&i.NasAnomalium.AnomaliaID,
			&i.NasAnomalium.DocumentoID,
			&i.NasAnomalium.ThreadID,
			&i.NasAnomalium.Problema,
			&i.NasAnomalium.StatoDb,
			&i.NasAnomalium.Percorso,
			&i.NasAnomalium.ShaAtteso,
			&i.NasAnomalium.ShaTrovato,
			&i.NasAnomalium.Dettaglio,
			&i.NasAnomalium.RilevataIl,
			&i.NasAnomalium.VistaIl,
			&i.NasAnomalium.RisoltaIl,
			&i.NomeFile,
			&i.Codice,
			&i.Rev,
			&i.Tipo,
			&i.VerificatoIl,
			&i.Oggetto,
			&i.RagioneSociale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopieNasPendenti = `-- name: ListCopieNasPendenti :many
SELECT chiave_idempotenza FROM job
WHERE tipo = 'copia_nas' AND stato IN ('pronto','in_corso') AND chiave_idempotenza IS NOT NULL
`

// Le chiavi delle copie gia' in coda. Un documento la cui copia deve ancora partire non e'
// un'anomalia: e' lavoro in corso, e metterlo in elenco vorrebbe dire chiedere a una persona di
// occuparsi di qualcosa che il sistema sta gia' facendo.
func (q *Queries) ListCopieNasPendenti(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listCopieNasPendenti)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var chiave_idempotenza pgtype.Text
		if err := rows.Scan(&chiave_idempotenza); err != nil {
			return nil, err
		}
		items = append(items, chiave_idempotenza)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentiDaVerificare = `-- name: ListDocumentiDaVerificare :many

SELECT d.documento_id, d.thread_id, d.componente_id, d.tipo, d.codice, d.rev, d.nome_file, d.estensione, d.sha256, d.bytes, d.path_relativo, d.stato_nas, d.errore_nas, d.scritto_il, d.confermato_da, d.confermato_il, d.sostituito_da, d.nota, d.verificato_il, t.cartella_relativa
FROM documento d JOIN thread_offerta t ON t.thread_id = d.thread_id
ORDER BY d.verificato_il NULLS FIRST, d.documento_id
LIMIT $1
`

type ListDocumentiDaVerificareRow struct {
	Documento        Documento   `json:"documento"`
	CartellaRelativa pgtype.Text `json:"cartella_relativa"`
}

// Integrita' NAS (blocco 5B): il ricognitore confronta il database con i file veri.
// I documenti guardati meno di recente per primi: la passata e' limitata, e a giro si arriva a tutti.
// Non si filtra per stato: un documento «scritto» va controllato proprio perche' dice di esserlo.
func (q *Queries) ListDocumentiDaVerificare(ctx context.Context, limit int32) ([]ListDocumentiDaVerificareRow, error) {
	rows, err := q.db.Query(ctx, listDocumentiDaVerificare, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentiDaVerificareRow{}
	for rows.Next() {
		var i ListDocumentiDaVerificareRow
		if err := rows.Scan(
			&i.Documento.DocumentoID,
			&i.Documento.ThreadID,
			&i.Documento.ComponenteID,
			&i.Documento.Tipo,
			&i.Documento.Codice,
			&i.Documento.Rev,
			&i.Documento.NomeFile,
			&i.Documento.Estensione,
			&i.Documento.Sha256,
			&i.Documento.Bytes,
			&i.Documento.PathRelativo,
			&i.Documento.StatoNas,
			&i.Documento.ErroreNas,
			&i.Documento.ScrittoIl,
			&i.Documento.ConfermatoDa,
			&i.Documento.ConfermatoIl,
			&i.Documento.SostituitoDa,
			&i.Documento.Nota,
			&i.Documento.VerificatoIl,
			&i.CartellaRelativa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNasOrfaniAperti = `-- name: ListNasOrfaniAperti :many
SELECT o.nas_orfano_id, o.thread_id, o.percorso, o.sha256, o.motivo, o.job_id, o.rilevato_il, o.risolto_il, o.risolto_da, o.nota, t.oggetto, t.cartella_relativa, c.ragione_sociale
FROM nas_orfano o
JOIN thread_offerta t ON t.thread_id = o.thread_id
JOIN cliente c ON c.cliente_id = t.cliente_id
WHERE o.risolto_il IS NULL
ORDER BY o.rilevato_il, o.nas_orfano_id
`

type ListNasOrfaniApertiRow struct {
	NasOrfano        NasOrfano   `json:"nas_orfano"`
	Oggetto          pgtype.Text `json:"oggetto"`
	CartellaRelativa pgtype.Text `json:"cartella_relativa"`
	RagioneSociale   string      `json:"ragione_sociale"`
}

func (q *Queries) ListNasOrfaniAperti(ctx context.Context) ([]ListNasOrfaniApertiRow, error) {
	rows, err := q.db.Query(ctx, listNasOrfaniAperti)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNasOrfaniApertiRow{}
	for rows.Next() {
		var i ListNasOrfaniApertiRow
		if err := rows.Scan(
			&i.NasOrfano.NasOrfanoID,
			&i.NasOrfano.ThreadID,
			&i.NasOrfano.Percorso,
			&i.NasOrfano.Sha256,
			&i.NasOrfano.Motivo,
			&i.NasOrfano.JobID,
			&i.NasOrfano.RilevatoIl,
			&i.NasOrfano.RisoltoIl,
			&i.NasOrfano.RisoltoDa,
			&i.NasOrfano.Nota,
			&i.Oggetto,
			&i.CartellaRelativa,
			&i.RagioneSociale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const risolviNasOrfaniDelJob = `-- name: RisolviNasOrfaniDelJob :execrows
UPDATE nas_orfano SET risolto_il = now() WHERE job_id = $1 AND risolto_il IS NULL
`

// Il passo 6 di un job riaccodato che ha tolto `da`: le righe che il suo fallimento aveva aperto si
// chiudono, dal sistema (nessun risolto_da).
func (q *Queries) RisolviNasOrfaniDelJob(ctx context.Context, jobID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, risolviNasOrfaniDelJob, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const risolviNasOrfano = `-- name: RisolviNasOrfano :execrows
UPDATE nas_orfano SET risolto_il = now(), risolto_da = $1, nota = COALESCE($2, nota)
WHERE nas_orfano_id = $3 AND risolto_il IS NULL
`

type RisolviNasOrfanoParams struct {
	RisoltoDa   uuid.NullUUID `json:"risolto_da"`
	Nota        pgtype.Text   `json:"nota"`
	NasOrfanoID int64         `json:"nas_orfano_id"`
}

func (q *Queries) RisolviNasOrfano(ctx context.Context, arg RisolviNasOrfanoParams) (int64, error) {
	result, err := q.db.Exec(ctx, risolviNasOrfano, arg.RisoltoDa, arg.Nota, arg.NasOrfanoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDocumentoVerificato = `-- name: SetDocumentoVerificato :exec
UPDATE documento SET verificato_il = now() WHERE documento_id = $1
`

func (q *Queries) SetDocumentoVerificato(ctx context.Context, documentoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDocumentoVerificato, documentoID)
	return err
}

const statoIntegritaNas = `-- name: StatoIntegritaNas :one
SELECT count(*)::int AS documenti,
       count(*) FILTER (WHERE verificato_il IS NOT NULL)::int AS verificati
FROM documento
`

type StatoIntegritaNasRow struct {
	Documenti  int32 `json:"documenti"`
	Verificati int32 `json:"verificati"`
}

func (q *Queries) StatoIntegritaNas(ctx context.Context) (StatoIntegritaNasRow, error) {
	row := q.db.QueryRow(ctx, statoIntegritaNas)
	var i StatoIntegritaNasRow
	err := row.Scan(&i.Documenti, &i.Verificati)
	return i, err
}

const ultimoControlloNas = `-- name: UltimoControlloNas :one
SELECT verificato_il::timestamptz FROM documento
WHERE verificato_il IS NOT NULL ORDER BY verificato_il DESC LIMIT 1
`

// Nessuna riga = il ricognitore non ha ancora guardato niente. E' una risposta, non un errore: una
// schermata che non segnala nulla perche' non ha mai controllato non e' una schermata tranquilla.
func (q *Queries) UltimoControlloNas(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, ultimoControlloNas)
	var verificato_il time.Time
	err := row.Scan(&verificato_il)
	return verificato_il, err
}
