// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panoramica.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listAnteprimePanoramica = `-- name: ListAnteprimePanoramica :many
SELECT d.thread_id, d.componente_id, d.codice, a.allegato_id, a.nome_file, 'documento'::text AS fonte, dp.ricevuto_il AS quando
  FROM documento d
  JOIN documento_provenienza dp ON dp.documento_id = d.documento_id
  JOIN allegato a ON a.allegato_id = dp.allegato_id
  LEFT JOIN componente ca ON ca.componente_id = d.componente_id
 WHERE d.thread_id = ANY($1::uuid[])
   AND d.tipo = 'disegno_2d' AND d.sostituito_da IS NULL AND ca.archiviato_il IS NULL
UNION ALL
SELECT p.thread_id, p.componente_id, p.codice, a.allegato_id, a.nome_file, 'proposta'::text AS fonte, p.creato_il AS quando
  FROM documento_proposta p
  JOIN allegato a ON a.allegato_id = p.allegato_id
 WHERE p.thread_id = ANY($1::uuid[])
   AND p.stato = 'aperta' AND p.tipo_proposto = 'disegno_2d'
`

type ListAnteprimePanoramicaRow struct {
	ThreadID     uuid.UUID     `json:"thread_id"`
	ComponenteID uuid.NullUUID `json:"componente_id"`
	Codice       pgtype.Text   `json:"codice"`
	AllegatoID   uuid.UUID     `json:"allegato_id"`
	NomeFile     string        `json:"nome_file"`
	Fonte        string        `json:"fonte"`
	Quando       time.Time     `json:"quando"`
}

// I disegni che possono fare da anteprima nelle RFQ date: i 2D correnti (non sostituiti, di un
// componente non archiviato) con un allegato fra le provenienze, e le proposte 2D ancora aperte. Il Go
// sceglie per ogni prodotto: prima il documento, poi la proposta; fra piu' candidati il piu' recente.
func (q *Queries) ListAnteprimePanoramica(ctx context.Context, threadIds []uuid.UUID) ([]ListAnteprimePanoramicaRow, error) {
	rows, err := q.db.Query(ctx, listAnteprimePanoramica, threadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnteprimePanoramicaRow{}
	for rows.Next() {
		var i ListAnteprimePanoramicaRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.ComponenteID,
			&i.Codice,
			&i.AllegatoID,
			&i.NomeFile,
			&i.Fonte,
			&i.Quando,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProdottiPanoramica = `-- name: ListProdottiPanoramica :many
SELECT i.thread_id, i.codice, c.componente_id, c.rev, c.descrizione
FROM identificativo_thread i
LEFT JOIN componente c ON c.thread_id = i.thread_id AND upper(c.codice) = upper(i.codice) AND c.archiviato_il IS NULL
WHERE i.thread_id = ANY($1::uuid[])
ORDER BY i.thread_id, i.creato_il, i.codice
`

type ListProdottiPanoramicaRow struct {
	ThreadID     uuid.UUID     `json:"thread_id"`
	Codice       string        `json:"codice"`
	ComponenteID uuid.NullUUID `json:"componente_id"`
	Rev          pgtype.Text   `json:"rev"`
	Descrizione  pgtype.Text   `json:"descrizione"`
}

// I prodotti delle RFQ date, uno per identificativo, anche quando il componente non c'e' ancora: il
// codice appartiene alla richiesta dal triage. Dal componente, se c'e' e non e' archiviato, vengono
// revisione e descrizione (il codice di un componente e' unico nella RFQ: al piu' una riga).
func (q *Queries) ListProdottiPanoramica(ctx context.Context, threadIds []uuid.UUID) ([]ListProdottiPanoramicaRow, error) {
	rows, err := q.db.Query(ctx, listProdottiPanoramica, threadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProdottiPanoramicaRow{}
	for rows.Next() {
		var i ListProdottiPanoramicaRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Codice,
			&i.ComponenteID,
			&i.Rev,
			&i.Descrizione,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRichiestePanoramica = `-- name: ListRichiestePanoramica :many

SELECT v.thread_id, t.cliente_id, v.cliente, c.ragione_sociale, c.peso AS peso_cliente,
       v.buyer, v.oggetto, t.riferimento_cliente, v.stato_thread, v.nome_fase, v.gg_in_fase, v.sla_gg,
       v.semaforo, v.data_inizio, v.data_scadenza, v.ultimo_aggiornamento,
       v.n_bloccanti, v.n_da_smistare, v.identificativi,
       count(*) OVER () AS totale
FROM v_cruscotto v
JOIN thread_offerta t ON t.thread_id = v.thread_id
JOIN cliente c        ON c.cliente_id = t.cliente_id
WHERE ($1::stato_thread IS NULL OR v.stato_thread = $1::stato_thread)
  AND ($2::uuid IS NULL OR t.cliente_id = $2::uuid)
  AND ($3::fase IS NULL OR v.nome_fase = $3::fase)
  AND (NOT $4::boolean OR COALESCE(v.n_bloccanti, 0) > 0)
  AND (NOT $5::boolean OR v.n_da_smistare > 0)
  AND (NOT $6::boolean OR v.semaforo = 'rosso')
  AND ($7::text IS NULL
       OR v.cliente ILIKE $7::text
       OR c.ragione_sociale ILIKE $7::text
       OR v.oggetto ILIKE $7::text
       OR t.riferimento_cliente ILIKE $7::text
       OR v.buyer ILIKE $7::text
       OR EXISTS (SELECT 1 FROM identificativo_thread i
                   WHERE i.thread_id = v.thread_id AND i.codice ILIKE $7::text))
ORDER BY
  CASE WHEN $8::text = 'priorita' THEN v.stato_thread = 'CHIUSA' END,
  CASE WHEN $8::text = 'priorita' THEN c.peso END DESC,
  CASE WHEN $8::text IN ('priorita', 'scadenza') THEN v.data_scadenza END ASC NULLS LAST,
  COALESCE(v.ultimo_aggiornamento, v.data_inizio) DESC,
  v.thread_id
LIMIT $10::int OFFSET $9::int
`

type ListRichiestePanoramicaParams struct {
	Stato          NullStatoThread `json:"stato"`
	ClienteID      uuid.NullUUID   `json:"cliente_id"`
	Fase           NullFase        `json:"fase"`
	SoloBloccanti  bool            `json:"solo_bloccanti"`
	SoloDaSmistare bool            `json:"solo_da_smistare"`
	SoloSlaCritico bool            `json:"solo_sla_critico"`
	Modello        pgtype.Text     `json:"modello"`
	Ordine         string          `json:"ordine"`
	Salta          int32           `json:"salta"`
	Limite         int32           `json:"limite"`
}

type ListRichiestePanoramicaRow struct {
	ThreadID            uuid.UUID   `json:"thread_id"`
	ClienteID           uuid.UUID   `json:"cliente_id"`
	Cliente             string      `json:"cliente"`
	RagioneSociale      string      `json:"ragione_sociale"`
	PesoCliente         int16       `json:"peso_cliente"`
	Buyer               pgtype.Text `json:"buyer"`
	Oggetto             pgtype.Text `json:"oggetto"`
	RiferimentoCliente  pgtype.Text `json:"riferimento_cliente"`
	StatoThread         StatoThread `json:"stato_thread"`
	NomeFase            NullFase    `json:"nome_fase"`
	GgInFase            pgtype.Int4 `json:"gg_in_fase"`
	SlaGg               pgtype.Int4 `json:"sla_gg"`
	Semaforo            pgtype.Text `json:"semaforo"`
	DataInizio          time.Time   `json:"data_inizio"`
	DataScadenza        *time.Time  `json:"data_scadenza"`
	UltimoAggiornamento *time.Time  `json:"ultimo_aggiornamento"`
	NBloccanti          pgtype.Int8 `json:"n_bloccanti"`
	NDaSmistare         int64       `json:"n_da_smistare"`
	Identificativi      []string    `json:"identificativi"`
	Totale              int64       `json:"totale"`
}

// La panoramica delle Richieste: una card per RFQ, e dentro una scheda per ogni codice della richiesta
// (identificativo_thread) con il disegno da guardare. Tre letture per pagina, qualunque sia il numero di
// RFQ: le RFQ, i loro prodotti, i disegni candidati all'anteprima. Le mette insieme il Go, come per la
// schermata del Fascicolo: una sola SELECT vorrebbe LEFT JOIN LATERAL, e sqlc non ne capisce la
// nullabilita' (schermata.sql).
//
// Niente migration: la testata c'e' gia' in v_cruscotto, i prodotti sono gli identificativi, e
// l'anteprima e' un dato derivato dai documenti e dalle proposte che esistono gia'.
// Le RFQ secondo i filtri della barra. Un filtro NULL (o false) non filtra. `modello` e' gia' il
// modello ILIKE ('%testo%', con % _ \ protetti dal Go) e cerca in cliente, oggetto, riferimento del
// cliente, buyer e codici della richiesta. L'ordine «priorita» e' quello di sempre (peso del cliente,
// poi scadenza), con le aperte prima delle chiuse: il punteggio dell'addendum 2 non esiste ancora.
// `totale` e' il numero di RFQ che rispondono ai filtri, prima di LIMIT: dice se ce ne sono altre.
func (q *Queries) ListRichiestePanoramica(ctx context.Context, arg ListRichiestePanoramicaParams) ([]ListRichiestePanoramicaRow, error) {
	rows, err := q.db.Query(ctx, listRichiestePanoramica,
		arg.Stato,
		arg.ClienteID,
		arg.Fase,
		arg.SoloBloccanti,
		arg.SoloDaSmistare,
		arg.SoloSlaCritico,
		arg.Modello,
		arg.Ordine,
		arg.Salta,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRichiestePanoramicaRow{}
	for rows.Next() {
		var i ListRichiestePanoramicaRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.ClienteID,
			&i.Cliente,
			&i.RagioneSociale,
			&i.PesoCliente,
			&i.Buyer,
			&i.Oggetto,
			&i.RiferimentoCliente,
			&i.StatoThread,
			&i.NomeFase,
			&i.GgInFase,
			&i.SlaGg,
			&i.Semaforo,
			&i.DataInizio,
			&i.DataScadenza,
			&i.UltimoAggiornamento,
			&i.NBloccanti,
			&i.NDaSmistare,
			&i.Identificativi,
			&i.Totale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
