// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preparazione.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decidiPropostaDocumento = `-- name: DecidiPropostaDocumento :execrows
UPDATE documento_proposta
   SET tipo_proposto = $1, codice = $2, rev = $3,
       fonte = 'operatore', confidenza = 100,
       dettagli = dettagli || jsonb_build_object('deciso_da_operatore', true)
 WHERE proposta_id = $4 AND stato = 'aperta' AND componente_id IS NULL
`

type DecidiPropostaDocumentoParams struct {
	TipoProposto TipoDocumento `json:"tipo_proposto"`
	Codice       pgtype.Text   `json:"codice"`
	Rev          pgtype.Text   `json:"rev"`
	PropostaID   uuid.UUID     `json:"proposta_id"`
}

// Una decisione su un file non ancora confermato (B8.7b, «Da verificare»): il tipo, il codice, la
// revisione. Scrive fonte = 'operatore', e da li' una lettura che arriva dopo non la riscrive
// (UpsertProposta). Solo una proposta aperta e non ancora agganciata: il codice di una proposta agganciata
// e' quello del suo componente (A2.2).
func (q *Queries) DecidiPropostaDocumento(ctx context.Context, arg DecidiPropostaDocumentoParams) (int64, error) {
	result, err := q.db.Exec(ctx, decidiPropostaDocumento,
		arg.TipoProposto,
		arg.Codice,
		arg.Rev,
		arg.PropostaID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllegatiDaPreparare = `-- name: ListAllegatiDaPreparare :many

SELECT a.allegato_id, a.messaggio_id, a.nome_file, a.bytes
  FROM allegato a
  JOIN messaggio m ON m.messaggio_id = a.messaggio_id
  JOIN documento_proposta p ON p.allegato_id = a.allegato_id
 WHERE m.thread_id = $1 AND m.canale = 'outlook'
   AND a.contenitore_id IS NULL AND a.natura = 'file'
   AND a.stato = 'grezzo' AND a.errore IS NULL AND a.path_staging IS NULL
   AND p.stato = 'aperta' AND coalesce((p.dettagli ->> 'pre_spunta')::boolean, false)
   AND (a.bytes IS NULL OR a.bytes <= $2::bigint)
 ORDER BY m.data_evento, a.indice
`

type ListAllegatiDaPreparareParams struct {
	ThreadID uuid.NullUUID `json:"thread_id"`
	MaxBytes int64         `json:"max_bytes"`
}

type ListAllegatiDaPreparareRow struct {
	AllegatoID  uuid.UUID   `json:"allegato_id"`
	MessaggioID uuid.UUID   `json:"messaggio_id"`
	NomeFile    string      `json:"nome_file"`
	Bytes       pgtype.Int8 `json:"bytes"`
}

// B8.7b: la preparazione automatica del Fascicolo. I file utili della RFQ scendono nello staging da
// soli, gli archivi fermi si estraggono, i file fermi si analizzano; la schermata sa quanto lavoro e'
// ancora in corso e si aggiorna finche' ce n'e'. Nessuna tabella nuova: si leggono allegati, proposte e
// job. Il NAS non si tocca da qui: i documenti nascono solo con la conferma.
// Gli allegati diretti della RFQ che valgono la pena di scaricare (pre_spunta nella proposta a ingest:
// tecnici, offerte, fogli di calcolo, archivi, PDF da determinare) e non sono ancora scesi: nessun
// percorso in staging, stato grezzo senza il marcatore «in coda» e senza un errore. Oltre max_bytes non
// si scaricano da soli: quel limite e' quello degli upload dei worker, e un file piu' grande fallirebbe.
func (q *Queries) ListAllegatiDaPreparare(ctx context.Context, arg ListAllegatiDaPreparareParams) ([]ListAllegatiDaPreparareRow, error) {
	rows, err := q.db.Query(ctx, listAllegatiDaPreparare, arg.ThreadID, arg.MaxBytes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllegatiDaPreparareRow{}
	for rows.Next() {
		var i ListAllegatiDaPreparareRow
		if err := rows.Scan(
			&i.AllegatoID,
			&i.MessaggioID,
			&i.NomeFile,
			&i.Bytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllegatiFermiInStaging = `-- name: ListAllegatiFermiInStaging :many
SELECT a.allegato_id, a.messaggio_id, a.contenitore_id, a.indice, a.nome_file, a.path_interno, a.estensione, a.content_type, a.natura, a.origine, a.bytes, a.sha256, a.stato, a.path_staging, a.errore, a.ricevuto_il, a.caricato_da
  FROM allegato a
  JOIN messaggio m ON m.messaggio_id = a.messaggio_id
 WHERE m.thread_id = $1 AND a.natura = 'file' AND a.stato = 'in_staging'
   AND a.path_staging IS NOT NULL AND a.sha256 IS NOT NULL
 ORDER BY m.data_evento, a.contenitore_id NULLS FIRST, a.indice
`

// I file della RFQ scesi nello staging e mai arrivati in fondo: uno zip mai estratto, un file mai
// analizzato. Succede quando il loro lavoro non e' mai stato accodato (l'analisi spenta quando il file e'
// sceso) o e' fallito; chi chiama decide se riaccodare guardando l'ultimo job con la stessa chiave.
func (q *Queries) ListAllegatiFermiInStaging(ctx context.Context, threadID uuid.NullUUID) ([]Allegato, error) {
	rows, err := q.db.Query(ctx, listAllegatiFermiInStaging, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Allegato{}
	for rows.Next() {
		var i Allegato
		if err := rows.Scan(
			&i.AllegatoID,
			&i.MessaggioID,
			&i.ContenitoreID,
			&i.Indice,
			&i.NomeFile,
			&i.PathInterno,
			&i.Estensione,
			&i.ContentType,
			&i.Natura,
			&i.Origine,
			&i.Bytes,
			&i.Sha256,
			&i.Stato,
			&i.PathStaging,
			&i.Errore,
			&i.RicevutoIl,
			&i.CaricatoDa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLavoroPendenteRfq = `-- name: ListLavoroPendenteRfq :many
WITH pendenti AS (
    SELECT j.job_id, j.tipo, j.stato, j.payload FROM job j
     WHERE j.stato IN ('pronto', 'in_corso') AND j.tipo IN ('stage_allegato', 'estrai_archivio', 'analizza_allegato')
)
SELECT p.job_id, p.tipo, p.stato, a.allegato_id, a.nome_file
  FROM pendenti p
  JOIN allegato a ON a.allegato_id = CASE WHEN p.tipo <> 'analizza_allegato' THEN (p.payload ->> 'allegato_id')::uuid END
                  OR a.sha256 = CASE WHEN p.tipo = 'analizza_allegato' THEN p.payload ->> 'sha256' END
  JOIN messaggio m ON m.messaggio_id = a.messaggio_id
 WHERE m.thread_id = $1
 ORDER BY p.job_id
`

type ListLavoroPendenteRfqRow struct {
	JobID      int64     `json:"job_id"`
	Tipo       TipoJob   `json:"tipo"`
	Stato      StatoJob  `json:"stato"`
	AllegatoID uuid.UUID `json:"allegato_id"`
	NomeFile   string    `json:"nome_file"`
}

// I lavori ancora da fare sui file della RFQ: i download (stage_allegato), le estrazioni degli archivi
// (estrai_archivio) e le analisi, che sono per contenuto (A15) e si contano in ogni RFQ che ha quel file.
// Solo i job pendenti: un job fallito o annullato non e' lavoro in corso, e una pagina che aspettasse
// quello aspetterebbe per sempre. Il CASE tiene il cast fuori dalle righe degli altri tipi di job.
func (q *Queries) ListLavoroPendenteRfq(ctx context.Context, threadID uuid.NullUUID) ([]ListLavoroPendenteRfqRow, error) {
	rows, err := q.db.Query(ctx, listLavoroPendenteRfq, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLavoroPendenteRfqRow{}
	for rows.Next() {
		var i ListLavoroPendenteRfqRow
		if err := rows.Scan(
			&i.JobID,
			&i.Tipo,
			&i.Stato,
			&i.AllegatoID,
			&i.NomeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
