// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposte.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bloccaComponenteProposta = `-- name: BloccaComponenteProposta :one
SELECT proposta_id, thread_id, allegato_id, sha256, chiave, nome_grezzo, id_grezzo, descrizione, codice, rev, origine_codice, famiglia, tipo_proposto, fonte, confidenza, evidenza, stato, componente_id, deciso_da, deciso_il, creato_il, nota FROM componente_proposta WHERE proposta_id = $1 FOR UPDATE
`

func (q *Queries) BloccaComponenteProposta(ctx context.Context, propostaID uuid.UUID) (ComponenteProposta, error) {
	row := q.db.QueryRow(ctx, bloccaComponenteProposta, propostaID)
	var i ComponenteProposta
	err := row.Scan(
		&i.PropostaID,
		&i.ThreadID,
		&i.AllegatoID,
		&i.Sha256,
		&i.Chiave,
		&i.NomeGrezzo,
		&i.IDGrezzo,
		&i.Descrizione,
		&i.Codice,
		&i.Rev,
		&i.OrigineCodice,
		&i.Famiglia,
		&i.TipoProposto,
		&i.Fonte,
		&i.Confidenza,
		&i.Evidenza,
		&i.Stato,
		&i.ComponenteID,
		&i.DecisoDa,
		&i.DecisoIl,
		&i.CreatoIl,
		&i.Nota,
	)
	return i, err
}

const bloccaRelazioneProposta = `-- name: BloccaRelazioneProposta :one
SELECT thread_id, allegato_id, padre_chiave, figlio_chiave, qta, evidenza, stato, nota, deciso_da, deciso_il, creato_il FROM relazione_proposta
WHERE thread_id = $1 AND allegato_id = $2 AND padre_chiave = $3 AND figlio_chiave = $4 FOR UPDATE
`

type BloccaRelazionePropostaParams struct {
	ThreadID     uuid.UUID `json:"thread_id"`
	AllegatoID   uuid.UUID `json:"allegato_id"`
	PadreChiave  string    `json:"padre_chiave"`
	FiglioChiave string    `json:"figlio_chiave"`
}

func (q *Queries) BloccaRelazioneProposta(ctx context.Context, arg BloccaRelazionePropostaParams) (RelazioneProposta, error) {
	row := q.db.QueryRow(ctx, bloccaRelazioneProposta,
		arg.ThreadID,
		arg.AllegatoID,
		arg.PadreChiave,
		arg.FiglioChiave,
	)
	var i RelazioneProposta
	err := row.Scan(
		&i.ThreadID,
		&i.AllegatoID,
		&i.PadreChiave,
		&i.FiglioChiave,
		&i.Qta,
		&i.Evidenza,
		&i.Stato,
		&i.Nota,
		&i.DecisoDa,
		&i.DecisoIl,
		&i.CreatoIl,
	)
	return i, err
}

const bloccaRimozioneProposta = `-- name: BloccaRimozioneProposta :one
SELECT thread_id, step_documento_id, padre_id, figlio_id, qta_working, stato, nota, deciso_da, deciso_il, creato_il FROM rimozione_proposta
WHERE thread_id = $1 AND step_documento_id = $2 AND padre_id = $3 AND figlio_id = $4 FOR UPDATE
`

type BloccaRimozionePropostaParams struct {
	ThreadID        uuid.UUID `json:"thread_id"`
	StepDocumentoID uuid.UUID `json:"step_documento_id"`
	PadreID         uuid.UUID `json:"padre_id"`
	FiglioID        uuid.UUID `json:"figlio_id"`
}

func (q *Queries) BloccaRimozioneProposta(ctx context.Context, arg BloccaRimozionePropostaParams) (RimozioneProposta, error) {
	row := q.db.QueryRow(ctx, bloccaRimozioneProposta,
		arg.ThreadID,
		arg.StepDocumentoID,
		arg.PadreID,
		arg.FiglioID,
	)
	var i RimozioneProposta
	err := row.Scan(
		&i.ThreadID,
		&i.StepDocumentoID,
		&i.PadreID,
		&i.FiglioID,
		&i.QtaWorking,
		&i.Stato,
		&i.Nota,
		&i.DecisoDa,
		&i.DecisoIl,
		&i.CreatoIl,
	)
	return i, err
}

const chiudiRimozione = `-- name: ChiudiRimozione :execrows
UPDATE rimozione_proposta SET stato = 'scartata', deciso_da = NULL, deciso_il = now(), nota = $1
WHERE thread_id = $2 AND step_documento_id = $3
  AND padre_id = $4 AND figlio_id = $5 AND stato = 'aperta'
`

type ChiudiRimozioneParams struct {
	Nota            pgtype.Text `json:"nota"`
	ThreadID        uuid.UUID   `json:"thread_id"`
	StepDocumentoID uuid.UUID   `json:"step_documento_id"`
	PadreID         uuid.UUID   `json:"padre_id"`
	FiglioID        uuid.UUID   `json:"figlio_id"`
}

// Una rimozione aperta che non vale piu' (l'arco non e' piu' nella working, o lo STEP strutturale lo
// contiene di nuovo): scartata senza chi l'ha decisa, con la nota. E' interpretazione, non decisione.
func (q *Queries) ChiudiRimozione(ctx context.Context, arg ChiudiRimozioneParams) (int64, error) {
	result, err := q.db.Exec(ctx, chiudiRimozione,
		arg.Nota,
		arg.ThreadID,
		arg.StepDocumentoID,
		arg.PadreID,
		arg.FiglioID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decidiComponenteProposta = `-- name: DecidiComponenteProposta :execrows
UPDATE componente_proposta SET stato = $1, componente_id = $2,
       deciso_da = $3, deciso_il = now()
WHERE proposta_id = $4 AND stato = 'aperta'
`

type DecidiComponentePropostaParams struct {
	Stato        StatoProposta `json:"stato"`
	ComponenteID uuid.NullUUID `json:"componente_id"`
	DecisoDa     uuid.NullUUID `json:"deciso_da"`
	PropostaID   uuid.UUID     `json:"proposta_id"`
}

func (q *Queries) DecidiComponenteProposta(ctx context.Context, arg DecidiComponentePropostaParams) (int64, error) {
	result, err := q.db.Exec(ctx, decidiComponenteProposta,
		arg.Stato,
		arg.ComponenteID,
		arg.DecisoDa,
		arg.PropostaID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decidiRelazioneProposta = `-- name: DecidiRelazioneProposta :execrows
UPDATE relazione_proposta SET stato = $1, nota = COALESCE($2, nota),
       deciso_da = $3, deciso_il = now()
WHERE thread_id = $4 AND allegato_id = $5
  AND padre_chiave = $6 AND figlio_chiave = $7 AND stato = 'aperta'
`

type DecidiRelazionePropostaParams struct {
	Stato        StatoProposta `json:"stato"`
	Nota         pgtype.Text   `json:"nota"`
	DecisoDa     uuid.NullUUID `json:"deciso_da"`
	ThreadID     uuid.UUID     `json:"thread_id"`
	AllegatoID   uuid.UUID     `json:"allegato_id"`
	PadreChiave  string        `json:"padre_chiave"`
	FiglioChiave string        `json:"figlio_chiave"`
}

func (q *Queries) DecidiRelazioneProposta(ctx context.Context, arg DecidiRelazionePropostaParams) (int64, error) {
	result, err := q.db.Exec(ctx, decidiRelazioneProposta,
		arg.Stato,
		arg.Nota,
		arg.DecisoDa,
		arg.ThreadID,
		arg.AllegatoID,
		arg.PadreChiave,
		arg.FiglioChiave,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnalisiCorrente = `-- name: GetAnalisiCorrente :one
SELECT af.sha256, af.versione_analizzatore, af.hash_configurazione, af.fatti, af.calcolato_il FROM analisi_fatti af
  JOIN analizzatore_corrente ac ON ac.versione_analizzatore = af.versione_analizzatore
                               AND ac.hash_configurazione = af.hash_configurazione
 WHERE af.sha256 = $1
`

// I fatti di un contenuto con la chiave dell'analizzatore corrente (A4.5). Nessuna riga se
// analizzatore_corrente e' vuota: nessuna analisi e' corrente, ed e' il lato che non concede.
func (q *Queries) GetAnalisiCorrente(ctx context.Context, sha256 string) (AnalisiFatti, error) {
	row := q.db.QueryRow(ctx, getAnalisiCorrente, sha256)
	var i AnalisiFatti
	err := row.Scan(
		&i.Sha256,
		&i.VersioneAnalizzatore,
		&i.HashConfigurazione,
		&i.Fatti,
		&i.CalcolatoIl,
	)
	return i, err
}

const getComponentePropostaPerChiave = `-- name: GetComponentePropostaPerChiave :one
SELECT proposta_id, thread_id, allegato_id, sha256, chiave, nome_grezzo, id_grezzo, descrizione, codice, rev, origine_codice, famiglia, tipo_proposto, fonte, confidenza, evidenza, stato, componente_id, deciso_da, deciso_il, creato_il, nota FROM componente_proposta WHERE thread_id = $1 AND allegato_id = $2 AND chiave = $3
`

type GetComponentePropostaPerChiaveParams struct {
	ThreadID   uuid.UUID `json:"thread_id"`
	AllegatoID uuid.UUID `json:"allegato_id"`
	Chiave     string    `json:"chiave"`
}

func (q *Queries) GetComponentePropostaPerChiave(ctx context.Context, arg GetComponentePropostaPerChiaveParams) (ComponenteProposta, error) {
	row := q.db.QueryRow(ctx, getComponentePropostaPerChiave, arg.ThreadID, arg.AllegatoID, arg.Chiave)
	var i ComponenteProposta
	err := row.Scan(
		&i.PropostaID,
		&i.ThreadID,
		&i.AllegatoID,
		&i.Sha256,
		&i.Chiave,
		&i.NomeGrezzo,
		&i.IDGrezzo,
		&i.Descrizione,
		&i.Codice,
		&i.Rev,
		&i.OrigineCodice,
		&i.Famiglia,
		&i.TipoProposto,
		&i.Fonte,
		&i.Confidenza,
		&i.Evidenza,
		&i.Stato,
		&i.ComponenteID,
		&i.DecisoDa,
		&i.DecisoIl,
		&i.CreatoIl,
		&i.Nota,
	)
	return i, err
}

const getPropostaDocumentoDiAllegato = `-- name: GetPropostaDocumentoDiAllegato :one
SELECT proposta_id, allegato_id, thread_id, tipo_proposto, codice, rev, componente_id, confidenza, fonte, regola_id, dettagli, stato, deciso_da, deciso_il, creato_il FROM documento_proposta WHERE allegato_id = $1
`

func (q *Queries) GetPropostaDocumentoDiAllegato(ctx context.Context, allegatoID uuid.UUID) (DocumentoProposta, error) {
	row := q.db.QueryRow(ctx, getPropostaDocumentoDiAllegato, allegatoID)
	var i DocumentoProposta
	err := row.Scan(
		&i.PropostaID,
		&i.AllegatoID,
		&i.ThreadID,
		&i.TipoProposto,
		&i.Codice,
		&i.Rev,
		&i.ComponenteID,
		&i.Confidenza,
		&i.Fonte,
		&i.RegolaID,
		&i.Dettagli,
		&i.Stato,
		&i.DecisoDa,
		&i.DecisoIl,
		&i.CreatoIl,
	)
	return i, err
}

const listAllegatiStessoFileConRfq = `-- name: ListAllegatiStessoFileConRfq :many
SELECT a.allegato_id, a.messaggio_id, a.contenitore_id, a.indice, a.nome_file, a.path_interno, a.estensione, a.content_type, a.natura, a.origine, a.bytes, a.sha256, a.stato, a.path_staging, a.errore, a.ricevuto_il, a.caricato_da, m.thread_id AS rfq_id
  FROM allegato a JOIN messaggio m ON m.messaggio_id = a.messaggio_id
 WHERE a.sha256 = $1 AND m.thread_id IS NOT NULL
 ORDER BY m.thread_id, a.ricevuto_il, a.allegato_id
`

type ListAllegatiStessoFileConRfqRow struct {
	Allegato Allegato      `json:"allegato"`
	RfqID    uuid.NullUUID `json:"rfq_id"`
}

// Ogni allegato con questo contenuto che sta in una RFQ: i fatti di uno STEP diventano proposte in
// ognuna (A1.2), ciascuna con le regole del suo cliente.
func (q *Queries) ListAllegatiStessoFileConRfq(ctx context.Context, sha256 pgtype.Text) ([]ListAllegatiStessoFileConRfqRow, error) {
	rows, err := q.db.Query(ctx, listAllegatiStessoFileConRfq, sha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllegatiStessoFileConRfqRow{}
	for rows.Next() {
		var i ListAllegatiStessoFileConRfqRow
		if err := rows.Scan(
			&i.Allegato.AllegatoID,
			&i.Allegato.MessaggioID,
			&i.Allegato.ContenitoreID,
			&i.Allegato.Indice,
			&i.Allegato.NomeFile,
			&i.Allegato.PathInterno,
			&i.Allegato.Estensione,
			&i.Allegato.ContentType,
			&i.Allegato.Natura,
			&i.Allegato.Origine,
			&i.Allegato.Bytes,
			&i.Allegato.Sha256,
			&i.Allegato.Stato,
			&i.Allegato.PathStaging,
			&i.Allegato.Errore,
			&i.Allegato.RicevutoIl,
			&i.Allegato.CaricatoDa,
			&i.RfqID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponenteProposteFile = `-- name: ListComponenteProposteFile :many

SELECT proposta_id, thread_id, allegato_id, sha256, chiave, nome_grezzo, id_grezzo, descrizione, codice, rev, origine_codice, famiglia, tipo_proposto, fonte, confidenza, evidenza, stato, componente_id, deciso_da, deciso_il, creato_il, nota FROM componente_proposta WHERE thread_id = $1 AND allegato_id = $2 ORDER BY chiave
`

type ListComponenteProposteFileParams struct {
	ThreadID   uuid.UUID `json:"thread_id"`
	AllegatoID uuid.UUID `json:"allegato_id"`
}

// Le proposte di struttura (Blocco 8, B8.5): dai fatti di uno STEP ai nodi, agli archi e alle
// rimozioni proposti per una RFQ (addendum A1.1, A1.2, A4.4).
//
// Tre strati, e qui se ne scrive uno solo: i FATTI stanno in analisi_fatti e non si toccano, le
// DECISIONI stanno in componente e componente_relazione e le prende una persona. Queste query scrivono
// l'interpretazione. Una proposta gia' decisa non si riscrive: gli upsert cambiano solo le righe aperte.
func (q *Queries) ListComponenteProposteFile(ctx context.Context, arg ListComponenteProposteFileParams) ([]ComponenteProposta, error) {
	rows, err := q.db.Query(ctx, listComponenteProposteFile, arg.ThreadID, arg.AllegatoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponenteProposta{}
	for rows.Next() {
		var i ComponenteProposta
		if err := rows.Scan(
			&i.PropostaID,
			&i.ThreadID,
			&i.AllegatoID,
			&i.Sha256,
			&i.Chiave,
			&i.NomeGrezzo,
			&i.IDGrezzo,
			&i.Descrizione,
			&i.Codice,
			&i.Rev,
			&i.OrigineCodice,
			&i.Famiglia,
			&i.TipoProposto,
			&i.Fonte,
			&i.Confidenza,
			&i.Evidenza,
			&i.Stato,
			&i.ComponenteID,
			&i.DecisoDa,
			&i.DecisoIl,
			&i.CreatoIl,
			&i.Nota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponenteProposteStessoFile = `-- name: ListComponenteProposteStessoFile :many
SELECT proposta_id, thread_id, allegato_id, sha256, chiave, nome_grezzo, id_grezzo, descrizione, codice, rev, origine_codice, famiglia, tipo_proposto, fonte, confidenza, evidenza, stato, componente_id, deciso_da, deciso_il, creato_il, nota FROM componente_proposta WHERE thread_id = $1 AND sha256 = $2 ORDER BY chiave, creato_il
`

type ListComponenteProposteStessoFileParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Sha256   string    `json:"sha256"`
}

// I nodi proposti da un contenuto in una RFQ, qualunque allegato li porti: servono a riconoscere nello
// STEP strutturale i nodi gia' decisi.
func (q *Queries) ListComponenteProposteStessoFile(ctx context.Context, arg ListComponenteProposteStessoFileParams) ([]ComponenteProposta, error) {
	rows, err := q.db.Query(ctx, listComponenteProposteStessoFile, arg.ThreadID, arg.Sha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponenteProposta{}
	for rows.Next() {
		var i ComponenteProposta
		if err := rows.Scan(
			&i.PropostaID,
			&i.ThreadID,
			&i.AllegatoID,
			&i.Sha256,
			&i.Chiave,
			&i.NomeGrezzo,
			&i.IDGrezzo,
			&i.Descrizione,
			&i.Codice,
			&i.Rev,
			&i.OrigineCodice,
			&i.Famiglia,
			&i.TipoProposto,
			&i.Fonte,
			&i.Confidenza,
			&i.Evidenza,
			&i.Stato,
			&i.ComponenteID,
			&i.DecisoDa,
			&i.DecisoIl,
			&i.CreatoIl,
			&i.Nota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProdottiConStepStrutturale = `-- name: ListProdottiConStepStrutturale :many
SELECT c.componente_id, c.thread_id, c.codice, c.rev, c.descrizione, c.qta, c.tipo, c.origine, c.materiale_testo, c.spessore_mm, c.peso_kg, c.esito_fattibilita, c.note_fattibilita, c.confermato_da, c.creato_il, c.archiviato_il, c.archiviato_da, c.motivo_archiviazione, c.step_strutturale_id FROM componente c JOIN documento d ON d.documento_id = c.step_strutturale_id
 WHERE c.thread_id = $1 AND d.sostituito_da IS NULL AND c.archiviato_il IS NULL
 ORDER BY c.codice
`

func (q *Queries) ListProdottiConStepStrutturale(ctx context.Context, threadID uuid.UUID) ([]Componente, error) {
	rows, err := q.db.Query(ctx, listProdottiConStepStrutturale, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Componente{}
	for rows.Next() {
		var i Componente
		if err := rows.Scan(
			&i.ComponenteID,
			&i.ThreadID,
			&i.Codice,
			&i.Rev,
			&i.Descrizione,
			&i.Qta,
			&i.Tipo,
			&i.Origine,
			&i.MaterialeTesto,
			&i.SpessoreMm,
			&i.PesoKg,
			&i.EsitoFattibilita,
			&i.NoteFattibilita,
			&i.ConfermatoDa,
			&i.CreatoIl,
			&i.ArchiviatoIl,
			&i.ArchiviatoDa,
			&i.MotivoArchiviazione,
			&i.StepStrutturaleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelazioneProposteFile = `-- name: ListRelazioneProposteFile :many
SELECT thread_id, allegato_id, padre_chiave, figlio_chiave, qta, evidenza, stato, nota, deciso_da, deciso_il, creato_il FROM relazione_proposta WHERE thread_id = $1 AND allegato_id = $2 ORDER BY padre_chiave, figlio_chiave
`

type ListRelazioneProposteFileParams struct {
	ThreadID   uuid.UUID `json:"thread_id"`
	AllegatoID uuid.UUID `json:"allegato_id"`
}

func (q *Queries) ListRelazioneProposteFile(ctx context.Context, arg ListRelazioneProposteFileParams) ([]RelazioneProposta, error) {
	rows, err := q.db.Query(ctx, listRelazioneProposteFile, arg.ThreadID, arg.AllegatoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RelazioneProposta{}
	for rows.Next() {
		var i RelazioneProposta
		if err := rows.Scan(
			&i.ThreadID,
			&i.AllegatoID,
			&i.PadreChiave,
			&i.FiglioChiave,
			&i.Qta,
			&i.Evidenza,
			&i.Stato,
			&i.Nota,
			&i.DecisoDa,
			&i.DecisoIl,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRimozioniDiUnoStep = `-- name: ListRimozioniDiUnoStep :many
SELECT thread_id, step_documento_id, padre_id, figlio_id, qta_working, stato, nota, deciso_da, deciso_il, creato_il FROM rimozione_proposta WHERE thread_id = $1 AND step_documento_id = $2 ORDER BY padre_id, figlio_id
`

type ListRimozioniDiUnoStepParams struct {
	ThreadID        uuid.UUID `json:"thread_id"`
	StepDocumentoID uuid.UUID `json:"step_documento_id"`
}

func (q *Queries) ListRimozioniDiUnoStep(ctx context.Context, arg ListRimozioniDiUnoStepParams) ([]RimozioneProposta, error) {
	rows, err := q.db.Query(ctx, listRimozioniDiUnoStep, arg.ThreadID, arg.StepDocumentoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RimozioneProposta{}
	for rows.Next() {
		var i RimozioneProposta
		if err := rows.Scan(
			&i.ThreadID,
			&i.StepDocumentoID,
			&i.PadreID,
			&i.FiglioID,
			&i.QtaWorking,
			&i.Stato,
			&i.Nota,
			&i.DecisoDa,
			&i.DecisoIl,
			&i.CreatoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepDellaRfq = `-- name: ListStepDellaRfq :many
SELECT a.allegato_id, a.messaggio_id, a.contenitore_id, a.indice, a.nome_file, a.path_interno, a.estensione, a.content_type, a.natura, a.origine, a.bytes, a.sha256, a.stato, a.path_staging, a.errore, a.ricevuto_il, a.caricato_da FROM allegato a JOIN messaggio m ON m.messaggio_id = a.messaggio_id
 WHERE m.thread_id = $1 AND lower(a.estensione) IN ('stp', 'step') AND a.sha256 IS NOT NULL
 ORDER BY a.ricevuto_il, a.allegato_id
`

// Gli STEP arrivati in una RFQ e scaricati (lo SHA si sa): quelli da cui possono nascere proposte.
func (q *Queries) ListStepDellaRfq(ctx context.Context, threadID uuid.NullUUID) ([]Allegato, error) {
	rows, err := q.db.Query(ctx, listStepDellaRfq, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Allegato{}
	for rows.Next() {
		var i Allegato
		if err := rows.Scan(
			&i.AllegatoID,
			&i.MessaggioID,
			&i.ContenitoreID,
			&i.Indice,
			&i.NomeFile,
			&i.PathInterno,
			&i.Estensione,
			&i.ContentType,
			&i.Natura,
			&i.Origine,
			&i.Bytes,
			&i.Sha256,
			&i.Stato,
			&i.PathStaging,
			&i.Errore,
			&i.RicevutoIl,
			&i.CaricatoDa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const motivoParziale = `-- name: MotivoParziale :one
SELECT COALESCE(struttura_motivo_parziale($1::jsonb), '')::text AS motivo
`

// Perche' una struttura non e' completa, con la definizione della 0020 (struttura_motivo_parziale):
// ” = completa. Il Go la chiede al database invece di ricalcolarla (A4.4: la definizione e' una).
func (q *Queries) MotivoParziale(ctx context.Context, struttura *json.RawMessage) (string, error) {
	row := q.db.QueryRow(ctx, motivoParziale, struttura)
	var motivo string
	err := row.Scan(&motivo)
	return motivo, err
}

const portatoreDelFile = `-- name: PortatoreDelFile :one
SELECT allegato_id FROM componente_proposta WHERE thread_id = $1 AND sha256 = $2
ORDER BY creato_il, allegato_id LIMIT 1
`

type PortatoreDelFileParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Sha256   string    `json:"sha256"`
}

// L'allegato che in questa RFQ porta le proposte di un contenuto. Lo stesso file arrivato due volte
// nella stessa RFQ propone una volta sola: due serie di nodi uguali sarebbero doppio lavoro e doppio
// conteggio nel gate.
func (q *Queries) PortatoreDelFile(ctx context.Context, arg PortatoreDelFileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, portatoreDelFile, arg.ThreadID, arg.Sha256)
	var allegato_id uuid.UUID
	err := row.Scan(&allegato_id)
	return allegato_id, err
}

const prodottoDelloStepStrutturale = `-- name: ProdottoDelloStepStrutturale :one
SELECT c.componente_id, c.thread_id, c.codice, c.rev, c.descrizione, c.qta, c.tipo, c.origine, c.materiale_testo, c.spessore_mm, c.peso_kg, c.esito_fattibilita, c.note_fattibilita, c.confermato_da, c.creato_il, c.archiviato_il, c.archiviato_da, c.motivo_archiviazione, c.step_strutturale_id FROM componente c JOIN documento d ON d.documento_id = c.step_strutturale_id
 WHERE c.thread_id = $1 AND d.sha256 = $2 AND d.sostituito_da IS NULL AND c.archiviato_il IS NULL
 ORDER BY c.codice LIMIT 1
`

type ProdottoDelloStepStrutturaleParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Sha256   string    `json:"sha256"`
}

// Il prodotto finito attivo che ha come STEP strutturale un documento corrente con questo contenuto.
func (q *Queries) ProdottoDelloStepStrutturale(ctx context.Context, arg ProdottoDelloStepStrutturaleParams) (Componente, error) {
	row := q.db.QueryRow(ctx, prodottoDelloStepStrutturale, arg.ThreadID, arg.Sha256)
	var i Componente
	err := row.Scan(
		&i.ComponenteID,
		&i.ThreadID,
		&i.Codice,
		&i.Rev,
		&i.Descrizione,
		&i.Qta,
		&i.Tipo,
		&i.Origine,
		&i.MaterialeTesto,
		&i.SpessoreMm,
		&i.PesoKg,
		&i.EsitoFattibilita,
		&i.NoteFattibilita,
		&i.ConfermatoDa,
		&i.CreatoIl,
		&i.ArchiviatoIl,
		&i.ArchiviatoDa,
		&i.MotivoArchiviazione,
		&i.StepStrutturaleID,
	)
	return i, err
}

const propostaDocumentoDaRadice = `-- name: PropostaDocumentoDaRadice :execrows
UPDATE documento_proposta SET codice = $1, rev = $2, fonte = 'regola_cliente',
       confidenza = $3, dettagli = dettagli || $4::jsonb
WHERE allegato_id = $5 AND stato = 'aperta'
`

type PropostaDocumentoDaRadiceParams struct {
	Codice     pgtype.Text     `json:"codice"`
	Rev        pgtype.Text     `json:"rev"`
	Confidenza int16           `json:"confidenza"`
	Dettagli   json.RawMessage `json:"dettagli"`
	AllegatoID uuid.UUID       `json:"allegato_id"`
}

// D16: la radice dello STEP riconosciuta da una famiglia del cliente corregge la proposta del
// documento, finche' e' aperta. regola_id resta com'e': le famiglie stanno in cliente.regole, non in
// `regola`, e la famiglia che l'ha riconosciuta va nei dettagli.
func (q *Queries) PropostaDocumentoDaRadice(ctx context.Context, arg PropostaDocumentoDaRadiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, propostaDocumentoDaRadice,
		arg.Codice,
		arg.Rev,
		arg.Confidenza,
		arg.Dettagli,
		arg.AllegatoID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const riconciliaProposteNodo = `-- name: RiconciliaProposteNodo :execrows
UPDATE componente_proposta SET stato = 'duplicato', componente_id = $1, deciso_il = now()
WHERE thread_id = $2 AND upper(codice) = upper($3::text) AND stato = 'aperta'
  AND proposta_id <> $4
`

type RiconciliaProposteNodoParams struct {
	ComponenteID uuid.NullUUID `json:"componente_id"`
	ThreadID     uuid.UUID     `json:"thread_id"`
	Codice       string        `json:"codice"`
	Esclusa      uuid.UUID     `json:"esclusa"`
}

// Un componente appena creato o agganciato riconcilia le altre proposte aperte dello stesso codice
// nella RFQ: non creano un'identita' nuova, la ritrovano (A2.3). Senza chi le ha decise: e' la stessa
// lettura che il server avrebbe dato alla prossima rianalisi.
func (q *Queries) RiconciliaProposteNodo(ctx context.Context, arg RiconciliaProposteNodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, riconciliaProposteNodo,
		arg.ComponenteID,
		arg.ThreadID,
		arg.Codice,
		arg.Esclusa,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const riconciliaProposteRelazione = `-- name: RiconciliaProposteRelazione :execrows
UPDATE relazione_proposta r SET stato = 'duplicato', deciso_il = now()
FROM componente_proposta p, componente_proposta f
WHERE r.thread_id = $1 AND r.stato = 'aperta' AND r.qta = $2
  AND p.thread_id = r.thread_id AND p.allegato_id = r.allegato_id AND p.chiave = r.padre_chiave
  AND f.thread_id = r.thread_id AND f.allegato_id = r.allegato_id AND f.chiave = r.figlio_chiave
  AND p.componente_id = $3 AND f.componente_id = $4
`

type RiconciliaProposteRelazioneParams struct {
	ThreadID uuid.UUID     `json:"thread_id"`
	Qta      int32         `json:"qta"`
	PadreID  uuid.NullUUID `json:"padre_id"`
	FiglioID uuid.NullUUID `json:"figlio_id"`
}

// Un arco appena scritto nella working riconcilia le altre proposte aperte che lo dicono uguale, da
// qualunque file della RFQ: stessi due componenti, stessa quantita'.
func (q *Queries) RiconciliaProposteRelazione(ctx context.Context, arg RiconciliaProposteRelazioneParams) (int64, error) {
	result, err := q.db.Exec(ctx, riconciliaProposteRelazione,
		arg.ThreadID,
		arg.Qta,
		arg.PadreID,
		arg.FiglioID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCodiceComponenteProposta = `-- name: SetCodiceComponenteProposta :execrows
UPDATE componente_proposta SET codice = $1, rev = $2, origine_codice = 'operatore',
       famiglia = '', confidenza = 100
WHERE proposta_id = $3 AND stato = 'aperta'
`

type SetCodiceComponentePropostaParams struct {
	Codice     pgtype.Text `json:"codice"`
	Rev        pgtype.Text `json:"rev"`
	PropostaID uuid.UUID   `json:"proposta_id"`
}

// Il codice lo scrive l'operatore, su un nodo che il server non ha saputo classificare (A1.2): origine
// 'operatore', e da qui una riclassificazione non lo tocca piu'.
func (q *Queries) SetCodiceComponenteProposta(ctx context.Context, arg SetCodiceComponentePropostaParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCodiceComponenteProposta, arg.Codice, arg.Rev, arg.PropostaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertComponenteProposta = `-- name: UpsertComponenteProposta :exec
INSERT INTO componente_proposta (thread_id, allegato_id, sha256, chiave, nome_grezzo, id_grezzo, descrizione, codice, rev,
                                 origine_codice, famiglia, tipo_proposto, fonte, confidenza, evidenza, stato, componente_id, nota, deciso_il)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12, 'step', $13, $14, $15, $16,
        $17, CASE WHEN $15::stato_proposta = 'aperta' THEN NULL ELSE now() END)
ON CONFLICT (thread_id, allegato_id, chiave) DO UPDATE SET
    sha256         = EXCLUDED.sha256,
    nome_grezzo    = EXCLUDED.nome_grezzo,
    id_grezzo      = EXCLUDED.id_grezzo,
    descrizione    = EXCLUDED.descrizione,
    codice         = CASE WHEN componente_proposta.origine_codice = 'operatore' THEN componente_proposta.codice ELSE EXCLUDED.codice END,
    rev            = CASE WHEN componente_proposta.origine_codice = 'operatore' THEN componente_proposta.rev ELSE EXCLUDED.rev END,
    origine_codice = CASE WHEN componente_proposta.origine_codice = 'operatore' THEN componente_proposta.origine_codice ELSE EXCLUDED.origine_codice END,
    famiglia       = CASE WHEN componente_proposta.origine_codice = 'operatore' THEN componente_proposta.famiglia ELSE EXCLUDED.famiglia END,
    confidenza     = CASE WHEN componente_proposta.origine_codice = 'operatore' THEN componente_proposta.confidenza ELSE EXCLUDED.confidenza END,
    tipo_proposto  = EXCLUDED.tipo_proposto,
    evidenza       = EXCLUDED.evidenza,
    stato          = EXCLUDED.stato,
    componente_id  = EXCLUDED.componente_id,
    nota           = EXCLUDED.nota,
    deciso_il      = EXCLUDED.deciso_il
WHERE componente_proposta.stato = 'aperta'
`

type UpsertComponentePropostaParams struct {
	ThreadID      uuid.UUID          `json:"thread_id"`
	AllegatoID    uuid.UUID          `json:"allegato_id"`
	Sha256        string             `json:"sha256"`
	Chiave        string             `json:"chiave"`
	NomeGrezzo    string             `json:"nome_grezzo"`
	IDGrezzo      string             `json:"id_grezzo"`
	Descrizione   pgtype.Text        `json:"descrizione"`
	Codice        pgtype.Text        `json:"codice"`
	Rev           pgtype.Text        `json:"rev"`
	OrigineCodice NullOrigineCodice  `json:"origine_codice"`
	Famiglia      string             `json:"famiglia"`
	TipoProposto  NullTipoComponente `json:"tipo_proposto"`
	Confidenza    int16              `json:"confidenza"`
	Evidenza      json.RawMessage    `json:"evidenza"`
	Stato         StatoProposta      `json:"stato"`
	ComponenteID  uuid.NullUUID      `json:"componente_id"`
	Nota          pgtype.Text        `json:"nota"`
}

// Un nodo proposto. Si riscrive solo finche' e' aperto; un codice scritto a mano dall'operatore
// (origine_codice = 'operatore') resta, anche se le regole del cliente cambiano: la riclassificazione
// vale per cio' che ha classificato il server.
func (q *Queries) UpsertComponenteProposta(ctx context.Context, arg UpsertComponentePropostaParams) error {
	_, err := q.db.Exec(ctx, upsertComponenteProposta,
		arg.ThreadID,
		arg.AllegatoID,
		arg.Sha256,
		arg.Chiave,
		arg.NomeGrezzo,
		arg.IDGrezzo,
		arg.Descrizione,
		arg.Codice,
		arg.Rev,
		arg.OrigineCodice,
		arg.Famiglia,
		arg.TipoProposto,
		arg.Confidenza,
		arg.Evidenza,
		arg.Stato,
		arg.ComponenteID,
		arg.Nota,
	)
	return err
}

const upsertRelazioneProposta = `-- name: UpsertRelazioneProposta :exec
INSERT INTO relazione_proposta (thread_id, allegato_id, padre_chiave, figlio_chiave, qta, evidenza, stato, nota, deciso_il)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, CASE WHEN $7::stato_proposta = 'aperta' THEN NULL ELSE now() END)
ON CONFLICT (thread_id, allegato_id, padre_chiave, figlio_chiave) DO UPDATE SET
    qta       = EXCLUDED.qta,
    evidenza  = EXCLUDED.evidenza,
    stato     = EXCLUDED.stato,
    nota      = EXCLUDED.nota,
    deciso_il = EXCLUDED.deciso_il
WHERE relazione_proposta.stato = 'aperta'
`

type UpsertRelazionePropostaParams struct {
	ThreadID     uuid.UUID       `json:"thread_id"`
	AllegatoID   uuid.UUID       `json:"allegato_id"`
	PadreChiave  string          `json:"padre_chiave"`
	FiglioChiave string          `json:"figlio_chiave"`
	Qta          int32           `json:"qta"`
	Evidenza     json.RawMessage `json:"evidenza"`
	Stato        StatoProposta   `json:"stato"`
	Nota         pgtype.Text     `json:"nota"`
}

// Un arco proposto, una riga per coppia (padre, figlio) del file. Solo finche' e' aperto.
func (q *Queries) UpsertRelazioneProposta(ctx context.Context, arg UpsertRelazionePropostaParams) error {
	_, err := q.db.Exec(ctx, upsertRelazioneProposta,
		arg.ThreadID,
		arg.AllegatoID,
		arg.PadreChiave,
		arg.FiglioChiave,
		arg.Qta,
		arg.Evidenza,
		arg.Stato,
		arg.Nota,
	)
	return err
}
