// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scarti.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const contaIngestScartiPerOrigine = `-- name: ContaIngestScartiPerOrigine :many
SELECT origine, count(*) AS n, max(ultimo_il) AS ultimo FROM ingest_scarto GROUP BY origine ORDER BY origine
`

type ContaIngestScartiPerOrigineRow struct {
	Origine string      `json:"origine"`
	N       int64       `json:"n"`
	Ultimo  interface{} `json:"ultimo"`
}

func (q *Queries) ContaIngestScartiPerOrigine(ctx context.Context) ([]ContaIngestScartiPerOrigineRow, error) {
	rows, err := q.db.Query(ctx, contaIngestScartiPerOrigine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContaIngestScartiPerOrigineRow{}
	for rows.Next() {
		var i ContaIngestScartiPerOrigineRow
		if err := rows.Scan(&i.Origine, &i.N, &i.Ultimo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eliminaIngestScarto = `-- name: EliminaIngestScarto :execrows
DELETE FROM ingest_scarto WHERE scarto_id = $1
`

func (q *Queries) EliminaIngestScarto(ctx context.Context, scartoID int64) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaIngestScarto, scartoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eliminaScartoPerElemento = `-- name: EliminaScartoPerElemento :execrows
DELETE FROM ingest_scarto WHERE casella_id = $1 AND entry_id = $2
`

type EliminaScartoPerElementoParams struct {
	CasellaID uuid.UUID `json:"casella_id"`
	EntryID   string    `json:"entry_id"`
}

func (q *Queries) EliminaScartoPerElemento(ctx context.Context, arg EliminaScartoPerElementoParams) (int64, error) {
	result, err := q.db.Exec(ctx, eliminaScartoPerElemento, arg.CasellaID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngestScarto = `-- name: GetIngestScarto :one
SELECT scarto_id, casella_id, entry_id, cartella, message_id, ricevuto_il, oggetto, origine, payload, errore, tentativi, primo_il, ultimo_il FROM ingest_scarto WHERE scarto_id = $1
`

func (q *Queries) GetIngestScarto(ctx context.Context, scartoID int64) (IngestScarto, error) {
	row := q.db.QueryRow(ctx, getIngestScarto, scartoID)
	var i IngestScarto
	err := row.Scan(
		&i.ScartoID,
		&i.CasellaID,
		&i.EntryID,
		&i.Cartella,
		&i.MessageID,
		&i.RicevutoIl,
		&i.Oggetto,
		&i.Origine,
		&i.Payload,
		&i.Errore,
		&i.Tentativi,
		&i.PrimoIl,
		&i.UltimoIl,
	)
	return i, err
}

const insertAgganciaLog = `-- name: InsertAgganciaLog :exec
INSERT INTO messaggio_aggancio_log (messaggio_id, thread_id, azione, utente_id, motivo)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAgganciaLogParams struct {
	MessaggioID uuid.UUID     `json:"messaggio_id"`
	ThreadID    uuid.NullUUID `json:"thread_id"`
	Azione      string        `json:"azione"`
	UtenteID    uuid.NullUUID `json:"utente_id"`
	Motivo      pgtype.Text   `json:"motivo"`
}

// Ogni decisione di aggancio lascia una traccia: automatica (utente NULL) o di una persona.
func (q *Queries) InsertAgganciaLog(ctx context.Context, arg InsertAgganciaLogParams) error {
	_, err := q.db.Exec(ctx, insertAgganciaLog,
		arg.MessaggioID,
		arg.ThreadID,
		arg.Azione,
		arg.UtenteID,
		arg.Motivo,
	)
	return err
}

const listAgganciaLog = `-- name: ListAgganciaLog :many
SELECT log_id, messaggio_id, thread_id, azione, utente_id, motivo, eseguito_il FROM messaggio_aggancio_log WHERE messaggio_id = $1 ORDER BY eseguito_il DESC
`

func (q *Queries) ListAgganciaLog(ctx context.Context, messaggioID uuid.UUID) ([]MessaggioAggancioLog, error) {
	rows, err := q.db.Query(ctx, listAgganciaLog, messaggioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessaggioAggancioLog{}
	for rows.Next() {
		var i MessaggioAggancioLog
		if err := rows.Scan(
			&i.LogID,
			&i.MessaggioID,
			&i.ThreadID,
			&i.Azione,
			&i.UtenteID,
			&i.Motivo,
			&i.EseguitoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestScarti = `-- name: ListIngestScarti :many
SELECT scarto_id, casella_id, entry_id, cartella, message_id, ricevuto_il, oggetto, origine, payload, errore, tentativi, primo_il, ultimo_il FROM ingest_scarto
WHERE ($2::varchar IS NULL OR origine = $2::varchar)
ORDER BY ultimo_il DESC LIMIT $1
`

type ListIngestScartiParams struct {
	Limit   int32       `json:"limit"`
	Origine pgtype.Text `json:"origine"`
}

func (q *Queries) ListIngestScarti(ctx context.Context, arg ListIngestScartiParams) ([]IngestScarto, error) {
	rows, err := q.db.Query(ctx, listIngestScarti, arg.Limit, arg.Origine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestScarto{}
	for rows.Next() {
		var i IngestScarto
		if err := rows.Scan(
			&i.ScartoID,
			&i.CasellaID,
			&i.EntryID,
			&i.Cartella,
			&i.MessageID,
			&i.RicevutoIl,
			&i.Oggetto,
			&i.Origine,
			&i.Payload,
			&i.Errore,
			&i.Tentativi,
			&i.PrimoIl,
			&i.UltimoIl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngestScarto = `-- name: UpsertIngestScarto :one

INSERT INTO ingest_scarto (casella_id, entry_id, cartella, message_id, ricevuto_il, oggetto, origine, payload, errore)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8, $9)
ON CONFLICT (casella_id, entry_id) DO UPDATE SET
    cartella    = EXCLUDED.cartella,
    message_id  = EXCLUDED.message_id,
    ricevuto_il = EXCLUDED.ricevuto_il,
    oggetto     = EXCLUDED.oggetto,
    origine     = EXCLUDED.origine,
    payload     = EXCLUDED.payload,
    errore      = EXCLUDED.errore,
    tentativi   = ingest_scarto.tentativi + 1,
    ultimo_il   = now()
RETURNING scarto_id, casella_id, entry_id, cartella, message_id, ricevuto_il, oggetto, origine, payload, errore, tentativi, primo_il, ultimo_il
`

type UpsertIngestScartoParams struct {
	CasellaID  uuid.UUID       `json:"casella_id"`
	EntryID    string          `json:"entry_id"`
	Cartella   pgtype.Text     `json:"cartella"`
	MessageID  pgtype.Text     `json:"message_id"`
	RicevutoIl *time.Time      `json:"ricevuto_il"`
	Oggetto    pgtype.Text     `json:"oggetto"`
	Origine    string          `json:"origine"`
	Payload    json.RawMessage `json:"payload"`
	Errore     string          `json:"errore"`
}

// Scarti dell'ingest e log delle decisioni di aggancio (migrazione 0003).
// Lo stesso elemento può fallire più volte: si tiene una riga per (casella, entry_id) con il conteggio
// dei tentativi, non una riga per tentativo, altrimenti un elemento rotto riempie la tabella da solo.
func (q *Queries) UpsertIngestScarto(ctx context.Context, arg UpsertIngestScartoParams) (IngestScarto, error) {
	row := q.db.QueryRow(ctx, upsertIngestScarto,
		arg.CasellaID,
		arg.EntryID,
		arg.Cartella,
		arg.MessageID,
		arg.RicevutoIl,
		arg.Oggetto,
		arg.Origine,
		arg.Payload,
		arg.Errore,
	)
	var i IngestScarto
	err := row.Scan(
		&i.ScartoID,
		&i.CasellaID,
		&i.EntryID,
		&i.Cartella,
		&i.MessageID,
		&i.RicevutoIl,
		&i.Oggetto,
		&i.Origine,
		&i.Payload,
		&i.Errore,
		&i.Tentativi,
		&i.PrimoIl,
		&i.UltimoIl,
	)
	return i, err
}
