// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smistamento.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const alzaPrioritaJob = `-- name: AlzaPrioritaJob :execrows
UPDATE job SET priorita = LEAST(priorita, $1::smallint)
 WHERE chiave_idempotenza = ANY($2::text[]) AND stato = 'pronto'
   AND priorita > $1::smallint
`

type AlzaPrioritaJobParams struct {
	Priorita int16    `json:"priorita"`
	Chiavi   []string `json:"chiavi"`
}

// Prima gli STEP (e i PDF) compatibili per nome con un prodotto della RFQ (A5.13.6): la coda serve per
// (priorita, job_id), e un numero piu' basso passa prima. LEAST: il flusso abbassa il numero e non lo alza
// mai; un job gia' preso (in corso) non si tocca. Idempotente.
func (q *Queries) AlzaPrioritaJob(ctx context.Context, arg AlzaPrioritaJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, alzaPrioritaJob, arg.Priorita, arg.Chiavi)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFileDelFlusso = `-- name: ListFileDelFlusso :many
SELECT a.allegato_id, a.contenitore_id, a.nome_file, a.path_interno, a.estensione, a.sha256, a.ricevuto_il, a.stato,
       c.nome_file AS nome_contenitore,
       (m.controparte_tipo <> 'fornitore' AND (m.direzione = 'entrata' OR m.canale = 'nota'))::bool AS del_cliente,
       (EXISTS (SELECT 1 FROM allegato v WHERE v.contenitore_id = a.allegato_id))::bool AS contenitore
  FROM allegato a
  JOIN messaggio m ON m.messaggio_id = a.messaggio_id
  LEFT JOIN allegato c ON c.allegato_id = a.contenitore_id
 WHERE m.thread_id = $1 AND a.natura = 'file'
 ORDER BY a.ricevuto_il, a.allegato_id
`

type ListFileDelFlussoRow struct {
	AllegatoID      uuid.UUID     `json:"allegato_id"`
	ContenitoreID   uuid.NullUUID `json:"contenitore_id"`
	NomeFile        string        `json:"nome_file"`
	PathInterno     pgtype.Text   `json:"path_interno"`
	Estensione      pgtype.Text   `json:"estensione"`
	Sha256          pgtype.Text   `json:"sha256"`
	RicevutoIl      time.Time     `json:"ricevuto_il"`
	Stato           StatoAllegato `json:"stato"`
	NomeContenitore pgtype.Text   `json:"nome_contenitore"`
	DelCliente      bool          `json:"del_cliente"`
	Contenitore     bool          `json:"contenitore"`
}

// I file della RFQ come il flusso li vede: il nome e la cartella dentro l'archivio (le evidenze del nome),
// il nome dell'archivio che li contiene, se sono a loro volta un archivio con delle voci, e se vengono da
// una fonte del cliente (la stessa condizione di ListStepDellaRfq, P27: non da un fornitore, non da una
// nostra mail in uscita fuori dal canale `nota`). Gli inline e i collegamenti non sono file da smistare. Lo
// stato dell'allegato dice se un PDF senza i fatti correnti e' gia' stato analizzato (testo «non letto, da
// rianalizzare») o no («da analizzare»): giro 4, fase 4.2.
func (q *Queries) ListFileDelFlusso(ctx context.Context, threadID uuid.NullUUID) ([]ListFileDelFlussoRow, error) {
	rows, err := q.db.Query(ctx, listFileDelFlusso, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileDelFlussoRow{}
	for rows.Next() {
		var i ListFileDelFlussoRow
		if err := rows.Scan(
			&i.AllegatoID,
			&i.ContenitoreID,
			&i.NomeFile,
			&i.PathInterno,
			&i.Estensione,
			&i.Sha256,
			&i.RicevutoIl,
			&i.Stato,
			&i.NomeContenitore,
			&i.DelCliente,
			&i.Contenitore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShaConFattiCorrenti = `-- name: ListShaConFattiCorrenti :many
SELECT DISTINCT a.sha256::text AS sha256
  FROM allegato a
  JOIN messaggio m ON m.messaggio_id = a.messaggio_id
  JOIN analisi_fatti af ON af.sha256 = a.sha256
  JOIN analizzatore_corrente ac ON ac.versione_analizzatore = af.versione_analizzatore
                               AND ac.hash_configurazione = af.hash_configurazione
 WHERE m.thread_id = $1 AND a.sha256 IS NOT NULL
 ORDER BY 1
`

// I contenuti della RFQ che hanno i fatti dell'analizzatore corrente. Solo lo sha: il flusso non legge mai
// il JSON del worker (consuma le evidenze che il core ne ha tratto: la valutazione, le righe della struttura),
// e qui vuole sapere soltanto se l'analisi c'e'.
func (q *Queries) ListShaConFattiCorrenti(ctx context.Context, threadID uuid.NullUUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listShaConFattiCorrenti, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sha256 string
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUltimiJobPerChiavi = `-- name: ListUltimiJobPerChiavi :many
SELECT DISTINCT ON (chiave_idempotenza) chiave_idempotenza::text AS chiave, stato, priorita
  FROM job
 WHERE chiave_idempotenza = ANY($1::text[])
 ORDER BY chiave_idempotenza, job_id DESC
`

type ListUltimiJobPerChiaviRow struct {
	Chiave   string   `json:"chiave"`
	Stato    StatoJob `json:"stato"`
	Priorita int16    `json:"priorita"`
}

// L'ultimo job di ogni chiave, in qualunque stato: per le analisi dei file della RFQ distingue «in attesa»
// (pronto, in corso) da «non si e' potuto leggere» (fallito) (A5.13.3, passo 2b).
func (q *Queries) ListUltimiJobPerChiavi(ctx context.Context, chiavi []string) ([]ListUltimiJobPerChiaviRow, error) {
	rows, err := q.db.Query(ctx, listUltimiJobPerChiavi, chiavi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUltimiJobPerChiaviRow{}
	for rows.Next() {
		var i ListUltimiJobPerChiaviRow
		if err := rows.Scan(&i.Chiave, &i.Stato, &i.Priorita); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scriviDestinazione = `-- name: ScriviDestinazione :execrows

UPDATE documento_proposta
   SET dettagli = jsonb_set(COALESCE(dettagli, '{}'::jsonb), '{destinazione}', $1::jsonb)
 WHERE proposta_id = $2
   AND stato = 'aperta'
   AND (dettagli -> 'destinazione' ->> 'firma') IS DISTINCT FROM $3::text
`

type ScriviDestinazioneParams struct {
	Destinazione json.RawMessage `json:"destinazione"`
	PropostaID   uuid.UUID       `json:"proposta_id"`
	Firma        string          `json:"firma"`
}

// Il flusso ancorato al prodotto (Smistamento F8, addendum A5.13). Il flusso legge lo stato della RFQ e scrive
// una cosa sola: la destinazione proposta di ogni file, dentro documento_proposta.dettagli, per le righe
// esistenti e aperte (FP3). Nessuna INSERT, nessuna tabella nuova, nessuna migrazione: le letture qui sotto
// non esistevano ancora nella forma che il flusso vuole, e alzare la priorita' di un'analisi in coda e' un
// UPDATE del job.
// La destinazione calcolata dal flusso (A5.13.6), solo su una proposta aperta e solo se e' cambiata. La
// guardia della decisione sta nel WHERE (P34): in READ COMMITTED una decisione concorrente che ha bloccato
// la riga fa rivalutare il WHERE sulla versione nuova, e l'UPDATE non tocca la riga decisa. La firma
// impedisce le riscritture uguali: ripetere l'evento non riscrive niente (prova 186).
func (q *Queries) ScriviDestinazione(ctx context.Context, arg ScriviDestinazioneParams) (int64, error) {
	result, err := q.db.Exec(ctx, scriviDestinazione, arg.Destinazione, arg.PropostaID, arg.Firma)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
